force-app/main/default/objects/ampi__Risk_Assessment__c/ampi__Risk_Assessment__c.object-meta.xml
<CustomObject>
    <description>Monitor and reassess identified risks, identify new risks, and track risk events related to projects/grants for evaluation</description>
    <label>Risk Assessment</label>
    <nameField>
        <label>Risk Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Conflict_Comments__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Comments__c</fullName>
    <label>Conflict Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Conflict_Response__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Response__c</fullName>
    <label>Conflict Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Conflict_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Response_Language_1__c</fullName>
    <label>Conflict_Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Conflict_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Response_Language_2__c</fullName>
    <label>Conflict_Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Conflict_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Response_Language_3__c</fullName>
    <label>Conflict_Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Conflict_Score__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Score__c</fullName>
    <label>Conflict Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Crime_Security_Comments__c.field-meta.xml
<CustomField>
    <fullName>Crime_Security_Comments__c</fullName>
    <label>Crime &amp; Security Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Crime_Security_Response__c.field-meta.xml
<CustomField>
    <fullName>Crime_Security_Response__c</fullName>
    <label>Crime &amp; Security Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Crime_Security_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Crime_Security_Response_Language_1__c</fullName>
    <label>Crime Security Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Crime_Security_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Crime_Security_Response_Language_2__c</fullName>
    <label>Crime Security Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Crime_Security_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Crime_Security_Response_Language_3__c</fullName>
    <label>Crime Security Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Crime_Security_Score__c.field-meta.xml
<CustomField>
    <fullName>Crime_Security_Score__c</fullName>
    <label>Crime &amp; Security Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Description_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Description_Language_1__c</fullName>
    <label>Description Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Description_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Description_Language_2__c</fullName>
    <label>Description Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Description_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Description_Language_3__c</fullName>
    <label>Description Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Description_Translated__c.field-meta.xml
<CustomField>
    <fullName>Description_Translated__c</fullName>
    <label>Description Translated</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Humanitarian_Space_Comments__c.field-meta.xml
<CustomField>
    <fullName>Humanitarian_Space_Comments__c</fullName>
    <label>Humanitarian Space Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Humanitarian_Space_Response__c.field-meta.xml
<CustomField>
    <fullName>Humanitarian_Space_Response__c</fullName>
    <label>Humanitarian Space Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Humanitarian_Space_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Humanitarian_Space_Response_Language_1__c</fullName>
    <label>Humanitarian_Space Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Humanitarian_Space_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Humanitarian_Space_Response_Language_2__c</fullName>
    <label>Humanitarian_Space Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Humanitarian_Space_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Humanitarian_Space_Response_Language_3__c</fullName>
    <label>Humanitarian_Space Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Humanitarian_Space_Score__c.field-meta.xml
<CustomField>
    <fullName>Humanitarian_Space_Score__c</fullName>
    <label>Humanitarian Space Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Infrastructure_Comments__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Comments__c</fullName>
    <label>Infrastructure Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Infrastructure_Response__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Response__c</fullName>
    <label>Infrastructure Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Infrastructure_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Response_Language_1__c</fullName>
    <label>Infrastructure Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Infrastructure_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Response_Language_2__c</fullName>
    <label>Infrastructure Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Infrastructure_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Response_Language_3__c</fullName>
    <label>Infrastructure Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Infrastructure_Score__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Score__c</fullName>
    <label>Infrastructure Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Kidnap_Comments__c.field-meta.xml
<CustomField>
    <fullName>Kidnap_Comments__c</fullName>
    <label>Kidnap Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Kidnap_Response__c.field-meta.xml
<CustomField>
    <fullName>Kidnap_Response__c</fullName>
    <label>Kidnap Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Kidnap_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Kidnap_Response_Language_1__c</fullName>
    <label>Kidnap Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Kidnap_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Kidnap_Response_Language_2__c</fullName>
    <label>Kidnap Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Kidnap_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Kidnap_Response_Language_3__c</fullName>
    <label>Kidnap Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Kidnap_Score__c.field-meta.xml
<CustomField>
    <fullName>Kidnap_Score__c</fullName>
    <label>Kidnap Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Language_Info__c.field-meta.xml
<CustomField>
    <fullName>Language_Info__c</fullName>
    <label>Language Info</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Social_Political_Comments__c.field-meta.xml
<CustomField>
    <fullName>Social_Political_Comments__c</fullName>
    <label>Social &amp; Political Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Social_Political_Response__c.field-meta.xml
<CustomField>
    <fullName>Social_Political_Response__c</fullName>
    <label>Social &amp; Political Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Social_Political_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Social_Political_Response_Language_1__c</fullName>
    <label>Social Political Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Social_Political_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Social_Political_Response_Language_2__c</fullName>
    <label>Social Political Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Social_Political_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Social_Political_Response_Language_3__c</fullName>
    <label>Social Political Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Social_Political_Score__c.field-meta.xml
<CustomField>
    <fullName>Social_Political_Score__c</fullName>
    <label>Social &amp; Political Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Terrorism_Comments__c.field-meta.xml
<CustomField>
    <fullName>Terrorism_Comments__c</fullName>
    <label>Terrorism Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Terrorism_Response__c.field-meta.xml
<CustomField>
    <fullName>Terrorism_Response__c</fullName>
    <label>Terrorism Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Terrorism_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Terrorism_Response_Language_1__c</fullName>
    <label>Terrorism Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Terrorism_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Terrorism_Response_Language_2__c</fullName>
    <label>Terrorism Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Terrorism_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Terrorism_Response_Language_3__c</fullName>
    <label>Terrorism Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Terrorism_Score__c.field-meta.xml
<CustomField>
    <fullName>Terrorism_Score__c</fullName>
    <label>Terrorism Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Total_Score__c.field-meta.xml
<CustomField>
    <fullName>Total_Score__c</fullName>
    <formula>((
IF(ISNULL(Social_Political_Score__c), 0, Social_Political_Score__c) +
IF(ISNULL(Crime_Security_Score__c), 0, Crime_Security_Score__c) +
IF(ISNULL(Conflict_Score__c), 0, Conflict_Score__c) +
IF(ISNULL(Terrorism_Score__c), 0, Terrorism_Score__c) +
IF(ISNULL(Kidnap_Score__c), 0, Kidnap_Score__c)
)/5)*20</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Overall security risk for the National Association. Calculated automatically (Average score of Social &amp; Political, Crime &amp; Security, Conflict, Terrorism and Kidnap Scores)</inlineHelpText>
    <label>National Context Risk</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RisReviewDetailsController.cls
public class RisReviewDetailsController {
     public ampi__Risk_Assessment__c riskReview {get;set;}
     public String language {get;set;}
     public String description_Translated {get;set;}
     public String conflict_Response_Translated {get;set;}
     public String crime_Security_Response_Translated {get;set;}
     public String social_Political_Response_Translated {get;set;}
     public String terrorism_Response_Translated {get;set;}
     public String kidnap_Response_Translated {get;set;}
     public String humanitarian_Space_Response_Translated {get;set;}
     public String infrastructure_Response_Translated {get;set;}

     public RisReviewDetailsController(ApexPages.StandardController controller){
         ampi__Risk_Assessment__c currentRecord = (ampi__Risk_Assessment__c) controller.getRecord();
         riskReview = getRiskReviewById(currentRecord.Id);
         language = getFullLanguageName(getCurrentShortUserLanguage());
         setTranslatedValuesOnProperties(language);
    }
    
    public void setTranslatedValuesOnProperties(String currentUserLanguage) {
        if (currentUserLanguage == 'Spanish') {
        	conflict_Response_Translated = riskReview.Conflict_Response_Language_1__c;
            crime_Security_Response_Translated = riskReview.Crime_Security_Response_Language_1__c;
            social_Political_Response_Translated = riskReview.Social_Political_Response_Language_1__c;
            terrorism_Response_Translated = riskReview.Terrorism_Response_Language_1__c;
            kidnap_Response_Translated = riskReview.Kidnap_Response_Language_1__c;
            humanitarian_Space_Response_Translated = riskReview.Humanitarian_Space_Response_Language_1__c;
            infrastructure_Response_Translated = riskReview.Infrastructure_Response_Language_1__c;
            description_Translated =  riskReview.Description_Language_1__c;
        } else if (currentUserLanguage == 'French') {
        	conflict_Response_Translated = riskReview.Conflict_Response_Language_2__c;
            crime_Security_Response_Translated = riskReview.Crime_Security_Response_Language_2__c;
            social_Political_Response_Translated = riskReview.Social_Political_Response_Language_2__c;
            terrorism_Response_Translated = riskReview.Terrorism_Response_Language_2__c;
            kidnap_Response_Translated = riskReview.Kidnap_Response_Language_2__c;
            humanitarian_Space_Response_Translated = riskReview.Humanitarian_Space_Response_Language_2__c;
            infrastructure_Response_Translated = riskReview.Infrastructure_Response_Language_2__c;
            description_Translated =  riskReview.Description_Language_2__c;
        } else if (currentUserLanguage == 'Russian') {
        	conflict_Response_Translated = riskReview.Conflict_Response_Language_3__c;
            crime_Security_Response_Translated = riskReview.Crime_Security_Response_Language_3__c;
            social_Political_Response_Translated = riskReview.Social_Political_Response_Language_3__c;
            terrorism_Response_Translated = riskReview.Terrorism_Response_Language_3__c;
            kidnap_Response_Translated = riskReview.Kidnap_Response_Language_3__c;
            humanitarian_Space_Response_Translated = riskReview.Humanitarian_Space_Response_Language_3__c;
            infrastructure_Response_Translated = riskReview.Infrastructure_Response_Language_3__c;
            description_Translated =  riskReview.Description_Language_3__c;
        } else {
        	conflict_Response_Translated = riskReview.Conflict_Response__c;        
            crime_Security_Response_Translated = riskReview.Crime_Security_Response__c;
            social_Political_Response_Translated = riskReview.Social_Political_Response__c;
            terrorism_Response_Translated = riskReview.Terrorism_Response__c;
            kidnap_Response_Translated = riskReview.Kidnap_Response__c;
            humanitarian_Space_Response_Translated = riskReview.Humanitarian_Space_Response__c;
            infrastructure_Response_Translated = riskReview.Infrastructure_Response__c;
            description_Translated =  riskReview.Description__c;
        }
        
        
    }
	public static ampi__Risk_Assessment__c getRiskReviewById(String riskAssessmentId) {
		return [SELECT Conflict_Comments__c, 
                Conflict_Response__c,
                Conflict_Response_Language_1__c,
                Conflict_Response_Language_2__c,
                Conflict_Response_Language_3__c,
                Conflict_Score__c,
                Crime_Security_Comments__c,
                Crime_Security_Response__c,
                Crime_Security_Response_Language_1__c,
                Crime_Security_Response_Language_2__c,
                Crime_Security_Response_Language_3__c,
                Crime_Security_Score__c,
                Description__c,
                Description_Language_1__c,
                Description_Language_2__c,
                Description_Language_3__c,
                Description_Translated__c,
                Humanitarian_Space_Comments__c,
                Humanitarian_Space_Response__c,
                Humanitarian_Space_Response_Language_1__c,
                Humanitarian_Space_Response_Language_2__c,
                Humanitarian_Space_Response_Language_3__c,
                Humanitarian_Space_Score__c,
                Id,
                Infrastructure_Comments__c,
                Infrastructure_Response__c,
                Infrastructure_Response_Language_1__c,
                Infrastructure_Response_Language_2__c,
                Infrastructure_Response_Language_3__c,
                Infrastructure_Score__c,
                Kidnap_Comments__c,
                Kidnap_Response__c,
                Kidnap_Response_Language_1__c,
                Kidnap_Response_Language_2__c,
                Kidnap_Response_Language_3__c,
                Kidnap_Score__c,
                Language_Info__c,
                Social_Political_Comments__c,
                Social_Political_Response__c,
                Social_Political_Response_Language_1__c,
                Social_Political_Response_Language_2__c,
                Social_Political_Response_Language_3__c,
                Social_Political_Score__c,
                Terrorism_Comments__c,
                Terrorism_Response__c,
                Terrorism_Response_Language_1__c,
                Terrorism_Response_Language_2__c,
                Terrorism_Response_Language_3__c,
                Terrorism_Score__c,
				Total_Score__c FROM ampi__Risk_Assessment__c WHERE Id =: riskAssessmentId];
	}
    public static String getCurrentShortUserLanguage() {
        User u = [SELECT toLabel(LanguageLocaleKey) FROM User WHERE Id = :UserInfo.getUserId()];		
		return u.LanguageLocaleKey.trim();    
    }
    
    public static String getFullLanguageName(String shortLanguageCode) { 
		System.debug('#### getFullLanguageName: ' + shortLanguageCode);
        if (shortLanguageCode == 'Español') {
              return 'Spanish';
        } else if (shortLanguageCode == 'Русский') {
			  return 'Russian';
        } else if (shortLanguageCode == 'Français') {
              return 'French';
        } else {
			return 'English';
		}
    }
}