force-app/main/default/objects/ampi__Risk_Assessment__c/ampi__Risk_Assessment__c.object-meta.xml
<CustomObject>
    <description>Monitor and reassess identified risks, identify new risks, and track risk events related to projects/grants for evaluation</description>
    <label>Risk Assessment</label>
    <nameField>
        <label>Risk Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/National_Association__c.field-meta.xml
<CustomField>
    <fullName>National_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Association</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Risk Reviews: National Security Context</relationshipLabel>
    <relationshipName>Risk_Reviews_National_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/changeNARecordTypeRiskForAllFields_Test.cls
@isTest 
private class changeNARecordTypeRiskForAllFields_Test {

	@isTest
	private static void changeNARecordTypeRiskForAllFields_RecordTypeUpdatedToEdit() {
		User u = TestDataFactory.CreateUserFromSystemAdmin();
		
		Id recordTypeIDForNewNARisk = Schema.getGlobalDescribe().get('ampi__Risk_Assessment__c').getDescribe().getRecordTypeInfosByName().get('New National Security Context').getRecordTypeId();
		Id recordTypeIDForEditNARisk = Schema.getGlobalDescribe().get('ampi__Risk_Assessment__c').getDescribe().getRecordTypeInfosByName().get('National Security Context').getRecordTypeId();
		
		Contact newContact = TestDataFactory.createContact(u.Email);
		System.debug('###newContact:' + newContact);
		
		Account newAccount = TestDataFactory.createOrganisation(newContact.Id);
		System.debug('###newAccount:' + newAccount);		

		ampi__Risk_Assessment__c newRiskAssessment = new ampi__Risk_Assessment__c();
		newRiskAssessment.RecordTypeId = recordTypeIDForNewNARisk;
		newRiskAssessment.National_Association__c = newAccount.Id;
		newRiskAssessment.Name = 'Test name Risk Assessment ' + TestDataFactory.getCurrentDateString();
		newRiskAssessment.Description__c  = 'Test desc Risk Assessment ' + TestDataFactory.getCurrentDateString();
		
		System.debug('##### UserInfo.getUserEmail():' + UserInfo.getUserEmail());
		
		Test.startTest();
		
		System.runAs(u) {
			insert newRiskAssessment;
			System.debug('##### newRiskAssessment:' + newRiskAssessment);
		 
			List<ampi__Risk_Assessment__c> newRiskAssessments = [SELECT RecordTypeId FROM ampi__Risk_Assessment__c WHERE Name =: newRiskAssessment.Name];
			System.debug('##### newRiskAssessment count:' + newRiskAssessments.size());

			System.assertEquals(true, newRiskAssessments.size() > 0 && newRiskAssessments.get(0).RecordTypeId == recordTypeIDForEditNARisk);		
		}

		Test.stopTest();
	}
}