force-app/main/default/objects/ampi__Risk_Assessment__c/ampi__Risk_Assessment__c.object-meta.xml
<CustomObject>
    <description>Monitor and reassess identified risks, identify new risks, and track risk events related to projects/grants for evaluation</description>
    <label>Risk Assessment</label>
    <nameField>
        <label>Risk Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Conflict_Response__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Response__c</fullName>
    <label>Conflict Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Conflict_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Response_Language_1__c</fullName>
    <label>Conflict_Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Conflict_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Response_Language_2__c</fullName>
    <label>Conflict_Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Conflict_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Response_Language_3__c</fullName>
    <label>Conflict_Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Crime_Security_Response__c.field-meta.xml
<CustomField>
    <fullName>Crime_Security_Response__c</fullName>
    <label>Crime &amp; Security Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Crime_Security_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Crime_Security_Response_Language_1__c</fullName>
    <label>Crime Security Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Crime_Security_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Crime_Security_Response_Language_2__c</fullName>
    <label>Crime Security Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Crime_Security_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Crime_Security_Response_Language_3__c</fullName>
    <label>Crime Security Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Humanitarian_Space_Response__c.field-meta.xml
<CustomField>
    <fullName>Humanitarian_Space_Response__c</fullName>
    <label>Humanitarian Space Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Humanitarian_Space_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Humanitarian_Space_Response_Language_1__c</fullName>
    <label>Humanitarian_Space Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Humanitarian_Space_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Humanitarian_Space_Response_Language_2__c</fullName>
    <label>Humanitarian_Space Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Humanitarian_Space_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Humanitarian_Space_Response_Language_3__c</fullName>
    <label>Humanitarian_Space Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Infrastructure_Response__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Response__c</fullName>
    <label>Infrastructure Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Infrastructure_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Response_Language_1__c</fullName>
    <label>Infrastructure Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Infrastructure_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Response_Language_2__c</fullName>
    <label>Infrastructure Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Infrastructure_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Response_Language_3__c</fullName>
    <label>Infrastructure Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Kidnap_Response__c.field-meta.xml
<CustomField>
    <fullName>Kidnap_Response__c</fullName>
    <label>Kidnap Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Kidnap_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Kidnap_Response_Language_1__c</fullName>
    <label>Kidnap Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Kidnap_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Kidnap_Response_Language_2__c</fullName>
    <label>Kidnap Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Kidnap_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Kidnap_Response_Language_3__c</fullName>
    <label>Kidnap Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Language_Info__c.field-meta.xml
<CustomField>
    <fullName>Language_Info__c</fullName>
    <label>Language Info</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Social_Political_Response__c.field-meta.xml
<CustomField>
    <fullName>Social_Political_Response__c</fullName>
    <label>Social &amp; Political Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Social_Political_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Social_Political_Response_Language_1__c</fullName>
    <label>Social Political Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Social_Political_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Social_Political_Response_Language_2__c</fullName>
    <label>Social Political Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Social_Political_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Social_Political_Response_Language_3__c</fullName>
    <label>Social Political Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Terrorism_Response__c.field-meta.xml
<CustomField>
    <fullName>Terrorism_Response__c</fullName>
    <label>Terrorism Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Terrorism_Response_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Terrorism_Response_Language_1__c</fullName>
    <label>Terrorism Response Language 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Terrorism_Response_Language_2__c.field-meta.xml
<CustomField>
    <fullName>Terrorism_Response_Language_2__c</fullName>
    <label>Terrorism Response Language 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Terrorism_Response_Language_3__c.field-meta.xml
<CustomField>
    <fullName>Terrorism_Response_Language_3__c</fullName>
    <label>Terrorism Response Language 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NA_Risk_Matrix__mdt/NA_Risk_Matrix__mdt.object-meta.xml
<CustomObject>
    <label>NA Risk Matrix</label>
    <pluralLabel>NA Risk Matrixes</pluralLabel>
</CustomObject>

force-app/main/default/objects/NA_Risk_Matrix__mdt/fields/Description_English__c.field-meta.xml
<CustomField>
    <fullName>Description_English__c</fullName>
    <label>Description English</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NA_Risk_Matrix__mdt/fields/Description_French__c.field-meta.xml
<CustomField>
    <fullName>Description_French__c</fullName>
    <label>Description French</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NA_Risk_Matrix__mdt/fields/Description_Russian__c.field-meta.xml
<CustomField>
    <fullName>Description_Russian__c</fullName>
    <label>Description Russian</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NA_Risk_Matrix__mdt/fields/Description_Spanish__c.field-meta.xml
<CustomField>
    <fullName>Description_Spanish__c</fullName>
    <label>Description Spanish</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TranslateRiskReviewInfo.cls
public class TranslateRiskReviewInfo {
  @InvocableMethod(label='Update Risk Reviews' description='Updating current risk review with the according translation by current user language.' category='Risk Review')
  public static void updateCurrentRiskReview(List<ID> ids) {
	List<ampi__Risk_Assessment__c> listRiskReviews = [SELECT Id, Language_Info__c, 
																 Kidnap_Response__c, Kidnap_Response_Language_1__c, Kidnap_Response_Language_2__c, Kidnap_Response_Language_3__c,
																 Infrastructure_Response__c, Infrastructure_Response_Language_1__c, Infrastructure_Response_Language_2__c, Infrastructure_Response_Language_3__c,
																 Humanitarian_Space_Response__c, Humanitarian_Space_Response_Language_1__c, Humanitarian_Space_Response_Language_2__c, Humanitarian_Space_Response_Language_3__c,
																 Crime_Security_Response__c, Crime_Security_Response_Language_1__c, Crime_Security_Response_Language_2__c, Crime_Security_Response_Language_3__c,
																 Conflict_Response__c, Conflict_Response_Language_1__c, Conflict_Response_Language_2__c, Conflict_Response_Language_3__c,
																 Social_Political_Response__c, Social_Political_Response_Language_1__c, Social_Political_Response_Language_2__c, Social_Political_Response_Language_3__c,
																 Terrorism_Response__c, Terrorism_Response_Language_1__c, Terrorism_Response_Language_2__c, Terrorism_Response_Language_3__c
                                                      FROM ampi__Risk_Assessment__c WHERE Id =:ids];
    
	User u = [SELECT toLabel(LanguageLocaleKey) FROM User WHERE Id = :UserInfo.getUserId()];
	String shortDestination = u.LanguageLocaleKey.left(2).toLowerCase();
    String destination = GetFullLanguageName(shortDestination);
            
    String query = 'SELECT Description_Russian__c, Description_Spanish__c,  Description_English__c, Description_French__c FROM NA_Risk_Matrix__mdt';
	List<sObject> matrix = Database.query(query);  
    System.debug('####Matrix items: ' + matrix);

	for (sObject item: matrix) {
        //System.debug('##### listRiskReviews[0].Kidnap_Response__c:' + listRiskReviews[0].Kidnap_Response__c);
        //System.debug('##### (String)item.get(Description_destination__c):' + (String)item.get('Description_' + destination + '__c'));
        if (listRiskReviews[0].Kidnap_Response__c == (String)item.get('Description_' + destination + '__c')) {
            System.debug('!Enterhere');
			listRiskReviews[0].Kidnap_Response__c = (String)item.get('Description_English__c');
            listRiskReviews[0].Kidnap_Response_Language_1__c = (String)item.get('Description_Spanish__c');
            listRiskReviews[0].Kidnap_Response_Language_2__c = (String)item.get('Description_French__c');
            listRiskReviews[0].Kidnap_Response_Language_3__c = (String)item.get('Description_Russian__c');
        }
		if (listRiskReviews[0].Infrastructure_Response__c == (String)item.get('Description_' + destination + '__c')) {
            System.debug('!Enterhere1');
			listRiskReviews[0].Infrastructure_Response__c = (String)item.get('Description_English__c');
            listRiskReviews[0].Infrastructure_Response_Language_1__c = (String)item.get('Description_Spanish__c');
            listRiskReviews[0].Infrastructure_Response_Language_2__c = (String)item.get('Description_French__c');
            listRiskReviews[0].Infrastructure_Response_Language_3__c = (String)item.get('Description_Russian__c');
        }
        if (listRiskReviews[0].Humanitarian_Space_Response__c == (String)item.get('Description_' + destination + '__c')) {
            System.debug('!Enterhere2');
			listRiskReviews[0].Humanitarian_Space_Response__c = (String)item.get('Description_English__c');
            listRiskReviews[0].Humanitarian_Space_Response_Language_1__c = (String)item.get('Description_Spanish__c');
            listRiskReviews[0].Humanitarian_Space_Response_Language_2__c = (String)item.get('Description_French__c');
            listRiskReviews[0].Humanitarian_Space_Response_Language_3__c = (String)item.get('Description_Russian__c');            
        }
        if (listRiskReviews[0].Crime_Security_Response__c == (String)item.get('Description_' + destination + '__c')) {
            System.debug('!Enterhere3');
			listRiskReviews[0].Crime_Security_Response__c = (String)item.get('Description_English__c');
            listRiskReviews[0].Crime_Security_Response_Language_1__c = (String)item.get('Description_Spanish__c');
            listRiskReviews[0].Crime_Security_Response_Language_2__c = (String)item.get('Description_French__c');
            listRiskReviews[0].Crime_Security_Response_Language_3__c = (String)item.get('Description_Russian__c');
        }
        if (listRiskReviews[0].Conflict_Response__c == (String)item.get('Description_' + destination + '__c')) {
            System.debug('!Enterhere4');
			listRiskReviews[0].Conflict_Response__c = (String)item.get('Description_English__c');
            listRiskReviews[0].Conflict_Response_Language_1__c = (String)item.get('Description_Spanish__c');
            listRiskReviews[0].Conflict_Response_Language_2__c = (String)item.get('Description_French__c');
            listRiskReviews[0].Conflict_Response_Language_3__c = (String)item.get('Description_Russian__c');
        }
        if (listRiskReviews[0].Social_Political_Response__c == (String)item.get('Description_' + destination + '__c')) {
            System.debug('!Enterhere5');
			listRiskReviews[0].Social_Political_Response__c = (String)item.get('Description_English__c');
            listRiskReviews[0].Social_Political_Response_Language_1__c = (String)item.get('Description_Spanish__c');
            listRiskReviews[0].Social_Political_Response_Language_2__c = (String)item.get('Description_French__c');
            listRiskReviews[0].Social_Political_Response_Language_3__c = (String)item.get('Description_Russian__c');
        }
        if (listRiskReviews[0].Terrorism_Response__c == (String)item.get('Description_' + destination + '__c')) {
			System.debug('!Enterhere6');
            listRiskReviews[0].Terrorism_Response__c = (String)item.get('Description_English__c');
            listRiskReviews[0].Terrorism_Response_Language_1__c = (String)item.get('Description_Spanish__c');
            listRiskReviews[0].Terrorism_Response_Language_2__c = (String)item.get('Description_French__c');
            listRiskReviews[0].Terrorism_Response_Language_3__c = (String)item.get('Description_Russian__c');            
        }
     }
	 listRiskReviews[0].Language_Info__c = shortDestination;            
     update listRiskReviews;
   }
    
    public static String GetFullLanguageName(String shortLanguageCode) { 
        if (shortLanguageCode == 'es') {
              return 'Spanish';
        } else if (shortLanguageCode == 'ru') {
              return 'Russian';
        } else if (shortLanguageCode == 'fr') {
              return 'French';
        }
        return 'English';
    }
}