force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
            <value>
                <fullName>Project Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>IF(CreatedBy.FirstName = &apos;LUCY&apos; &amp;&amp; CreatedBy.LastName = &apos;Service Account&apos; &amp;&amp; RecordType.DeveloperName = &quot;Transition&quot; &amp;&amp;  ISPICKVAL(Transition_Project_Type__c, &apos;Construction&apos;) = FALSE &amp;&amp; New_PU_Count__c = 0, FALSE, TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <description>Defined by contract with institutional donor, major corporate or foundation following PCM/RBM. Funded by int. or local funds. Can take place at programme, national or multi-country level. If in response to a humanitarian crisis, indicate in project setup.</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Reporting_Period__c/ampi__Reporting_Period__c.object-meta.xml
<CustomObject>
    <description>A period of time for which a project&apos;s targets must be set and results reported</description>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Reporting Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Label__c.field-meta.xml
<CustomField>
    <fullName>ampi__Label__c</fullName>
    <description>Text field to specify the human readable name of reporting period.</description>
    <inlineHelpText>Create a name for your reporting period that matches the duration of time that results are reported on. For example, for annual data, enter the “year name”. For quarterly data, enter “Q1 [year name]”.</inlineHelpText>
    <label>Reporting Period Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Project to which a Reporting Period belongs</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Reporting Periods</relationshipLabel>
    <relationshipName>Project_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Report_Type__c.field-meta.xml
<CustomField>
    <fullName>ampi__Report_Type__c</fullName>
    <description>Duration of time that results are reported on. This field determines what Project Indicator Reporting Period junction records are generated by the Reporting Period triggers.</description>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Life of Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Reporting_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Period_End_Date__c</fullName>
    <description>Date field to store the end date for this reporting period. This field determines the primary order in which Reporting Periods are displayed in the dropdown picklist on SetTargets and AddResults.</description>
    <label>Reporting Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Reporting_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Period_Start_Date__c</fullName>
    <description>Date field to store the start date for this reporting period. This field determines the secondary order in which Reporting Periods are displayed in the dropdown picklist on SetTargets and AddResults.</description>
    <label>Reporting Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MonitoringPeriodBatch.cls
global class MonitoringPeriodBatch implements Database.Batchable<sObject> {
  private String query;
    
  /*
  Execute Apex Jobs / Check on Setup => Environments => Jobs => Apex Jobs or Scheduled Jobs
  for(integer i = 0; i < 60; i++) {
    String sch = '0 ' + i + ' * * * ?';
    System.debug('i:' + i);
    ScheduledMonitoringPeriodBatch sqrb = new ScheduledMonitoringPeriodBatch();
    system.schedule('Every Hour plus ' + i + ' min', sch, sqrb);
    i = i + 4;
  }
  
  global MonitoringPeriodBatch (String soql){
    query = soql;
  }*/
    
  global MonitoringPeriodBatch (){
  }
    
  // The batch job starts
  global Database.Querylocator start(Database.BatchableContext bc){
    // String query = 'SELECT Id FROM ampi__project__c WHERE RecordType.Name IN (\'' + 'Standard' + '\', \'' + 'Grant' + '\', \'' + 'Transition' + '\', \'' + 'Humanitarian' + '\') AND IsActive__c = true AND ID NOT IN (SELECT ampi__project__c FROM ampi__reporting_period__c where ampi__Report_Type__c = \'' + 'Monthly' + '\' AND CALENDAR_YEAR(ampi__Reporting_Period_Start_Date__c) = 2023) LIMIT 20';
    // String query = 'SELECT Id FROM ampi__project__c WHERE RecordType.Name IN (\'' + 'Standard' + '\', \'' + 'Grant' + '\', \'' + 'Humanitarian' + '\') AND IsActive__c = true AND ampi__Project_status__c NOT IN (\'' + 'Project Closed' + '\',\'' + 'Cancelled'+ '\',\'' + 'Concept Rejected' + '\',\'' + 'Application Rejected' + '\') AND ID NOT IN (SELECT ampi__project__c FROM ampi__reporting_period__c where ampi__Report_Type__c = \'' + 'Monthly' + '\' AND CALENDAR_YEAR(ampi__Reporting_Period_Start_Date__c) = 2023) LIMIT 20';
    // String query = 'SELECT Id FROM ampi__project__c WHERE RecordType.Name IN (\'' + 'Shadow Project' + '\') AND IsActive__c = true AND ampi__Project_status__c NOT IN (\'' + 'Project Closed' + '\',\'' + 'Cancelled'+ '\',\'' + 'Concept Rejected' + '\',\'' + 'Application Rejected' + '\') AND ID NOT IN (SELECT ampi__project__c FROM ampi__reporting_period__c where ampi__Report_Type__c = \'' + 'Monthly' + '\' AND CALENDAR_YEAR(ampi__Reporting_Period_Start_Date__c) = 2023) AND Name LIKE \'National Office%\' LIMIT 20';     
    String query = 'SELECT Id FROM ampi__project__c WHERE RecordType.Name IN (\'' + 'Transition' + '\') AND IsActive__c = true AND ampi__Project_status__c NOT IN (\'' + 'Project Closed' + '\',\'' + 'Cancelled'+ '\',\'' + 'Concept Rejected' + '\',\'' + 'Application Rejected' + '\') AND ID NOT IN (SELECT ampi__project__c FROM ampi__reporting_period__c where ampi__Report_Type__c = \'' + 'Monthly' + '\' AND CALENDAR_YEAR(ampi__Reporting_Period_Start_Date__c) = 2023) LIMIT 20';     
    System.debug('>>>> start ' + query);
    return Database.getQuerylocator(query);
  } 
  
  // The batch job executes and operates on one batch of records
  global void execute(Database.BatchableContext bc, List<sObject> scope){
    System.debug('>>>> execute ' + scope.size());
	List<ampi__reporting_period__c> periods = new List<ampi__reporting_period__c>();

    for(sObject proj : scope) {
        for(Integer i = 1; i <= 12; i++) {
            ampi__reporting_period__c newPeriod = new ampi__reporting_period__c();
            newPeriod.ampi__Reporting_Period_Start_Date__c = Date.newInstance(2023, i, 1);
            newPeriod.ampi__Reporting_Period_End_Date__c = newPeriod.ampi__Reporting_Period_Start_Date__c.addMonths(1).addDays(-1);
            newPeriod.ampi__project__c = proj.Id;
            String month = (newPeriod.ampi__Reporting_Period_Start_Date__c.month() > 9 ? '' : '0') + newPeriod.ampi__Reporting_Period_Start_Date__c.month();
            newPeriod.ampi__label__c = newPeriod.ampi__Reporting_Period_Start_Date__c.year() + '-' + month;
            newPeriod.ampi__Report_Type__c = 'Monthly';
            periods.add(newPeriod);
        }
        System.debug('###proj.Id:' + proj.Id);
    }
    
    INSERT periods;    
  }
  
  // The batch job finishes
  global void finish(Database.BatchableContext bc){
    AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :bc.getJobId()]; 
    System.debug('>>>> finish ' + job.Status);
  }
}