force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/SharePoint_Team_Site_URL__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Team_Site_URL__c</fullName>
    <label>SharePoint Team Site URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/Project_TestHelper.cls
/****************************************************************************************
* Class: Project_TestHelper
* Created By: Ajinkya Hingne
----------------------------------------------------------------------------------------
* Description: Helper class.
----------------------------------------------------------------------------------------
* Version History:
* VERSION     DEVELOPER NAME       DATE            DETAIL FEATURES
https://vera.my.salesforce.com/
  1.0         Ajinkya Hingne       24/10/2019      Initial Development
***************************************************************************************/
@isTest
public with sharing class Project_TestHelper {

    public static List<ampi__Project__c> insertProjectRecords(List<ampi__Project__c> projects) {
        insert projects;
        return projects;
    }

    public static List<ampi__Project__c> getProjectRecords() {
        return [
            SELECT
                Id,
                SharePoint_Team_Site_URL__c
            FROM
                ampi__Project__c
        ];
    }
}