force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project</description>
    <inlineHelpText>Add description of your project (1024 char max), describe specific objectives. Include key words to ease the search (e.g. country, donor). The description can be changed and updated at any time and is shown on the Team Site.</inlineHelpText>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Project_TestFactory.cls
/****************************************************************************************
* Class: Project_TestFactory
* Created By: Ajinkya Hingne
----------------------------------------------------------------------------------------
* Description: Class to create test data for Project object
----------------------------------------------------------------------------------------
* Version History:
* VERSION     DEVELOPER NAME       DATE            DETAIL FEATURES
https://vera.my.salesforce.com/
  1.0         Ajinkya Hingne       04/11/2019      Initial Development
***************************************************************************************/
@isTest
public with sharing class Project_TestFactory {

    public static List<ampi__Project__c> createProjectRecords(Integer count) {
        List<ampi__Project__c> projects = new List<ampi__Project__c>();
        for (Integer i = 1; i <= count; i++) {
            projects.add(
                new ampi__Project__c(
                    Name = 'Test Project ' + i,
                    ampi__Description__c = 'Test Description' + i
                )
            );
        }
        return projects;
    }
}