force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/SOS_Implementing_Organisation__c.field-meta.xml
<CustomField>
    <fullName>SOS_Implementing_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Mandatory field for status &quot;in identification&quot;.
Indicate which SOS organisation will implement the project. For Umbrella projects, select &quot;Global-multiple MAs&quot; and register sub-projects for each implementating organisation in a separate step.</inlineHelpText>
    <label>SOS Implementing Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only an SOS Organisation can be an Implementing Organisation.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SOS Organisation - MA</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation - GSC Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funds (SOS Implementing Organisation)</relationshipLabel>
    <relationshipName>Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <description>Defined by contract with institutional donor, major corporate or foundation following PCM/RBM. Funded by int. or local funds. Can take place at programme, national or multi-country level. If in response to a humanitarian crisis, indicate in project setup.</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Geographic_Area__c</fullName>
    <description>Master-detail to specify parent geographic area</description>
    <label>Geographic Area</label>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Project Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Geographic_Area__c</fullName>
    <description>[NOT IN USE - Candidate for Deprecation]</description>
    <label>Project Geographic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/createPGACountry_GrantProject.cls
public class createPGACountry_GrantProject {

    @InvocableMethod(label='Create PGA Country for Grant Projects') 
	public Static void createPGACountry_GrantProject(List<Id> projectIds){
        
        List<ampi__Project__c> projects = [SELECT SOS_Implementing_Organisation__r.Country__c, RecordType.Name FROM ampi__Project__c WHERE Id IN: (projectIds)];

        if (projects.size() == 0) {
            return;
        }
        
        String countryId = projects[0].SOS_Implementing_Organisation__r.Country__c;
        System.debug('####createPGACountry_GrantProject Country A:' + countryId);
        
        if ((countryId != null && projects[0].RecordType.Name == 'Grant')) {
            List<ampi__Project_Geographic_Area__c> pgas = [SELECT Id FROM ampi__Project_Geographic_Area__c WHERE ampi__Project__c IN :projectIds AND ampi__Geographic_Area__c =: countryId];
            String projectId = projectIds[0];
    		
            System.debug('####createPGACountry_GrantProject pgas B:' + pgas.size());
        
            System.debug('####Schema.sObjectType.ampi__Project_Geographic_Area__c.isCreateable():' + Schema.sObjectType.ampi__Project_Geographic_Area__c.isCreateable());
            System.debug('####Schema.sObjectType.ampi__Project_Geographic_Area__c.isUpdateable():' + Schema.sObjectType.ampi__Project_Geographic_Area__c.isUpdateable());
            if (pgas.size() == 0 && Schema.sObjectType.ampi__Project_Geographic_Area__c.isCreateable() && Schema.sObjectType.ampi__Project_Geographic_Area__c.isUpdateable()) {
                ampi__Project_Geographic_Area__c newPGA = new ampi__Project_Geographic_Area__c();
                System.debug('####Schema.sObjectType.ampi__Project_Geographic_Area__c.isCreateable() 1');
                newPGA.ampi__Geographic_Area__c = projects[0].SOS_Implementing_Organisation__r.Country__c;
                System.debug('####Schema.sObjectType.ampi__Project_Geographic_Area__c.isCreateable() 2');
                newPGA.ampi__Project__c = projectId;
                newPGA.ampi__Geolocation__latitude__s = 0;
                newPGA.ampi__Geolocation__longitude__s = 0;
                insert newPGA;
                System.debug('####Schema.sObjectType.ampi__Project_Geographic_Area__c.isCreateable() 3');
        
                System.debug('####createPGACountry_GrantProject newPGA C:' + newPGA.Id);
        	}
        }
    }
}