force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/Programme_Location__c.field-meta.xml
<CustomField>
    <fullName>Programme_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the programme location for your project.</inlineHelpText>
    <label>Programme Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Programme for this field, not a Programme Unit, Country or Region.</errorMessage>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Projects in this Programme Location</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Active__c.field-meta.xml
<CustomField>
    <fullName>ampi__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to indicate if this project geographic area is active</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Geographic_Area__c</fullName>
    <description>Master-detail to specify parent geographic area</description>
    <label>Geographic Area</label>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Project Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Geographic_Area__c</fullName>
    <description>[NOT IN USE - Candidate for Deprecation]</description>
    <label>Project Geographic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/createPGAProgramme.cls
public class createPGAProgramme {
    @InvocableMethod(label='Create PGA Programme') 
	public Static void createPGAProgramme(List<Id> projectIds){
        List<ampi__Project__c> projects = [SELECT Id, Programme_Location__c FROM ampi__Project__c WHERE Id IN: (projectIds)];

        if (Schema.sObjectType.ampi__Project_Geographic_Area__c.isCreateable() && Schema.sObjectType.ampi__Project_Geographic_Area__c.isUpdateable() && projects.size() > 0 && projects[0].Programme_Location__c != null) {
            String programmeId = projects[0].Programme_Location__c;
        	System.debug('####createPGAProgramme Location:' + programmeId);
        
            List<ampi__Project_Geographic_Area__c> pgas = [SELECT Id, ampi__Active__c FROM ampi__Project_Geographic_Area__c WHERE ampi__Project__c IN :projectIds AND ampi__Geographic_Area__c =: programmeId];
            List<ampi__Project_Geographic_Area__c> newPGAs = new List<ampi__Project_Geographic_Area__c>();
            String projectId = projectIds[0];
    		
            System.debug('####createPGAProgramme pgas B:' + pgas.size());
            
            if (pgas.size() == 0) {
            	ampi__Project_Geographic_Area__c newPGA = new ampi__Project_Geographic_Area__c();
                newPGA.ampi__Geographic_Area__c = programmeId;
                newPGA.ampi__Project__c = projectId;
                newPGA.ampi__Geolocation__latitude__s = 0;
                newPGA.ampi__Geolocation__longitude__s = 0;
                INSERT newPGA;                
            }
            
            for (ampi__Project_Geographic_Area__c pga : pgas) {
                 if (pgas[0].ampi__Active__c ==  false) {
                    pga.ampi__Active__c = true;                    
                    UPDATE pga;
                }
            }
        }
    }
}