force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project</description>
    <inlineHelpText>Add description of your project (1024 char max), describe specific objectives. Include key words to ease the search (e.g. country, donor). The description can be changed and updated at any time and is shown on the Team Site.</inlineHelpText>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Create_Workspace_Callout_Time__c.field-meta.xml
<CustomField>
    <fullName>Create_Workspace_Callout_Time__c</fullName>
    <label>Create Workspace Callout Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Project_ID_raw__c.field-meta.xml
<CustomField>
    <fullName>Project_ID_raw__c</fullName>
    <description>Raw string version of Project_ID__c, used for SharePoint integration.</description>
    <formula>CASE(RecordType.Name,
&quot;Standard&quot;, &quot;S&quot;,
&quot;Emergency Response&quot;, &quot;E&quot;,
&quot;Funding Opportunity&quot;, &quot;F&quot;,
&quot;Humanitarian Appeal&quot;, &quot;H&quot;,
&quot;Grant&quot;, &quot;G&quot;,
&quot;Legacy&quot;, &quot;L&quot;,
&quot;Transition&quot;, &quot;T&quot;,
&quot;End of Involvement&quot;, &quot;X&quot;,
&quot;&quot;)
&amp; IF(DATEVALUE(CreatedDate) &gt; DATEVALUE(&quot;2019-12-31&quot;),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2),
IF(RecordType.Name = &quot;Grant&quot;,
RIGHT(TEXT(YEAR(Start_Identification__c)), 2),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2)
)
)
&amp; &quot;-&quot;
&amp; Project_Autonumber__c</formula>
    <inlineHelpText>Raw string version of Project_ID__c, used for SharePoint integration.</inlineHelpText>
    <label>Funding Opportunity ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/SOS_Implementing_Organisation__c.field-meta.xml
<CustomField>
    <fullName>SOS_Implementing_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Mandatory field for status &quot;in identification&quot;.
Indicate which SOS organisation will implement the project. For Umbrella projects, select &quot;Global-multiple MAs&quot; and register sub-projects for each implementating organisation in a separate step.</inlineHelpText>
    <label>SOS Implementing Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only an SOS Organisation can be an Implementing Organisation.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SOS Organisation - MA</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation - GSC Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funds (SOS Implementing Organisation)</relationshipLabel>
    <relationshipName>Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/SOS_Region__c.field-meta.xml
<CustomField>
    <fullName>SOS_Region__c</fullName>
    <description>Displays the SOS Region based on the SOS Applicant/Accountable Organisation</description>
    <formula>SOS_Implementing_Organisation__r.Country__r.ampi__Parent_Geographical_Area__r.Name</formula>
    <inlineHelpText>Shows  SOS Region where your project will be implemented.
This data field is filled automatically by the system based on the information entered in SOS Implementing Organisation.</inlineHelpText>
    <label>SOS Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateWorkspace_Ctrl.cls
/****************************************************************************************
* Class: CreateWorkspace_Ctrl
* Created By: Ajinkya Hingne
----------------------------------------------------------------------------------------
* Description: Class to perform server side actions of CreateWorkspace component
----------------------------------------------------------------------------------------
* Version History:
* VERSION     DEVELOPER NAME       DATE            DETAIL FEATURES
https://vera.my.salesforce.com/a041O00000e6qhH
  1.0         Ajinkya Hingne       04/11/2019      Initial Development
***************************************************************************************/
public with sharing class CreateWorkspace_Ctrl {

    @AuraEnabled
    public static Response createWorkspaceForProject(Id projectId) {
        ampi__Project__c project = Project_Domain.getProjectDetails(projectId);
        Response response = new Response();
        if (project.Create_Workspace_Callout_Time__c == null) {
            AuthResponse authResponse = authorizeToSharepoint();
            HttpResponse httpResponse;
            if (authResponse == null || authResponse.access_token == null) {
                // Return an error
                response.message = System.Label.CREATE_WORKSPACE_REQUEST_ERROR_MESSAGE;
                response.isSuccess = false;
            }
            else {
                httpResponse = callCreateWorkspaceAPI(project, authResponse.access_token);
                // Return error or success message
                if (httpResponse.getStatusCode() == 202) {
                    response.message = System.Label.CREATE_WORKSPACE_REQUEST_SUCCESS_MESSAGE;
                    response.isSuccess = true;
                    updateProjectCalloutTime(projectId);
                }
                else {
                    response.message = httpResponse.getStatusCode() + ' ' + httpResponse.getBody();
                    response.isSuccess = false;
                }
            }
        }
        else {
            response.message = System.Label.SHAREPOINT_INTEGRATION_ERROR_MESSAGE;
            response.isSuccess = false;
        }
        return response;
    }

    private static Void updateProjectCalloutTime(Id projectId) {
        ampi__Project__c project = new ampi__Project__c(
            Id = projectId,
            Create_Workspace_Callout_Time__c = System.now()
        );
        Project_Domain.updateProjects(new List<ampi__Project__c>{project});
    }

    private static AuthResponse authorizeToSharepoint() {
        List<Credential__c> credentials = Credential_Domain.getCredential('Sharepoint');

        if (!credentials.isEmpty()) {
            String requestBody = 'grant_type=' + credentials[0].Grant_Type__c +
                '&client_id=' + credentials[0].Client_Id__c +
                '&client_secret=' + credentials[0].Client_Secret__c +
                '&resource=' + credentials[0].Resource__c;

            HttpResponse httpResponse = doCallout(
                System.Label.ACCESS_TOKEN_AUTHORIZATION_URL,
                null,
                requestBody,
                'POST'
            );
            AuthResponse authResponse =
                (AuthResponse)JSON.deserialize(httpResponse.getbody(), AuthResponse.class);
            authResponse.calloutResponse = httpResponse;
            return authResponse;
        }
        return null;
    }

    private static HttpResponse callCreateWorkspaceAPI(
            ampi__Project__c project,
            String accessToken
    ) {
        String projectMembers = '';
        for(Team_Member__c member : project.Team_Members__r) {
            projectMembers += member.User__r.Username + ',';
        }
        projectMembers = projectMembers.removeEnd(',');
        String requestBody =  JSON.serialize(
            new ProjectData(
                project.Project_ID_raw__c,
                project.Name,
                project.ampi__Description__c == null ? '' : project.ampi__Description__c,
                project.Id,
                project.Owner.Username,
                project.ampi__Project_Status__c,
                projectMembers,
                project.SOS_Region__c,
                project.SOS_Implementing_Organisation__r.Name
            )
        );
        Map<String, String> headers = new Map<String, String> {
            'Content-Type' => System.Label.TYPE_APPLICATION_JSON,
            'Origin' => System.Label.SOS_HEADER_ORIGIN_URL,
            'Authorization' => 'Bearer ' + accessToken
        };
        HttpResponse httpResponse = doCallout(
            System.Label.SOS_INTEGRATION_API_URL,
            headers,
            requestBody,
            'POST'
        );
        return httpResponse;
    }

    private static HttpResponse doCallout(
            String endpoint,
            Map<String, String> headers,
            String requestBody,
            String method
    ) {
        HttpRequest request = new HttpRequest();
        request.setEndPoint(endpoint);
        request.setMethod(method);
        request.setBody(requestBody);
        if (headers != null) {
            for (String headerKey : headers.keySet()) {
                request.setHeader(headerKey, headers.get(headerKey));
            }
        }
        Http httpConnection = new Http();
        return httpConnection.send(request);
    }

    /**
     * Wrapper classes
     */
    public class AuthResponse {
        public String access_token;
        public HttpResponse calloutResponse;
    }
    public class Response {
        @AuraEnabled public String message;
        @AuraEnabled public boolean isSuccess;
    }

    public class ProjectData {
        String projectId;
        String projectName;
        String projectDescription;
        String projectUrl;
        String owner;
        String projectStatus;
        String projectMembers;
        String sosRegion;
        String sosImplementingPartner;

        public ProjectData(
            String projectId,
            String projectName,
            String projectDescription,
            Id recordId,
            String owner,
            String projectStatus,
            String projectMembers,
            String sosRegion,
            String sosImplementingPartner
        ) {
            this.projectId = projectId;
            this.projectName = projectName;
            this.projectDescription = projectDescription;
            this.projectUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/' + recordId;
            this.owner = owner;
            this.projectStatus = projectStatus;
            this.projectMembers = projectMembers;
            this.sosRegion = sosRegion;
            this.sosImplementingPartner = sosImplementingPartner;
        }
    }
}