force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project</description>
    <inlineHelpText>Add description of your project (1024 char max), describe specific objectives. Include key words to ease the search (e.g. country, donor). The description can be changed and updated at any time and is shown on the Team Site.</inlineHelpText>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/IOR_Approver__c.field-meta.xml
<CustomField>
    <fullName>IOR_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IOR Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IOR_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identification</fullName>
                <default>true</default>
                <label>Identification</label>
            </value>
            <value>
                <fullName>Formulation</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Closure</fullName>
            </value>
            <value>
                <fullName>In Setup</fullName>
            </value>
            <value>
                <fullName>In Tendering</fullName>
            </value>
            <value>
                <fullName>In Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Project_ID_Text__c.field-meta.xml
<CustomField>
    <fullName>Project_ID_Text__c</fullName>
    <formula>CASE(RecordType.Name,
&quot;Standard&quot;, &quot;S&quot;,
&quot;Emergency Response&quot;, &quot;E&quot;,
&quot;Funding Opportunity&quot;, &quot;F&quot;,
&quot;Humanitarian&quot;, &quot;H&quot;,
&quot;Grant&quot;, &quot;G&quot;,
&quot;Legacy&quot;, &quot;L&quot;,
&quot;End of Involvement&quot;, &quot;X&quot;,
&quot;Construction&quot;, &quot;C&quot;,
&quot;&quot;)
&amp; IF(DATEVALUE(CreatedDate) &gt; DATEVALUE(&quot;2019-12-31&quot;),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2),
IF(RecordType.Name = &quot;Grant&quot;,
RIGHT(TEXT(YEAR(Start_Identification__c)), 2),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2)
)
)
&amp; &quot;-&quot;
&amp; Project_Autonumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Project ID is generated by the system..</inlineHelpText>
    <label>Project ID Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/PSA_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>PSA_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSA Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PSA_Reviewer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/SharePoint_Team_Site_URL__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_Team_Site_URL__c</fullName>
    <label>SharePoint Team Site URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Deliverable__c/Deliverable__c.object-meta.xml
<CustomObject>
    <label>Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deliverable__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <description>Project phase to which the deliverable is related. Pre-filled for standard deliverables.</description>
    <inlineHelpText>Project phase to which the deliverable is related. Pre-filled for standard deliverables.</inlineHelpText>
    <label>Project Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identification</fullName>
            </value>
            <value>
                <fullName>Formulation</fullName>
            </value>
            <value>
                <fullName>Implemention</fullName>
            </value>
            <value>
                <fullName>Closure</fullName>
            </value>
            <value>
                <fullName>Set up</fullName>
                <isActive>false</isActive>
                <label>Set up</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deliverable__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Project ID to which the deliverable is related. Filled by the system.</inlineHelpText>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Deliverables</relationshipLabel>
    <relationshipName>Deliverables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deliverable__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Set to done once the deliverable is available and passed applicable validation cycle. Add link to the Sharepoint where the deliverable is stored.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Done</fullName>
                <default>true</default>
                <label>Not Done</label>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Agreement in progress</fullName>
            </value>
            <value>
                <fullName>In development</fullName>
            </value>
            <value>
                <fullName>Agreement signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deliverable__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Choose what is the most suitable. For standard deliverables this filed is pre-filled.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Evaluation</fullName>
            </value>
            <value>
                <fullName>Plan</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
            </value>
            <value>
                <fullName>Decision</fullName>
            </value>
            <value>
                <fullName>Form</fullName>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Validation</fullName>
            </value>
            <value>
                <fullName>Concept note</fullName>
            </value>
            <value>
                <fullName>Framework</fullName>
            </value>
            <value>
                <fullName>Checklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deliverable__c/recordTypes/Agreement.recordType-meta.xml
<RecordType>
    <fullName>Agreement</fullName>
    <active>true</active>
    <label>Agreement</label>
</RecordType>

force-app/main/default/classes/notificationForPSAandIOR.cls
public class notificationForPSAandIOR {
        @InvocableMethod(label='Notification For PSA and IOR') 
        public Static void notificationForPSAandIOR_ForStandardProject(List<FlowInputs> request) {
            //Approval process topic: https://salesforce.stackexchange.com/questions/1298/how-to-check-if-a-record-is-locked-or-not-in-apex-during-an-approval-process
            //Email Messaging: https://developer.salesforce.com/forums/?id=9060G000000I8UNQA0
            System.debug('###notificationForPSAandIOR request[0].projectId: ' + request[0].projectId);
            System.debug('###notificationForPSAandIOR Approval.isLocked(request[0].projectId): ' + Approval.isLocked(request[0].projectId));
            // if (Approval.isLocked(request[0].projectId) || Test.isRunningTest()) {
                //Please replace "Your Email Template Unique Name" with your template name
                String emailTemplateName = request[0].emailTemplate;
                List<EmailTemplate> lstEmailTemplates = [SELECT Id, HtmlValue, Body, Subject from EmailTemplate where DeveloperName =: emailTemplateName];
                System.debug('###notificationForPSAandIOR emailTemplateName: ' + emailTemplateName);
                System.debug('###notificationForPSAandIOR lstEmailTemplates: ' + lstEmailTemplates);
                System.debug('###notificationForPSAandIOR lstEmailTemplates.size(): ' + lstEmailTemplates.size());
            
                List<ampi__project__c> currentProjectInfo = [SELECT Project_ID_Text__c, Name, ampi__Description__c, Phase__c, ampi__Project_Status__c, SharePoint_Team_Site_URL__c, IOR_Approver__r.Name, IOR_Approver__c, IOR_Approver__r.Email, PSA_Reviewer__r.Name, PSA_Reviewer__c, PSA_Reviewer__r.Email FROM ampi__project__c WHERE Id =: request[0].projectId AND RecordType.Name = 'Standard'];
                // List<agreement__c> currentProjectAgreement = [SELECT Id, Status__c FROM agreement__c WHERE project__c =: request[0].projectId];
                List<deliverable__c> currentProjectAgreement = [SELECT Id, Status__c FROM deliverable__c WHERE project__c =: request[0].projectId AND Type__c = 'Agreement' AND Name LIKE 'Partnership agreement%'];
                System.debug('###notificationForPSAandIOR currentProjectInfo: ' + currentProjectInfo);
            
                if (currentProjectInfo.size() > 0 && lstEmailTemplates.size() > 0 && currentProjectAgreement.size() > 0) {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setTemplateId(lstEmailTemplates[0].Id);
                    mail.setSaveAsActivity(false);
                    mail.setTargetObjectId(userinfo.getUserId());// Any contact or User id of your record

                    List<String> receivers = new List<String>();
                    Set<String> receiverIds = new Set<String>();
                    
                    String checkers = '';
                    if (currentProjectInfo[0].PSA_Reviewer__r.Email <> null && currentProjectInfo[0].PSA_Reviewer__r.Email <> '') {
                        checkers = 'PSA Reviewer: ' + currentProjectInfo[0].PSA_Reviewer__r.Name + ' / ';
                        receivers.add(currentProjectInfo[0].PSA_Reviewer__r.Email);
                        receiverIds.add(currentProjectInfo[0].PSA_Reviewer__c);
                    }
                    if (currentProjectInfo[0].IOR_Approver__r.Email <> null && currentProjectInfo[0].IOR_Approver__r.Email <> '') {
                        checkers += 'IOR Approver: ' + currentProjectInfo[0].IOR_Approver__r.Name;
                        receivers.add(currentProjectInfo[0].IOR_Approver__r.Email);
                        receiverIds.add(currentProjectInfo[0].IOR_Approver__c);
                    }
                    
                    System.debug('###notificationForPSAandIOR receivers: ' + receivers);
                    
                    String plainBody = lstEmailTemplates[0].Body;
                    plainBody = plainBody.replace('{!ampi__Project__c.Project_ID_Text__c}', ' ' + currentProjectInfo[0].Project_ID_Text__c);
                    plainBody = plainBody.replace('{!ampi__Project__c.Name}', ' ' + currentProjectInfo[0].Name);
                    plainBody = plainBody.replace('{!ampi__Project__c.ampi__Description__c}', currentProjectInfo[0].ampi__Description__c == null ? ' No Info Available' : ' ' + currentProjectInfo[0].ampi__Description__c);
                    plainBody = plainBody.replace('{!ampi__Project__c.Phase__c}', ' ' + currentProjectInfo[0].Phase__c);
                    plainBody = plainBody.replace('{!ampi__Project__c.ampi__Project_Status__c}', ' ' + currentProjectInfo[0].ampi__Project_Status__c);
                    plainBody = plainBody.replace('{!ampi__Project__c.Link}', currentProjectInfo[0].SharePoint_Team_Site_URL__c == null ? ' No Info Available' : ' ' + currentProjectInfo[0].SharePoint_Team_Site_URL__c);
                    plainBody = plainBody.replace('{!ApprovalRequest.Process_Assignee}', ' Agreement is changed to status: "' + currentProjectAgreement[0].Status__c + '" ' + checkers);
                    mail.setToAddresses(receivers);
                    mail.setPlainTextBody(plainBody);

                    //https://stackoverflow.com/questions/11105086/setwhatid-in-salesforce-using-email-template
                    // mail.setWhatId(request[0].projectId); // Enter your record Id whose merge field you want to add in template
                    // set data to email template:
                    // Project Id:
                    // Project Name:
                    // Project Description:
                    // Phase:
                    // Project Status:
                    System.debug('###notificationForPSAandIOR mail: ' + mail);
                    Messaging.SendEmailResult[] resultMail = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                    
                    String title = 'Please Check New Agreement On Standard Project';
                    String message = 'New agreement was created for a Standard Project. The record is ready for your review. Project Name: ' + currentProjectInfo[0].Name;

                    notifyUsers(receiverIds, request[0].projectId, title, message);
                    System.debug('###notificationForPSAandIOR resultMail: ' + resultMail);
                }
            // }
        }

        public static void notifyUsers(Set<String> recipientsIds, String targetId, String title, String message) {
            // Get the Id for our custom notification type
            CustomNotificationType notificationType = 
                [SELECT Id, DeveloperName 
                FROM CustomNotificationType 
                WHERE DeveloperName='notification_PSA_IOR' LIMIT 1];
            
            // Create a new custom notification
            Messaging.CustomNotification notification = new Messaging.CustomNotification();

            // Set the contents for the notification
            notification.setTitle(title);
            notification.setBody(message);

            // Set the notification type and target
            notification.setNotificationTypeId(notificationType.Id);
            notification.setTargetId(targetId);
            
            // Actually send the notification
            try {
                notification.send(recipientsIds);
            }
            catch (Exception e) {
                System.debug('Problem sending notification: ' + e.getMessage());
            }
        }

        public class FlowInputs{    
            @InvocableVariable
            public Id projectId;
            @InvocableVariable
            public String emailTemplate = 'Standard_Project_Notify_For_New_Agreement';
        }
}