force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Active__c.field-meta.xml
<CustomField>
    <fullName>ampi__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to indicate if this project geographic area is active</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Geographic_Area__c</fullName>
    <description>Master-detail to specify parent geographic area</description>
    <label>Geographic Area</label>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Project Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Geographic_Area__c</fullName>
    <description>[NOT IN USE - Candidate for Deprecation]</description>
    <label>Project Geographic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/createPGA.cls
public class createPGA {
    @InvocableMethod(label='Create Programme PGA') 
	public Static void createProgramme_PGA(List<FlowInputs> request){
        List<ampi__project_geographic_area__c> checkDuplicates = [SELECT Id, ampi__Active__c FROM ampi__project_geographic_area__c WHERE ampi__Geographic_Area__c =: request[0].programmeId AND ampi__project__c =: request[0].projectId];
        Boolean foundInactiveDuplicates = false;
                
        if (checkDuplicates.size() > 0) {
            for (ampi__project_geographic_area__c pga : checkDuplicates) {
                if (pga.ampi__Active__c == false) {
                    pga.ampi__Active__c = true;
                    foundInactiveDuplicates = true;
                }
            }

            if (foundInactiveDuplicates){
                UPDATE checkDuplicates;
            }
        } else {
            ampi__project_geographic_area__c newPGA = new ampi__project_geographic_area__c();
            newPGA.ampi__Active__c = true;
            newPGA.ampi__Geographic_Area__c = request[0].programmeId;
            newPGA.ampi__project__c = request[0].projectId;
            newPGA.ampi__Geolocation__latitude__s = 0;
            newPGA.ampi__Geolocation__longitude__s = 0;
            INSERT newPGA;
        } 
    }

    public class FlowInputs{    
        @InvocableVariable
        public Id projectId;
        @InvocableVariable
        public Id programmeId;        
    }
}