force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Reporting_Period__c/ampi__Reporting_Period__c.object-meta.xml
<CustomObject>
    <description>A period of time for which a project&apos;s targets must be set and results reported</description>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Reporting Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Date_Submitted__c.field-meta.xml
<CustomField>
    <fullName>ampi__Date_Submitted__c</fullName>
    <description>Date field to specify when results were submitted for this reporting period. This field needs to be manually updated, system admins can set up custom automation to populate the field on custom criteria.</description>
    <label>Date Submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Project to which a Reporting Period belongs</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Reporting Periods</relationshipLabel>
    <relationshipName>Project_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Reporting_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Period_End_Date__c</fullName>
    <description>Date field to store the end date for this reporting period. This field determines the primary order in which Reporting Periods are displayed in the dropdown picklist on SetTargets and AddResults.</description>
    <label>Reporting Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Reporting_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Period_Start_Date__c</fullName>
    <description>Date field to store the start date for this reporting period. This field determines the secondary order in which Reporting Periods are displayed in the dropdown picklist on SetTargets and AddResults.</description>
    <label>Reporting Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Result_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Result_Status__c</fullName>
    <description>This picklist field is to specify the status of results for this reporting period. If set to &quot;Submitted&quot;, then the AddResults page is locked from editing for this Reporting Period.</description>
    <label>Result Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <label>Scheduled / In Progress</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Results_Locked__c.field-meta.xml
<CustomField>
    <fullName>ampi__Results_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox field to indicate if adding results are locked for this reporting period. If marked as TRUE, then the AddResults page is locked from editing for this Reporting Period.</description>
    <label>Results Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubmitPendingMonitoringPeriodBatch.cls
global class SubmitPendingMonitoringPeriodBatch implements Database.Batchable<sObject>{
	private String query;
    public Integer numberOfRecords;
    
  /*
  Execute Apex Jobs / Check on Setup => Environments => Jobs => Apex Jobs or Scheduled Jobs
  //String sch = '0 1 * * * ?';
Integer day = 44;
Integer hour = 14;
Integer month = 39;
Integer count = 1;
String sch = '0 ' + month + ' ' + hour + ' ' + day + ' * * ';   // 8:30am every 1st day of the month

for(Integer i=month; i<60; i++) {
    ScheduledSubmitPendingMonitoringPeriod sqrb = new ScheduledSubmitPendingMonitoringPeriod();
    sqrb.numberOfRecords = 1000;
    system.schedule('ScheduledSubmitPendingMonitoringPeriod Day:' + day + ' hour:' + hour + ' month:' + i + ' v:' + count, sch, sqrb);
    count++;
}
*/
    
  global SubmitPendingMonitoringPeriodBatch(Integer records){
      this.numberOfRecords = records;
  }
    
  // The batch job starts
  global Database.Querylocator start(Database.BatchableContext bc){
    String query = 'SELECT Id, ampi__Result_Status__c, ampi__Results_Locked__c FROM ampi__Reporting_Period__c WHERE (CALENDAR_YEAR(ampi__Reporting_Period_Start_Date__c) = 2022 OR CALENDAR_YEAR(ampi__Reporting_Period_End_Date__c) = 2022) AND ampi__Result_Status__c <> \'Submitted\' AND ampi__Project__r.RecordType.Name = \'Shadow Project\' LIMIT ' + this.numberOfRecords;
    System.debug('####query:' + query);
    return Database.getQuerylocator(query);
  } 
  
  // The batch job executes and operates on one batch of records
  global void execute(Database.BatchableContext bc, List<sObject> scope){            
    List<ampi__Reporting_Period__c> mpsToUpdate = new List<ampi__Reporting_Period__c>();
    for(sObject mp : scope) {
        ampi__Reporting_Period__c toUpdate = (ampi__Reporting_Period__c)mp;      
        toUpdate.ampi__Result_Status__c = 'Submitted';
        toUpdate.ampi__Results_Locked__c = true;
        toUpdate.ampi__Date_Submitted__c = date.today();
        mpsToUpdate.add(toUpdate);
    }
      
    Try {  
    	UPDATE mpsToUpdate;
        System.debug('###mpsToUpdate records were removed: ' + mpsToUpdate.size());
    } catch(Exception ex) {
        System.debug('###mpsToUpdate exception: ' + ex.getMessage());
    }
  }
  
  // The batch job finishes
  global void finish(Database.BatchableContext bc){
    AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :bc.getJobId()]; 
    System.debug('>>>> finish ' + job.Status);
  }
}