force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/SOS_Implementing_Organisation__c.field-meta.xml
<CustomField>
    <fullName>SOS_Implementing_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Mandatory field for status &quot;in identification&quot;.
Indicate which SOS organisation will implement the project. For Umbrella projects, select &quot;Global-multiple MAs&quot; and register sub-projects for each implementating organisation in a separate step.</inlineHelpText>
    <label>SOS Implementing Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only an SOS Organisation can be an Implementing Organisation.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SOS Organisation - MA</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation - GSC Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funds (SOS Implementing Organisation)</relationshipLabel>
    <relationshipName>Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/ampi__Project_Indicator__c.object-meta.xml
<CustomObject>
    <description>Junction linking a catalog indicator to a project</description>
    <label>Project Indicator</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Project Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Project this project indicator belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Project_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Result__c/ampi__Result__c.object-meta.xml
<CustomObject>
    <description>Target and result values for a specific reporting period, project area, project indicator, and disaggregation value</description>
    <label>Result</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Result ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Result__c/fields/ampi__Project_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator__c</fullName>
    <description>Describes the Indicator for which Results and Targets are captured</description>
    <label>Project Indicator</label>
    <referenceTo>ampi__Project_Indicator__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Project_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Project role that describes your involvement in the project, not necessary same as your job title.</description>
    <inlineHelpText>Choose the role that describes best your involvement in the project. Can be different than your job title.</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Construction Coordinator</fullName>
            </value>
            <value>
                <fullName>CVI Rep</fullName>
            </value>
            <value>
                <fullName>Financial controller</fullName>
            </value>
            <value>
                <fullName>GER Advisor</fullName>
            </value>
            <value>
                <fullName>IO IPD Coordinator</fullName>
            </value>
            <value>
                <fullName>IO PPC Coordinator</fullName>
            </value>
            <value>
                <fullName>IOR IPD Coordinator</fullName>
            </value>
            <value>
                <fullName>IOR PPC Coordinator</fullName>
            </value>
            <value>
                <fullName>MA IPD Coordinator</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PSA representative</fullName>
            </value>
            <value>
                <fullName>IO Financial Controller</fullName>
            </value>
            <value>
                <fullName>IOR Financial Controller</fullName>
            </value>
            <value>
                <fullName>MA Financial Controller</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>Project Contributor</fullName>
            </value>
            <value>
                <fullName>Global Project Manager</fullName>
            </value>
            <value>
                <fullName>Global MEL Advisor</fullName>
            </value>
            <value>
                <fullName>Regional Coordinator</fullName>
            </value>
            <value>
                <fullName>Sos Youth Can Coordinator</fullName>
            </value>
            <value>
                <fullName>Global Partner</fullName>
            </value>
            <value>
                <fullName>Local Partner</fullName>
            </value>
            <value>
                <fullName>Programme Planning Advisor</fullName>
            </value>
            <value>
                <fullName>Sustainable Construction Solution Project Manager</fullName>
            </value>
            <value>
                <fullName>YouthCan! Global MEL Advisor</fullName>
            </value>
            <value>
                <fullName>YouthCan! Global Project Manager</fullName>
            </value>
            <value>
                <fullName>YouthCan! Key Account Manager</fullName>
            </value>
            <value>
                <fullName>YouthCan! Regional Coordinator</fullName>
            </value>
            <value>
                <fullName>YouthCan! Coordinator</fullName>
            </value>
            <value>
                <fullName>YouthCan! Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ResultTriggerHandler.cls
public class ResultTriggerHandler {
    public void beforeInsertUpdateResultsInCommunityProfiles(List<ampi__Result__c> newResults) {
            User currentUser = [SELECT id,Contact.AccountId,Name,Profile.UserLicense.Name, Alias FROM User WHERE Id =:UserInfo.getUserId() LIMIT 1];
            String license = currentUser.Profile.UserLicense.Name;
            System.debug('####currentUser: ' + currentUser.Name);        
            System.debug('####license: ' + license);        

            List<string> roles = new List<string>();
            roles.add('YouthCan! Global MEL Advisor');
            roles.add('YouthCan! Global Project Manager');
            roles.add('YouthCan! Key Account Manager');
            roles.add('YouthCan! Regional Coordinator');
            roles.add('YouthCan! Coordinator');
            roles.add('YouthCan! Partner');
            roles.add('Project Contributor');

            If (license.toLowerCase().contains('community') || currentUser.Alias.toLowerCase().contains('xxzzzccc')) {
                List<ampi__Result__c> results = newResults;
                System.debug('####results: ' + results);
                for(ampi__Result__c res : results) {
                    List<ampi__project_indicator__c> pi = [SELECT id, ampi__project__c, ampi__project__r.RecordType.Name, ampi__project__r.SOS_Implementing_Organisation__c FROM ampi__project_indicator__c WHERE Id =: res.ampi__Project_Indicator__c];
                    
                    if (pi.size() > 0) {
                        System.debug('####pi[0].ampi__project__c: ' + pi[0].ampi__project__c);
                        System.debug('####currentUser.Id: ' + currentUser.Id);
                        System.debug('####roles: ' + roles);
                        System.debug('####pi[0].ampi__project__r.RecordType.Name: ' + pi[0].ampi__project__r.RecordType.Name);                        
                        if (pi[0].ampi__project__r.RecordType.Name == 'Shadow Project') {
                            if (currentUser.Contact.AccountId != pi[0].ampi__project__r.SOS_Implementing_Organisation__c) {
                                res.addError('INSUFFICIENT_ACCESS_OR_READONLY error for Contact "Organisation" field is different to the project "SOS Implemetation Organisation" field.');
                                // res.addError('INSUFFICIENT_ACCESS_OR_READONLY on "ampi__result__c" row Id:' + res.Id);                                
                            }
                        } else {
                            List<Team_member__c> tms = [SELECT Id FROM Team_member__c WHERE Project__c =: pi[0].ampi__project__c AND User__c =: currentUser.Id AND Role__c IN : roles AND Active__c = true];
                            System.debug('####tms.size(): ' + tms.size());        
                            if(tms.size() == 0) {
                                res.addError('INSUFFICIENT_ACCESS_OR_READONLY error for User is not registered as a "Team member" on the project as Project Contributor or Youthcan roles.');
                                // res.addError('INSUFFICIENT_ACCESS_OR_READONLY on "ampi__result__c" row Id:' + res.Id);
                            }
                        }                        
                    }                    
                }
            }   
    }
}