force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/IOR_Approver__c.field-meta.xml
<CustomField>
    <fullName>IOR_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IOR Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IOR_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/PSA_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>PSA_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PSA Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PSA_Reviewer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Project role that describes your involvement in the project, not necessary same as your job title.</description>
    <inlineHelpText>Choose the role that describes best your involvement in the project. Can be different than your job title.</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Construction Coordinator</fullName>
            </value>
            <value>
                <fullName>CVI Rep</fullName>
            </value>
            <value>
                <fullName>Financial controller</fullName>
            </value>
            <value>
                <fullName>GER Advisor</fullName>
            </value>
            <value>
                <fullName>IO IPD Coordinator</fullName>
            </value>
            <value>
                <fullName>IO PPC Coordinator</fullName>
            </value>
            <value>
                <fullName>IOR IPD Coordinator</fullName>
            </value>
            <value>
                <fullName>IOR PPC Coordinator</fullName>
            </value>
            <value>
                <fullName>MA IPD Coordinator</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PSA representative</fullName>
            </value>
            <value>
                <fullName>IO Financial Controller</fullName>
            </value>
            <value>
                <fullName>IOR Financial Controller</fullName>
            </value>
            <value>
                <fullName>MA Financial Controller</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>Project Contributor</fullName>
            </value>
            <value>
                <fullName>Global Project Manager</fullName>
            </value>
            <value>
                <fullName>Global MEL Advisor</fullName>
            </value>
            <value>
                <fullName>Regional Coordinator</fullName>
            </value>
            <value>
                <fullName>Sos Youth Can Coordinator</fullName>
            </value>
            <value>
                <fullName>Global Partner</fullName>
            </value>
            <value>
                <fullName>Local Partner</fullName>
            </value>
            <value>
                <fullName>Programme Planning Advisor</fullName>
            </value>
            <value>
                <fullName>Sustainable Construction Solution Project Manager</fullName>
            </value>
            <value>
                <fullName>YouthCan! Global MEL Advisor</fullName>
            </value>
            <value>
                <fullName>YouthCan! Global Project Manager</fullName>
            </value>
            <value>
                <fullName>YouthCan! Key Account Manager</fullName>
            </value>
            <value>
                <fullName>YouthCan! Regional Coordinator</fullName>
            </value>
            <value>
                <fullName>YouthCan! Coordinator</fullName>
            </value>
            <value>
                <fullName>YouthCan! Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TeamMemberTriggerHandler.cls
public class TeamMemberTriggerHandler {
    public void afterInsertSetIORApproverAndPSAReviewer(List<Team_Member__c> newTeamMembers) {
        if (newTeamMembers.size() == 0) {
            return;
        }
        
        String projectId = newTeamMembers[0].Project__c;
        List<ampi__Project__c> projectStandardRelatedToTeamMembers = [SELECT Id, PSA_Reviewer__c, IOR_Approver__c FROM ampi__Project__c WHERE Id =: projectId AND RecordType.Name = 'Standard'];
        
        // System.debug('####projectStandardRelatedToTeamMembers.size():' + projectStandardRelatedToTeamMembers.size());
        if (projectStandardRelatedToTeamMembers.size() == 0) 
            return;

        boolean changed = false;
        for(Team_Member__c tm : newTeamMembers) {            
            // System.debug('####tm.role__c:' + tm.role__c);
            switch on tm.role__c {
                when 'PSA Reviewer' {
                    projectStandardRelatedToTeamMembers[0].PSA_Reviewer__c = tm.User__c;   
                    // System.debug('####projectStandardRelatedToTeamMembers[0].PSA_Reviewer__c:' + projectStandardRelatedToTeamMembers[0].PSA_Reviewer__c);
                    changed = true;
                }
                when 'IOR Approver' {
                    projectStandardRelatedToTeamMembers[0].IOR_Approver__c = tm.User__c;       
                    // System.debug('####projectStandardRelatedToTeamMembers[0].IOR_Approver__c:' + projectStandardRelatedToTeamMembers[0].IOR_Approver__c);
                    changed = true;
                }
            }
            /*if(tm.role__c == 'PSA Reviewer') {
                projectStandardRelatedToTeamMembers[0].PSA_Reviewer__c = tm.UserId;   
            } else if(tm.role__c == 'IOR Approver') {
                projectStandardRelatedToTeamMembers[0].IOR_Approver__c = tm.UserId;                     
            }*/
        }

        if (changed) {
            UPDATE projectStandardRelatedToTeamMembers;
            System.debug('####projectStandardRelatedToTeamMembers:' + projectStandardRelatedToTeamMembers);
        }
    }
}