force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Reporting_Period__c/ampi__Reporting_Period__c.object-meta.xml
<CustomObject>
    <description>A period of time for which a project&apos;s targets must be set and results reported</description>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Reporting Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Label__c.field-meta.xml
<CustomField>
    <fullName>ampi__Label__c</fullName>
    <description>Text field to specify the human readable name of reporting period.</description>
    <inlineHelpText>Create a name for your reporting period that matches the duration of time that results are reported on. For example, for annual data, enter the “year name”. For quarterly data, enter “Q1 [year name]”.</inlineHelpText>
    <label>Reporting Period Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Project to which a Reporting Period belongs</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Reporting Periods</relationshipLabel>
    <relationshipName>Project_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Report_Type__c.field-meta.xml
<CustomField>
    <fullName>ampi__Report_Type__c</fullName>
    <description>Duration of time that results are reported on. This field determines what Project Indicator Reporting Period junction records are generated by the Reporting Period triggers.</description>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Life of Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MonitoringPeriodTriggerHandler.cls
public class MonitoringPeriodTriggerHandler {
    public void beforeInsertMonitoringPeriods(List<ampi__Reporting_Period__c> newReportingPeriod) {
        for(ampi__Reporting_Period__c rp : newReportingPeriod) {
            Integer matchReportingPeriods = [SELECT Count() FROM ampi__Reporting_Period__c 
                                                                		WHERE ampi__Project__c =: rp.ampi__Project__c AND
                                                                              ampi__Report_Type__c =: rp.ampi__Report_Type__c AND
                                                                              ampi__Label__c =: rp.ampi__Label__c];

            if (matchReportingPeriods > 0) {
                rp.addError('There is already a Monitoring Period with these specifications assigned to this Project. Please review and update where required.');
            }   
        }
    }

    public void beforeUpdateMonitoringPeriods(List<ampi__Reporting_Period__c> newReportingPeriod) {
        //System.debug('####newReportingPeriod:' + newReportingPeriod.size());
        for(ampi__Reporting_Period__c rp : newReportingPeriod) {
            /*System.debug('####newReportingPeriod.ampi__Project__c:' + rp.ampi__Project__c);
            System.debug('####newReportingPeriod.ampi__Report_Type__c:' + rp.ampi__Report_Type__c);
            System.debug('####newReportingPeriod.Id:' + rp.Id);
            System.debug('####newReportingPeriod.ampi__Label__c:' + rp.ampi__Label__c);*/
            Integer matchReportingPeriods = [SELECT Count() FROM ampi__Reporting_Period__c 
                                                                		WHERE ampi__Project__c =: rp.ampi__Project__c AND
                                                                              ampi__Report_Type__c =: rp.ampi__Report_Type__c AND
                                                                              Id !=: rp.Id AND
                                                                              ampi__Label__c =: rp.ampi__Label__c];
            System.debug('####matchReportingPeriods:' + matchReportingPeriods);
            if (matchReportingPeriods > 0) {
                rp.addError('There is already a Monitoring Period with these specifications assigned to this Project. Please review and update where required.');
            }   
        }
    }
}