force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/Account_Teams__c.field-meta.xml
<CustomField>
    <fullName>Account_Teams__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Organisation record which is populated here will be used as the basis for sharing this Project record with external users in the MA Portal. For Projects (Grants, Standard, Emergency) this should be the shadow Organisation record named like &quot;{Project ID} - External Project Team&quot;. For Programmes or NMUs, this should be the NA that they fall underneath.</description>
    <inlineHelpText>The Organisation record which is populated here will be used as the basis for sharing this Project record with external users in the MA Portal. For Projects (Grants, Standard, Emergency) this should be the shadow Organisation record named like &quot;{Project ID} - External Project Team&quot;. For Programmes or NMUs, this should be the NA that they fall underneath.</inlineHelpText>
    <label>External Project Team</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Account Team)</relationshipLabel>
    <relationshipName>Projects5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/SOS_Implementing_Organisation__c.field-meta.xml
<CustomField>
    <fullName>SOS_Implementing_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Mandatory field for status &quot;in identification&quot;.
Indicate which SOS organisation will implement the project. For Umbrella projects, select &quot;Global-multiple MAs&quot; and register sub-projects for each implementating organisation in a separate step.</inlineHelpText>
    <label>SOS Implementing Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only an SOS Organisation can be an Implementing Organisation.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SOS Organisation - MA</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation - GSC Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funds (SOS Implementing Organisation)</relationshipLabel>
    <relationshipName>Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/createTeamMemberProject.cls
public class createTeamMemberProject {
        //public Static void createTeammember_Project(List<Id> projectIds, List<Id> usersIds, String role, Boolean alternate){
        @InvocableMethod(label='Create Team members') 
        public Static void createTeammember_Project(List<FlowInputs> request) {
            // ampi__project__c project = [SELECT Id, Account_Teams__c, SOS_Implementing_Organisation__c FROM ampi__project__c WHERE Id =: request[0].projectId LIMIT 1];
            if (request[0].projectId == null || request[0].userId == null)
                return;
            
            ampi__project__c project = [SELECT Id, Account_Teams__c FROM ampi__project__c WHERE Id =: request[0].projectId LIMIT 1];            
            User user = [SELECT Id, ContactId, Contact.AccountId, FirstName, LastName, Phone, Profile.UserLicense.Name, Email   FROM user WHERE Id =: request[0].userId LIMIT 1];            
            String contactId = '';
            String accountId = '';
            System.debug('####CTMP user.Profile.UserLicense.Name:' + user.Profile.UserLicense.Name);
            // if (user <> null && !user.Profile.UserLicense.Name.contains('Community') && !Test.isRunningTest()) {
            if (user == null) {
                return;
            }
            
            if (project <> null) {
                 if(project.Account_Teams__c <> NULL && String.valueOf(project.Account_Teams__c) <> '') {
                     accountId = project.Account_Teams__c;
                //  } else if(project.Account_Teams__c <> NULL && String.valueOf(project.SOS_Implementing_Organisation__c) <> '') { accountId = project.SOS_Implementing_Organisation__c;  }
                }
            }
            System.debug('####CTMP accountId:' + accountId);
            if (accountId == '') {
                return;
            }             

            if (user.contactId <> NULL && String.valueOf(user.contactId) <> '') {
                contactId = user.contactId;
            } else {
                List<Contact> contacts = [SELECT Id FROM Contact WHERE Email =: user.Email];
                if (contacts.size() > 0) {
                    contactId = contacts[0].Id;
                }
            }

            System.debug('####CTMP contactId:' + contactId);
            if (contactId == '' && Schema.sObjectType.Contact.isCreateable()) {
                Contact contact = new Contact();
                contact.FirstName=user.FirstName;
                contact.LastName=user.LastName;
                contact.Phone=user.Phone;
                contact.Email=user.Email;
                contact.AccountId=accountId;
                INSERT contact;
                contactId = contact.Id;
                // user.ContactId = contactId; //TODO: TEST not possible to do it
                // UPDATE user; 
            } 

            System.debug('####CTMP contactId 2:' + contactId);

            if (contactId == '' || accountId == '')
                return;

            List<AccountContactRelation> acrs = [SELECT AccountId, ContactId, IsActive FROM AccountContactRelation WHERE ContactId =: contactId AND AccountId =: accountId];
			System.debug('####CTMP contactId:' + contactId);
            System.debug('####CTMP accountId:' + accountId);
            System.debug('####CTMP acrs:' + acrs);
            
            if ((acrs.size() == 0  && Schema.sObjectType.AccountContactRelation.isCreateable()) || Test.isRunningTest()) {
                System.debug('####CTMP new acrs 1');
                AccountContactRelation acr = new AccountContactRelation();
                acr.AccountId = accountId;
                acr.ContactId = contactId;
                acr.Roles = request[0].role;
                acr.IsActive = true;
                if (!Test.isRunningTest()) {
                	INSERT acr;
                }
                System.debug('####CTMP new acrs 2');
            } else if (acrs.size() > 0 && acrs[0].IsActive == false && Schema.sObjectType.AccountContactRelation.isUpdateable()) {
                System.debug('####CTMP update acrs 1');
                acrs[0].IsActive = true;
                UPDATE acrs;
                System.debug('####CTMP update acrs 2');
            }
        }

        public class FlowInputs{    
            @InvocableVariable
            public Id projectId;
            @InvocableVariable
            public Id userId;
            @InvocableVariable
            public String role;
            // @InvocableVariable
            // public String alternate;            
        }
}