force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/Account_Teams__c.field-meta.xml
<CustomField>
    <fullName>Account_Teams__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Organisation record which is populated here will be used as the basis for sharing this Project record with external users in the MA Portal. For Projects (Grants, Standard, Emergency) this should be the shadow Organisation record named like &quot;{Project ID} - External Project Team&quot;. For Programmes or NMUs, this should be the NA that they fall underneath.</description>
    <inlineHelpText>The Organisation record which is populated here will be used as the basis for sharing this Project record with external users in the MA Portal. For Projects (Grants, Standard, Emergency) this should be the shadow Organisation record named like &quot;{Project ID} - External Project Team&quot;. For Programmes or NMUs, this should be the NA that they fall underneath.</inlineHelpText>
    <label>External Project Team</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Account Team)</relationshipLabel>
    <relationshipName>Projects5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
            <value>
                <fullName>Project Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>IF(CreatedBy.FirstName = &apos;LUCY&apos; &amp;&amp; CreatedBy.LastName = &apos;Service Account&apos; &amp;&amp; RecordType.DeveloperName = &quot;Transition&quot; &amp;&amp;  ISPICKVAL(Transition_Project_Type__c, &apos;Construction&apos;) = FALSE &amp;&amp; New_PU_Count__c = 0, FALSE, TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Project_ID_Text__c.field-meta.xml
<CustomField>
    <fullName>Project_ID_Text__c</fullName>
    <formula>CASE(RecordType.Name,
&quot;Standard&quot;, &quot;S&quot;,
&quot;Emergency Response&quot;, &quot;E&quot;,
&quot;Funding Opportunity&quot;, &quot;F&quot;,
&quot;Humanitarian&quot;, &quot;H&quot;,
&quot;Grant&quot;, &quot;G&quot;,
&quot;Legacy&quot;, &quot;L&quot;,
&quot;End of Involvement&quot;, &quot;X&quot;,
&quot;Construction&quot;, &quot;C&quot;,
&quot;&quot;)
&amp; IF(DATEVALUE(CreatedDate) &gt; DATEVALUE(&quot;2019-12-31&quot;),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2),
IF(RecordType.Name = &quot;Grant&quot;,
RIGHT(TEXT(YEAR(Start_Identification__c)), 2),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2)
)
)
&amp; &quot;-&quot;
&amp; Project_Autonumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Project ID is generated by the system..</inlineHelpText>
    <label>Project ID Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/classes/ExternalProjectTeamBatch.cls
global class ExternalProjectTeamBatch implements Database.Batchable<sObject> {
  private String query;
    
  /*
  Execute Apex Jobs / Check on Setup => Environments => Jobs => Apex Jobs or Scheduled Jobs
  for(integer i = 0; i < 60; i++) {
    String sch = '0 ' + i + ' * * * ?';
    System.debug('i:' + i);
    ScheduledExternalProjectTeamBatch sqrb = new ScheduledExternalProjectTeamBatch();
    system.schedule('Every Hour plus ' + i + ' min', sch, sqrb);
    i = i + 2;
  }*/
    
  global ExternalProjectTeamBatch (){
  }
    
  // The batch job starts
  global Database.Querylocator start(Database.BatchableContext bc){
    String query = 'SELECT Id, Project_ID_Text__c, Account_Teams__c FROM ampi__project__c WHERE RecordType.Name IN (\'' + 'Transition' + '\') AND IsActive__c = true AND ampi__Project_status__c NOT IN (\'' + 'Project Closed' + '\',\'' + 'Closed'+ '\',\'' + '\',\'' + 'Cancelled'+ '\',\'' + 'Concept Rejected' + '\',\'' + 'Application Rejected' + '\') AND Account_Teams__c = \'\' LIMIT 10';
    System.debug('>>>> start ' + query);
    return Database.getQuerylocator(query);
  } 
  
  // The batch job executes and operates on one batch of records
  global void execute(Database.BatchableContext bc, List<sObject> scope){
            
    List<ampi__project__c> projectsToUpdate = new List<ampi__project__c>();

    for(sObject proj : scope) {
        Account acc = new Account();
        ampi__Project__c projToUpdate = (ampi__Project__c)proj;      
        acc.Name = projToUpdate.Project_ID_Text__c + ' - External Project Team';
        acc.RecordTypeId = '0121i0000008W2BAAU';
        acc.Shadow_Record__c = true;
        INSERT acc;
        
        projToUpdate.Account_Teams__c = acc.Id;      
        projectsToUpdate.add(projToUpdate);
        //System.debug('####Project ID: ' + projectsTransition + '---' + proj.Id + '/' + acc.Id);
    }
    UPDATE projectsToUpdate;
  }
  
  // The batch job finishes
  global void finish(Database.BatchableContext bc){
    AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :bc.getJobId()]; 
    System.debug('>>>> finish ' + job.Status);
  }
}