force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Credential_Domain.cls
/****************************************************************************************
* Class: Credential_Domain
* Created By: Ajinkya Hingne
----------------------------------------------------------------------------------------
* Description: Class to perform server side actions of CreateWorkspace component
----------------------------------------------------------------------------------------
* Version History:
* VERSION     DEVELOPER NAME       DATE            DETAIL FEATURES
https://vera.my.salesforce.com/a041O00000e6qhH
  1.0         Ajinkya Hingne       04/11/2019      Initial Development
***************************************************************************************/
public with sharing class Credential_Domain {

    public static List<Credential__c> getCredential(String credentialName) {
        return [
            SELECT
                Grant_Type__c,
                Client_Id__c,
                Client_Secret__c,
                Resource__c
            FROM
                Credential__c
            WHERE
                Name =: credentialName
        ];
    }

}