force-app/main/default/objects/ampi__Activity__c/ampi__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Type__c.field-meta.xml
<CustomField>
    <fullName>ampi__Type__c</fullName>
    <description>This field enables users to track the different types of activities. This field is unrestricted and can be modified by subscribers.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Results-Based</fullName>
                <default>true</default>
                <label>Results-Based</label>
            </value>
            <value>
                <fullName>Overarching</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</description>
    <inlineHelpText>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</inlineHelpText>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/ampi__Budget__c.object-meta.xml
<CustomObject>
    <description>Budget for a project</description>
    <label>Budget</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Budget__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detail field to relate a budget record to a project record.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/fields/Is_ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>Is_ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ReadOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/fields/Order_Financial__c.field-meta.xml
<CustomField>
    <fullName>Order_Financial__c</fullName>
    <label>Order Financial</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/fields/Order_Project__c.field-meta.xml
<CustomField>
    <fullName>Order_Project__c</fullName>
    <label>Order Project</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Disbursement__c/ampi__Disbursement__c.object-meta.xml
<CustomObject>
    <description>Financial payments made for a Project</description>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Disbursement__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-Detail field to specify the project this disbursement belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Disbursement__c/fields/Is_ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>Is_ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ReadOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Disbursement__c/fields/Order_Project__c.field-meta.xml
<CustomField>
    <fullName>Order_Project__c</fullName>
    <label>Order Project</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/ampi__Financial__c.object-meta.xml
<CustomObject>
    <description>Financial records of a project, per reporting period and budget</description>
    <label>Financial</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Activity__c.field-meta.xml
<CustomField>
    <fullName>ampi__Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to add financial line items to a project activity.</description>
    <label>Activity</label>
    <referenceTo>ampi__Activity__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Budget__c.field-meta.xml
<CustomField>
    <fullName>ampi__Budget__c</fullName>
    <description>Master-detail field to relate a financial record to a budget record.</description>
    <label>Budget</label>
    <referenceTo>ampi__Budget__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Category__c.field-meta.xml
<CustomField>
    <fullName>ampi__Category__c</fullName>
    <description>This picklist field is for categorizing Financial records based on their purpose. This field is unrestricted and can be modified by subscribers.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Result based</fullName>
            </value>
            <value>
                <fullName>9 PSCI</fullName>
            </value>
            <value>
                <fullName>Overarching</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>ADV</fullName>
            </value>
            <value>
                <fullName>SIL</fullName>
            </value>
            <value>
                <fullName>FLC</fullName>
            </value>
            <value>
                <fullName>DFE</fullName>
            </value>
            <value>
                <fullName>CFE</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>HA</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>ECD</fullName>
            </value>
            <value>
                <fullName>EDU</fullName>
            </value>
            <value>
                <fullName>EET</fullName>
            </value>
            <value>
                <fullName>ER</fullName>
            </value>
            <value>
                <fullName>FFC</fullName>
            </value>
            <value>
                <fullName>FS</fullName>
            </value>
            <value>
                <fullName>HPP</fullName>
            </value>
            <value>
                <fullName>MED</fullName>
            </value>
            <value>
                <fullName>OA</fullName>
            </value>
            <value>
                <fullName>OAC</fullName>
            </value>
            <value>
                <fullName>SGH</fullName>
            </value>
            <value>
                <fullName>SFC</fullName>
            </value>
            <value>
                <fullName>YC</fullName>
            </value>
            <value>
                <fullName>3 CMG CI</fullName>
            </value>
            <value>
                <fullName>3 FD CI</fullName>
            </value>
            <value>
                <fullName>2 IF4C COR</fullName>
            </value>
            <value>
                <fullName>2 IF4C D2D</fullName>
            </value>
            <value>
                <fullName>2 IF4C DB</fullName>
            </value>
            <value>
                <fullName>3 IF4C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Type__c.field-meta.xml
<CustomField>
    <fullName>ampi__Type__c</fullName>
    <description>Picklist to denote the type of the financial record. The value in this picklist determines which rollup fields (Planned Revenue and Actual Revenue or Planned Expenditure and Actual Expenditure) a particular Financial record is counted in.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Expenditure</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/Order_Project__c.field-meta.xml
<CustomField>
    <fullName>Order_Project__c</fullName>
    <label>Order Project</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/recordTypes/Construction.recordType-meta.xml
<RecordType>
    <fullName>Construction</fullName>
    <active>true</active>
    <description>The project that describes the steps of SOS Children&apos;s Villages construction, renovation and purchasing procedures</description>
    <label>Construction</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Emergency_Response.recordType-meta.xml
<RecordType>
    <fullName>Emergency_Response</fullName>
    <active>true</active>
    <description>Projects for preparedness or response to emergencies or disasters funded by SOS internal resources. Humanitarian aid as part of an institutionally funded project should be registered as a grant.</description>
    <label>Humanitarian</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <description>Defined by contract with institutional donor, major corporate or foundation following PCM/RBM. Funded by int. or local funds. Can take place at programme, national or multi-country level. If in response to a humanitarian crisis, indicate in project setup.</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/classes/FinancialTriggerHandler.cls
public class FinancialTriggerHandler {
    public void afterInsertSetOrderPerProject(List<ampi__Financial__c> newFinancials) {
            if (newFinancials.size() == 0) {
                return;
            }
            
            Integer order = 0;
            Integer initialOrderForGrantTransition = 0;
            Integer initialOrderForStandardER = 0;
            Integer standardERCount = 0;
            Integer grantTransitionCount = 0;

            Set<Id> projectIds = new Set<Id>();
            Boolean hasRecordsToUpdate = false; 
            Set<Id> ids = (new Map<Id, ampi__Financial__c>(newFinancials)).keySet();
            
            List<ampi__Financial__c> newFinancialsToUpdate = [SELECT Id, Is_ReadOnly__c, ampi__Activity__c, ampi__Budget__r.Id, Order_Project__c, ampi__Budget__r.ampi__Project__c, ampi__Budget__r.ampi__Project__r.Name, ampi__Budget__r.ampi__Project__r.RecordTypeId FROM ampi__Financial__c WHERE Id =: ids AND ampi__Budget__r.ampi__Project__c != NULL];
            //System.debug('#### newFinancialsToUpdate:' + newFinancialsToUpdate.size());
            if (newFinancialsToUpdate == null || newFinancialsToUpdate.size() == 0) {
                return;
            }
            
            if (newFinancialsToUpdate.size() > 0) {
                for (ampi__Financial__c financialUpdate : newFinancialsToUpdate)
                if (!projectIds.contains(financialUpdate.ampi__Budget__r.ampi__Project__c)) {
                    projectIds.add(financialUpdate.ampi__Budget__r.ampi__Project__c);
                }
            }
            
            //projectName = newFinancialsToUpdate[0].ampi__Budget__r.ampi__Project__r.Name;
            //projectRecordTypeId = newFinancialsToUpdate[0].ampi__Budget__r.ampi__Project__r.RecordTypeId;

            //List<ampi__Financial__c> orderOnFinancialByProject = [SELECT Id, Order_Project__c, ampi__Activity__c FROM ampi__Financial__c WHERE ampi__Budget__r.ampi__Project__c =: projectId AND Order_Project__c <> NULL ORDER BY Order_Project__c DESC LIMIT 1];
            // List<ampi__Financial__c> orderOnFinancialByProject = new List<ampi__Financial__c>();
            // System.debug('####Schema.SObjectType.ampi__project__c.getRecordTypeInfosByName():' + Schema.SObjectType.ampi__project__c.getRecordTypeInfosByDeveloperName());
            // System.debug('####Schema.SObjectType.ampi__project__c.getRecordTypeInfosByName() Standard:' + Schema.SObjectType.ampi__project__c.getRecordTypeInfosByDeveloperName().get('Standard'));
            // System.debug('####Schema.SObjectType.ampi__project__c.getRecordTypeInfosByName() Humanitarian/Emergency_Response:' + Schema.SObjectType.ampi__project__c.getRecordTypeInfosByDeveloperName().get('Emergency_Response'));

            Id standardRecordType = Schema.SObjectType.ampi__project__c.getRecordTypeInfosByDeveloperName().get('Standard').getRecordTypeId();
            Id ERRecordType = Schema.SObjectType.ampi__project__c.getRecordTypeInfosByDeveloperName().get('Emergency_Response').getRecordTypeId();
            Id grantRecordType = Schema.SObjectType.ampi__project__c.getRecordTypeInfosByDeveloperName().get('Grant').getRecordTypeId();
            Id constructionRecordType = Schema.SObjectType.ampi__project__c.getRecordTypeInfosByDeveloperName().get('Construction').getRecordTypeId();
            Id transitionRecordType = Schema.SObjectType.ampi__project__c.getRecordTypeInfosByDeveloperName().get('Transition').getRecordTypeId();

            //System.debug('#### orderOnFinancialByProject:' + orderOnFinancialByProject.size());                     
            
            Set<Id> objBudgets = new Set<Id>();
            Set<Id> objFinancialsReadOnly = new Set<Id>();
            //Set<Id> objDisbursements = new Set<Id>();

            List<ampi__Financial__c> financialOrderOnStandardERByProject = [SELECT Id, Order_Project__c, ampi__Activity__r.Project__c
                                                            FROM ampi__Financial__c WHERE 
                                                            (ampi__Activity__r.Project__r.RecordTypeId =: standardRecordType OR ampi__Activity__r.Project__r.RecordTypeId =: ERRecordType) AND
                                                            ampi__Activity__r.Project__c IN : projectIds AND 
                                                            ampi__Activity__r.ampi__Type__c IN ('Results-Based', 'Overarching') AND
                                                            Order_Project__c <> NULL AND
                                                            ampi__Type__c = 'Expenditure' ORDER BY Order_Project__c DESC];

            System.debug('###financialOrderOnStandardERByProject:' + financialOrderOnStandardERByProject);
            List<ampi__Financial__c> financialOrderGrantTransitionByProject = [SELECT Id, Order_Project__c, ampi__Budget__r.ampi__Project__c
                                                            FROM ampi__Financial__c WHERE 
                                                            ampi__Budget__r.ampi__Project__c IN : projectIds AND 
                                                            Order_Project__c <> NULL
                                                            ORDER BY Order_Project__c DESC];
			
        	System.debug('###financialOrderGrantTransitionByProject:' + financialOrderGrantTransitionByProject);            
            for(ampi__Financial__c newFinancial : newFinancialsToUpdate) {    
                    if (newFinancial.Is_ReadOnly__c) {
                        newFinancial.Is_ReadOnly__c = false;
                        objFinancialsReadOnly.add(newFinancial.Id);
                    }

                    Id projectId = newFinancial.ampi__Budget__r.ampi__Project__c;      
                    String projectName = newFinancial.ampi__Budget__r.ampi__Project__r.Name;  
                    Id projectRecordTypeId = newFinancial.ampi__Budget__r.ampi__Project__r.RecordTypeId;

                    //System.debug('#### projectRecordTypeId:' + projectRecordTypeId);
                    //System.debug('#### projectId:' + projectId);
                    //System.debug('#### projectName:' + projectName);

                    if (projectId != NULL) {
                        for (ampi__Financial__c fin : financialOrderOnStandardERByProject) {
                            if (fin.ampi__Activity__r != NULL && fin.ampi__Activity__r.Project__c == projectId && initialOrderForStandardER == 0) {
                                initialOrderForStandardER = Integer.ValueOf(fin.Order_Project__c);
                            }    
                        }    
                        
                        for (ampi__Financial__c fin : financialOrderGrantTransitionByProject) {
                            if (fin.ampi__Budget__r != NULL && fin.ampi__Budget__r.ampi__Project__c == projectId && initialOrderForGrantTransition == 0) {
                                initialOrderForGrantTransition = Integer.ValueOf(fin.Order_Project__c);
                            }    
                        }                        
                                    
                        boolean found = false;
                        if (projectRecordTypeId == standardRecordType || projectRecordTypeId == ERRecordType || projectRecordTypeId == constructionRecordType) {
                            if (newFinancial.ampi__Activity__c != NULL) {
                                //System.debug('####orderOnFinancialByProject Standard/ER:' + orderOnFinancialByProject.size());
                                found = true;
                                standardERCount += 1;
                                order = initialOrderForStandardER + standardERCount;
                            }
                        }

                        if (projectRecordTypeId == grantRecordType || projectRecordTypeId == transitionRecordType || 
                            (projectRecordTypeId == standardRecordType && newFinancial.ampi__Activity__c == NULL) ||
                            (projectRecordTypeId == ERRecordType && newFinancial.ampi__Activity__c == NULL)) {
                            found = true;
                            grantTransitionCount += 1;                            
                            order = initialOrderForGrantTransition + grantTransitionCount;
                            //System.debug('####orderOnFinancialByProject Grant/Transition:' + orderOnFinancialByProject.size());
                        }

                        if (found == false) {
                            order = order + 1;
                        }
                    } else {
                        order = order + 1;
                    }            
                    System.debug('#### new order: ' + order);  

                    if (newFinancial.Order_Project__c != order) {
                        hasRecordsToUpdate = true;                
                        newFinancial.Order_Project__c = order;                    
                    }  
                    
                    objBudgets.add(newFinancial.ampi__Budget__r.Id);
                    //objDisbursements.add(newFinancial.ampi__Disbursement__r.Id);
            }
            System.debug('####hasRecordsToUpdate 1:' + hasRecordsToUpdate);
            if (hasRecordsToUpdate) {
                UPDATE newFinancialsToUpdate;
                System.debug('####objFinancialsReadOnly.size() 2:' + objFinancialsReadOnly.size());
                if(objFinancialsReadOnly.size() > 0) {
                    newFinancialsToUpdate = [SELECT Id, Is_ReadOnly__c FROM ampi__Financial__c WHERE Id IN: objFinancialsReadOnly];
                    for(ampi__Financial__c newFinancial : newFinancialsToUpdate) {    
                        newFinancial.Is_ReadOnly__c = true;
                        System.debug('####newFinancial 3:' + newFinancial.Is_ReadOnly__c);
                    }
                    UPDATE newFinancialsToUpdate;
                }

                List<ampi__budget__c> updateBudgets = [SELECT Id, Order_Financial__c FROM ampi__budget__c WHERE Id IN: objBudgets];

                if (updateBudgets.size() > 0) {
                    Boolean hasChangesToUpdate = false;
                    for(ampi__budget__c updateBudget : updateBudgets) {
                        if (updateBudget.Order_Financial__c != (order + '')) {
                            updateBudget.Order_Financial__c = order + '';
                            hasChangesToUpdate = true;
                        }
                        
                    }
                    if (hasChangesToUpdate == true) {
                        UPDATE updateBudgets;
                    }
                }

                /*List<ampi__disbursement__c> updateDisbursements = [SELECT Id, Order_Financial__c FROM ampi__disbursement__c WHERE Id IN: objDisbursements];

                IF (updateDisbursements.size() > 0) {
                    for(ampi__disbursement__c updateDisbursement : updateDisbursements) {
                        updateDisbursement.Order_Financial__c = order + '';
                    }

                    UPDATE updateDisbursements;
                }*/
            }
    }   



    public void beforeDeleteRestrictionDeletion(List<ampi__Financial__c> newFinancials) {
        for(ampi__Financial__c acc : newFinancials){
            if (acc.ampi__Category__c == '3 CMG CI') {
                acc.addError('Financials from category "3 CMG CI" are not allowed to be removed or changed');
            } 

			if (acc.Is_ReadOnly__c == true) {
				Id profileId = userinfo.getProfileId();
                List<Profile> profiles = [Select Name from Profile where Id =: profileId AND Name = 'System Administrator'];

                if (profiles.size() == 0) {
                    acc.addError('Financials are not allowed to be removed or changed');                                                    
                }
            }
        } 
    }

    public void beforeUpdateRestrictionDeletion(List<ampi__Financial__c> oldFinancials, List<ampi__Financial__c> newFinancials) {
        for(ampi__Financial__c acc : newFinancials){
            if (acc.ampi__Category__c == '3 CMG CI') {
                for(ampi__Financial__c accold : oldFinancials) {
                    if (acc.Id == accold.Id && acc.Order_Project__c == accold.Order_Project__c && acc.Is_ReadOnly__c == accold.Is_ReadOnly__c) {
                        acc.addError('Financials from category "3 CMG CI" are not allowed to be removed or changed');
                    }
                }
            } 

            if (acc.Is_ReadOnly__c == true) {
                Id profileId = userinfo.getProfileId();
                List<Profile> profiles = [Select Name from Profile where Id =: profileId AND Name = 'System Administrator'];

                if (profiles.size() == 0) {
                    for(ampi__Financial__c accold : oldFinancials) {
                        if (acc.Id == accold.Id && acc.Order_Project__c == accold.Order_Project__c && acc.Is_ReadOnly__c == accold.Is_ReadOnly__c) {
                            acc.addError('Financials are not allowed to be removed or changed');
                        }
                    }
                }                
            }
        } 
    }

    public void beforeInsertFinancialCategory(List<ampi__Financial__c> newFinancials) {
        for(ampi__Financial__c acc : newFinancials){
            if (acc.ampi__Category__c == '3 IF4C' && acc.Is_ReadOnly__c == false) {
                acc.addError('Financials from category "3 IF4C" are not allowed to be created by users');
            } 
        } 
    }
}