force-app/main/default/objects/ampi__Activity__c/ampi__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>This long text field is used to store additional details about this Activity.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Implementation_Plan__c.field-meta.xml
<CustomField>
    <fullName>ampi__Implementation_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to associate an Activity with an Implementation Plan. This field must be populated for an Activity record to display on the ActivityChart Lightning Component.</description>
    <label>Implementation Plan</label>
    <referenceTo>ampi__Implementation_Plan__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Implementation_Plan__c/ampi__Implementation_Plan__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan</label>
    <nameField>
        <label>Implementation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Implementation_Plan__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>This field stores additional details about the Implementation Plan as needed.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Implementation_Plan__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the project this implementation plan is related to</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Implementation Plans</relationshipLabel>
    <relationshipName>Implementation_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/ampi__Objective__c.object-meta.xml
<CustomObject>
    <description>An objective that has been assigned to a specific project</description>
    <label>Framework Objective</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Project Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project objective</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Label__c.field-meta.xml
<CustomField>
    <fullName>ampi__Label__c</fullName>
    <description>Text field to store the Name value of the parent Catalog Objective. This is populated by the Process on the Project Objective (ampi__Objective__c) object and can be manually modified afterwards.</description>
    <label>Objective Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Objective__c.field-meta.xml
<CustomField>
    <fullName>ampi__Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the parent catalog objective</description>
    <label>Objective</label>
    <referenceTo>ampi__Catalog_Objective__c</referenceTo>
    <relationshipLabel>Project Objectives</relationshipLabel>
    <relationshipName>Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Parent_Project_Objective__c.field-meta.xml
<CustomField>
    <fullName>ampi__Parent_Project_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self-lookup to create a hierarchy between objectives within a project, as displayed on ManageLogframes</description>
    <label>Parent Framework Objective</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>$Source.ampi__Project__c</field>
            <operation>equals</operation>
            <valueField>ampi__Objective__c.ampi__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Objective__c</referenceTo>
    <relationshipLabel>Child Project Objectives</relationshipLabel>
    <relationshipName>Child_Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to specify the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project</description>
    <inlineHelpText>Add description of your project (1024 char max), describe specific objectives. Include key words to ease the search (e.g. country, donor). The description can be changed and updated at any time and is shown on the Team Site.</inlineHelpText>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Funding_organisation__c.field-meta.xml
<CustomField>
    <fullName>Funding_organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select SOS organisation that will provides funds for the project .</inlineHelpText>
    <label>Funding organisation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SOS Organisation - MA</value>
        </filterItems>
        <infoMessage>Please select an SOS Organisation (MA)</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Funding PSA)</relationshipLabel>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identification</fullName>
                <default>true</default>
                <label>Identification</label>
            </value>
            <value>
                <fullName>Formulation</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Closure</fullName>
            </value>
            <value>
                <fullName>In Setup</fullName>
            </value>
            <value>
                <fullName>In Tendering</fullName>
            </value>
            <value>
                <fullName>In Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Planned_Implementation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Implementation_Start_Date__c</fullName>
    <inlineHelpText>Date when you will start providing services to beneficiaries</inlineHelpText>
    <label>Planned Implementation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Service_Type_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Service_Type_Assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Type Assigned?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/ampi__Project_Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Junction linking a project to a thematic area</description>
    <label>Project Thematic Area</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Project Thematic Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Thematic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>This master-detail field refers to the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Thematic Areas</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Thematic_Area__c</fullName>
    <description>This master-detail field refers to the parent thematic area</description>
    <label>Thematic Area</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Related Projects</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Thematic_Area__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to descrive the thematic area</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ProjectResultStatementTriggerHandlerTest.cls
@isTest
private class ProjectResultStatementTriggerHandlerTest {
    @isTest 
    static void beforeUpdateRestriction_PRSCheckError() {
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
        Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
        ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
		
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, gaProgramme.Id, '', '');
        
        ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__Thematic_Area__c thematicAreaYC2 = TestDataFactory.createThematicArea('YC2', 'Youth Care (similar to YF 2)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        ampi__Activity__c act2 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act2', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
                
		ampi__Objective__c newObjectiveImp = TestDataFactory.createProjectResultStatement('Impact', 1, '', projectTransition.Id);
        ampi__Objective__c newObjectiveImp2 = TestDataFactory.createProjectResultStatement('Impact', 2, '', projectTransition.Id);
        ampi__Objective__c newObjectiveOut = TestDataFactory.createProjectResultStatement('Output', 1, newObjectiveImp.Id, projectTransition.Id);
        ampi__Objective__c newObjectiveOut2 = TestDataFactory.createProjectResultStatement('Output', 2, newObjectiveImp.Id, projectTransition.Id);

        projectTransition.Service_Type_Assigned__c = true;
        projectTransition.ampi__Project_Status__c = 'In Implementation';
        projectTransition.Phase__c = 'Implementation';
        projectTransition.Planned_Implementation_Start_Date__c = Date.newinstance(Date.today().year(), 1, 1);
        projectTransition.Funding_organisation__c = accNA.Id;

        Update projectTransition;
        
		Test.startTest();
        Boolean exceptionOccurredUpdating = false;
        
        try{
            newObjectiveOut.ampi__Parent_Project_Objective__c = newObjectiveImp2.Id;
            update newObjectiveOut;
		}catch (Exception e){
            //Set boolean to true to catch exception being thrown
            exceptionOccurredUpdating = e.getMessage().contains('Cannot update Related Project Result Statement fields from the Project');
        }

        System.assert(exceptionOccurredUpdating);

        Test.stopTest();        
    }

    @isTest 
    static void beforeDeleteRestriction_PRSCheckError() {
    	ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
        ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
		
        ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, gaProgramme.Id, '', '');
		
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__Thematic_Area__c thematicAreaYC2 = TestDataFactory.createThematicArea('YC2', 'Youth Care (similar to YF 2)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        ampi__Activity__c act2 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act2', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        
        ampi__Objective__c newObjectiveImp = TestDataFactory.createProjectResultStatement('Impact', 1, '', projectTransition.Id);
        ampi__Objective__c newObjectiveImp2 = TestDataFactory.createProjectResultStatement('Impact', 2, '', projectTransition.Id);
        ampi__Objective__c newObjectiveOut = TestDataFactory.createProjectResultStatement('Output', 1, newObjectiveImp.Id, projectTransition.Id);
        ampi__Objective__c newObjectiveOut2 = TestDataFactory.createProjectResultStatement('Output', 2, newObjectiveImp.Id, projectTransition.Id);

        projectTransition.Service_Type_Assigned__c = true;
        projectTransition.Planned_Implementation_Start_Date__c = Date.newinstance(Date.today().year(), 1, 1);
        projectTransition.Funding_organisation__c = accNA.Id;
        projectTransition.ampi__Project_Status__c = 'In Implementation';
        projectTransition.Phase__c = 'Implementation';        
        Update projectTransition;
        
		Test.startTest();
        Boolean exceptionOccurredUpdating = false;
        
        try{
            delete newObjectiveOut;
		}catch (Exception e){
            //Set boolean to true to catch exception being thrown
            exceptionOccurredUpdating = e.getMessage().contains('Cannot delete Project Result Statement if the project');
        }

        System.assert(exceptionOccurredUpdating);

        Test.stopTest();        
    }

    @isTest 
    static void beforeInsertSetShortDescription_Checks() {
    	ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
        ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
		
        ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, gaProgramme.Id, '', '');
		
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__Thematic_Area__c thematicAreaYC2 = TestDataFactory.createThematicArea('YC2', 'Youth Care (similar to YF 2)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        ampi__Activity__c act2 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act2', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        
        ampi__Objective__c newObjectiveImp = TestDataFactory.createProjectResultStatement('Impact', 1, '', projectTransition.Id);
        ampi__Objective__c newObjectiveImp2 = TestDataFactory.createProjectResultStatement('Impact', 2, '', projectTransition.Id);
        ampi__Objective__c newObjectiveOut = TestDataFactory.createProjectResultStatement('Output', 1, newObjectiveImp.Id, projectTransition.Id);
        ampi__Objective__c newObjectiveOut2 = TestDataFactory.createProjectResultStatement('Output', 2, newObjectiveImp.Id, projectTransition.Id);

        String originalFullText = 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.';
        ampi__Objective__c newObjective = new ampi__Objective__c();
        newObjective.RecordTypeId = ampi__Objective__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('YouthCan! Project Result Statement').getRecordTypeId();
        newObjective.ampi__Description__c = originalFullText;
        newObjective.ampi__Label__c = 'Test Label Output rnd ';
        newObjective.ampi__Level__c = 'Output';
        newObjective.ampi__Parent_Project_Objective__c = newObjectiveImp.Id;
        newObjective.ampi__Project__c = projectTransition.Id;
        insert newObjective;
        
		Test.startTest();        
        System.assert(originalFullText.length() > newObjective.description_short__c.length());
        Test.stopTest();        
    }

    @isTest 
    static void beforeUpdateSetShortDescription_Checks() {
    	ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
        ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
		
        ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, gaProgramme.Id, '', '');
		
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__Thematic_Area__c thematicAreaYC2 = TestDataFactory.createThematicArea('YC2', 'Youth Care (similar to YF 2)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        ampi__Activity__c act2 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act2', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        
        ampi__Objective__c newObjectiveImp = TestDataFactory.createProjectResultStatement('Impact', 1, '', projectTransition.Id);
        ampi__Objective__c newObjectiveImp2 = TestDataFactory.createProjectResultStatement('Impact', 2, '', projectTransition.Id);
        ampi__Objective__c newObjectiveOut = TestDataFactory.createProjectResultStatement('Output', 1, newObjectiveImp.Id, projectTransition.Id);
        ampi__Objective__c newObjectiveOut2 = TestDataFactory.createProjectResultStatement('Output', 2, newObjectiveImp.Id, projectTransition.Id);

        String originalFullText = 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.';
        ampi__Objective__c newObjective = new ampi__Objective__c();
        newObjective.RecordTypeId = ampi__Objective__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('YouthCan! Project Result Statement').getRecordTypeId();
        newObjective.ampi__Description__c = 'Test Description Output rnd ';
        newObjective.ampi__Label__c = 'Test Label Output rnd ';
        newObjective.ampi__Level__c = 'Output';
        newObjective.ampi__Parent_Project_Objective__c = newObjectiveImp.Id;
        newObjective.ampi__Project__c = projectTransition.Id;
        INSERT newObjective;
        
		Test.startTest();        

        newObjective.ampi__Description__c = originalFullText;
        UPDATE newObjective;
        System.assert(originalFullText.length() > newObjective.description_short__c.length());

        Test.stopTest();        
    }
}