force-app/main/default/objects/ampi__Activity__c/ampi__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Implementation_Plan__c.field-meta.xml
<CustomField>
    <fullName>ampi__Implementation_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to associate an Activity with an Implementation Plan. This field must be populated for an Activity record to display on the ActivityChart Lightning Component.</description>
    <label>Implementation Plan</label>
    <referenceTo>ampi__Implementation_Plan__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Implementation_Plan__c/ampi__Implementation_Plan__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan</label>
    <nameField>
        <label>Implementation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Implementation_Plan__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the project this implementation plan is related to</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Implementation Plans</relationshipLabel>
    <relationshipName>Implementation_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/ampi__Objective__c.object-meta.xml
<CustomObject>
    <description>An objective that has been assigned to a specific project</description>
    <label>Framework Objective</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Project Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Objective__c.field-meta.xml
<CustomField>
    <fullName>ampi__Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the parent catalog objective</description>
    <label>Objective</label>
    <referenceTo>ampi__Catalog_Objective__c</referenceTo>
    <relationshipLabel>Project Objectives</relationshipLabel>
    <relationshipName>Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to specify the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/activityExtensionTest.cls
@isTest
private class activityExtensionTest {
    @isTest
    private static void activityExtensionTest_CreatingTests() {
        Test.startTest();
        
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('New Programme Unit based on Callao', gaProgramme.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
		
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectStandard.Id);
		
		ampi__Objective__c obj1 = TestDataFactory.createProjectResultStatement('Impact', 1, '', projectStandard.Id);
		ampi__Objective__c obj2 = TestDataFactory.createProjectResultStatement('Outcome', 2, obj1.Id, projectStandard.Id);
		ampi__Objective__c obj3 = TestDataFactory.createProjectResultStatement('Output', 3, obj2.Id, projectStandard.Id);
		
        TestDataFactory.createActivityWithDates(ip.Id, 'act 1', 'Results-Based', 'Task', 'New', projectStandard.Id, Date.newInstance(2023, 1, 1), Date.newInstance(2023, 1, 21), obj3.Id, '1');
        TestDataFactory.createActivityWithDates(ip.Id, 'act 2', 'Results-Based', 'Task', 'New', projectStandard.Id, Date.newInstance(2022, 1, 1), Date.newInstance(2022, 1, 21), obj3.Id, '2');
        TestDataFactory.createActivityWithDates(ip.Id, 'act 3', 'Results-Based', 'Task', 'New', projectStandard.Id, Date.newInstance(2023, 1, 1), Date.newInstance(2023, 1, 21), obj3.Id, '3');
	    
		List<ampi__project__c> projs = activityExtension.getProjectInfoStatus(projectStandard.Id);
		System.assert(projs.size() > 0);

		List<ampi__objective__c> objs = activityExtension.getProjectResultStatementFromProject(projectStandard.Id);
		System.assert(objs.size() > 0);
		
		Integer earlyYear = activityExtension.getEarlyStartDateFromActivity(projectStandard.Id);
		System.assert(earlyYear > 0);

		Integer endingYear = activityExtension.getLateStartDateFromActivity(projectStandard.Id);
		System.assert(endingYear > 0);

		List<ampi__activity__c> activities = activityExtension.getActivitiesFromYearAndResultAndProject(earlyYear, objs[0].Id, projectStandard.Id);
		System.assert(activities.size() > 0);

		List<ampi__activity__c> activities2 = activityExtension.getMainActivitiesFromYearAndNewStatus(earlyYear, projectStandard.Id);
		System.assert(activities2.size() > 0);

		String result = activityExtension.updateMainActivitiesFromYearAndNewStatusToPlanning(earlyYear, projectStandard.Id);
		System.assert(result == '');

		List<activityExtension.LabelValue> statuses = activityExtension.getStatusesFromActivity();
		System.assert(statuses.size() > 0);

        Test.stopTest();                
    }
}