force-app/main/default/objects/ampi__Activity__c/ampi__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Activity__c/fields/Activity_ID__c.field-meta.xml
<CustomField>
    <fullName>Activity_ID__c</fullName>
    <label>Activity ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Actual_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ampi__Actual_End_Date__c</fullName>
    <description>This field tracks the actual end date of an activity. If populated, it will display in the Gantt chart on the ActivityChart Lightning Component.</description>
    <label>Actual End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Actual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ampi__Actual_Start_Date__c</fullName>
    <description>This field tracks the actual start date of an activity. If populated, it will display in the Gantt chart on the ActivityChart Lightning Component.</description>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>This long text field is used to store additional details about this Activity.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Parent_Activity__c.field-meta.xml
<CustomField>
    <fullName>ampi__Parent_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup field looks up to a parent activity to create a hierarchy of activities.</description>
    <inlineHelpText>For sub-activities, please select the related main activities (needs to be entered before). For main activities, please select &quot;none / main activity.</inlineHelpText>
    <label>Parent Activity</label>
    <referenceTo>ampi__Activity__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Project_Objective__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to connect Activities to a Project Objective.</description>
    <label>Framework Objective</label>
    <referenceTo>ampi__Objective__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Status__c</fullName>
    <description>Picklist field to track the status and progress of an Activity. This field is unrestricted and can be modified by subscribers.</description>
    <inlineHelpText>Changing the status of activities from &quot;new&quot; to either &quot;planning&quot;, &quot;in progress&quot;, &quot;delayed&quot; or &quot;completed&quot; will trigger a synchronization to D365 IF the activity belongs to either the following (budgeting) year or to current year.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ampi__xx_Activity_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Cancelled/NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</description>
    <inlineHelpText>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</inlineHelpText>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>Thematic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/ampi__Objective__c.object-meta.xml
<CustomObject>
    <description>An objective that has been assigned to a specific project</description>
    <label>Framework Objective</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Project Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Deactivated__c.field-meta.xml
<CustomField>
    <fullName>ampi__Deactivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox field to determine whether a Project Objective is active and thus whether it should be displayed on the ManageLogframes page</description>
    <inlineHelpText>Check this box if you no longer want to display this Objective in the Framework. All data related to this Objective will be preserved.</inlineHelpText>
    <label>Deactivated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project objective</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Label__c.field-meta.xml
<CustomField>
    <fullName>ampi__Label__c</fullName>
    <description>Text field to store the Name value of the parent Catalog Objective. This is populated by the Process on the Project Objective (ampi__Objective__c) object and can be manually modified afterwards.</description>
    <label>Objective Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Level__c.field-meta.xml
<CustomField>
    <fullName>ampi__Level__c</fullName>
    <description>Picklist field to determine the level of an objective. This is populated by the Process on the Project Objective (ampi__Objective__c) object and can be manually modified afterwards.</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Impact</fullName>
            </value>
            <value>
                <fullName>Outcome</fullName>
            </value>
            <value>
                <fullName>Output</fullName>
            </value>
            <value>
                <fullName>Input</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Objective__c.field-meta.xml
<CustomField>
    <fullName>ampi__Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the parent catalog objective</description>
    <label>Objective</label>
    <referenceTo>ampi__Catalog_Objective__c</referenceTo>
    <relationshipLabel>Project Objectives</relationshipLabel>
    <relationshipName>Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to specify the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project</description>
    <inlineHelpText>Add description of your project (1024 char max), describe specific objectives. Include key words to ease the search (e.g. country, donor). The description can be changed and updated at any time and is shown on the Team Site.</inlineHelpText>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identification</fullName>
                <default>true</default>
                <label>Identification</label>
            </value>
            <value>
                <fullName>Formulation</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Closure</fullName>
            </value>
            <value>
                <fullName>In Setup</fullName>
            </value>
            <value>
                <fullName>In Tendering</fullName>
            </value>
            <value>
                <fullName>In Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Thematic_Area__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to descrive the thematic area</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/activityExtension.cls
public without sharing class activityExtension {
    
    @AuraEnabled
    public static List<ampi__project__c> getProjectInfoStatus(String projectId) {													
        return [SELECT Id, ampi__project_status__c, phase__c FROM ampi__project__c WHERE Id =: projectId];
    }   

    @AuraEnabled
    public static List<ampi__objective__c> getProjectResultStatementFromProject(String projectId) {													
        return [SELECT Id, ampi__Label__c, ampi__Description__c FROM ampi__objective__c WHERE ampi__Project__c =: projectId AND ampi__Deactivated__c = false AND IsDeleted = false AND ampi__Level__c = 'Output' ORDER BY ampi__Label__c DESC]; // AND recordTypeId =: '0123O000002OQC0QAO'];
    }    
    @AuraEnabled
    public static Integer getEarlyStartDateFromActivity(String projectId) {
        List<ampi__activity__c> activities = [SELECT Id, ampi__Actual_Start_Date__c FROM ampi__activity__c WHERE project__c =: projectId AND IsDeleted = false AND ampi__Actual_Start_Date__c <> null ORDER BY ampi__Actual_Start_Date__c ASC]; 

        if (activities.size() == 0)
            return 0;

        return activities[0].ampi__Actual_Start_Date__c.year();
    }
    @AuraEnabled
    public static Integer getLateStartDateFromActivity(String projectId) {
        List<ampi__activity__c> activities = [SELECT Id, ampi__Actual_Start_Date__c FROM ampi__activity__c WHERE project__c =: projectId AND IsDeleted = false AND ampi__Actual_Start_Date__c <> null ORDER BY ampi__Actual_Start_Date__c DESC]; 
        //ampi__Actual_End_Date__c
        if (activities.size() == 0)
            return 0;

        return activities[0].ampi__Actual_Start_Date__c.year();
    } 
    @AuraEnabled
    public static List<ampi__activity__c> getActivitiesFromYearAndResultAndProject(Integer year, String result, String projectId) {
        return [SELECT Id, Name, ampi__Status__c, Activity_ID__c, thematic_area__r.Name FROM ampi__activity__c WHERE CALENDAR_YEAR(ampi__Actual_Start_Date__c) =: year AND project__c =: projectId AND ampi__Project_Objective__c =: result AND IsDeleted = false ORDER BY Name DESC]; 
    }
    @AuraEnabled
    public static List<ampi__activity__c> getMainActivitiesFromYearAndNewStatus(Integer year, String projectId) {
        return [SELECT Id, Name, ampi__Status__c, Activity_ID__c, thematic_area__r.Name FROM ampi__activity__c WHERE CALENDAR_YEAR(ampi__Actual_Start_Date__c) =: year AND project__c =: projectId AND ampi__Status__c = 'New' AND ampi__Parent_Activity__c = null AND IsDeleted = false ORDER BY Name DESC]; 
    }
    @AuraEnabled
    public static String updateMainActivitiesFromYearAndNewStatusToPlanning(Integer year, String projectId) {
         List<ampi__activity__c> activities = [SELECT Id, ampi__Status__c FROM ampi__activity__c WHERE CALENDAR_YEAR(ampi__Actual_Start_Date__c) =: year AND project__c =: projectId AND ampi__Status__c = 'New' AND ampi__Parent_Activity__c = null AND IsDeleted = false]; 

         for (ampi__activity__c act : activities) {
             act.ampi__Status__c = 'Planning';
         }

         try {
            UPDATE activities;             
         } catch(Exception ex) {
             return ex.getMessage();
         }
         return '';
    }
    @AuraEnabled(cacheable=true)
    public static List<LabelValue> getStatusesFromActivity() {
        Schema.DescribeFieldResult fieldDetail = ampi__activity__c.ampi__Status__c.getDescribe(); 
        List<Schema.PicklistEntry> values = fieldDetail.getPicklistValues();
        List<LabelValue> picklist = new List<LabelValue>();
        for (Schema.PicklistEntry value : values) {
            //values.getValue()
            //values.getLabel()
            if (value.isActive()) {
                LabelValue newItem = new LabelValue();
                newItem.label = value.getLabel();
                newItem.value = value.getValue();
                picklist.add(newItem);
            }
            //values.isDefaultValue()
        }
        return picklist;
    }

    public class LabelValue{    
        @AuraEnabled public String label;
        @AuraEnabled public String value;
    }

}