force-app/main/default/objects/ampi__Activity__c/ampi__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Activity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</description>
    <inlineHelpText>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</inlineHelpText>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/ampi__Budget__c.object-meta.xml
<CustomObject>
    <description>Budget for a project</description>
    <label>Budget</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Budget__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detail field to relate a budget record to a project record.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/fields/Is_ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>Is_ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ReadOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/ampi__Financial__c.object-meta.xml
<CustomObject>
    <description>Financial records of a project, per reporting period and budget</description>
    <label>Financial</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Activity__c.field-meta.xml
<CustomField>
    <fullName>ampi__Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to add financial line items to a project activity.</description>
    <label>Activity</label>
    <referenceTo>ampi__Activity__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Amount_Actual__c.field-meta.xml
<CustomField>
    <fullName>ampi__Amount_Actual__c</fullName>
    <description>Currency field to track the actual expenditure/revenue for a financial record.</description>
    <label>Amount Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Amount_Planned__c.field-meta.xml
<CustomField>
    <fullName>ampi__Amount_Planned__c</fullName>
    <description>Currency field to track the planned amount to be spent/earned for a financial record.</description>
    <label>Amount Planned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Budget__c.field-meta.xml
<CustomField>
    <fullName>ampi__Budget__c</fullName>
    <description>Master-detail field to relate a financial record to a budget record.</description>
    <label>Budget</label>
    <referenceTo>ampi__Budget__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Category__c.field-meta.xml
<CustomField>
    <fullName>ampi__Category__c</fullName>
    <description>This picklist field is for categorizing Financial records based on their purpose. This field is unrestricted and can be modified by subscribers.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Result based</fullName>
            </value>
            <value>
                <fullName>9 PSCI</fullName>
            </value>
            <value>
                <fullName>Overarching</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>ADV</fullName>
            </value>
            <value>
                <fullName>SIL</fullName>
            </value>
            <value>
                <fullName>FLC</fullName>
            </value>
            <value>
                <fullName>DFE</fullName>
            </value>
            <value>
                <fullName>CFE</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>HA</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>ECD</fullName>
            </value>
            <value>
                <fullName>EDU</fullName>
            </value>
            <value>
                <fullName>EET</fullName>
            </value>
            <value>
                <fullName>ER</fullName>
            </value>
            <value>
                <fullName>FFC</fullName>
            </value>
            <value>
                <fullName>FS</fullName>
            </value>
            <value>
                <fullName>HPP</fullName>
            </value>
            <value>
                <fullName>MED</fullName>
            </value>
            <value>
                <fullName>OA</fullName>
            </value>
            <value>
                <fullName>OAC</fullName>
            </value>
            <value>
                <fullName>SGH</fullName>
            </value>
            <value>
                <fullName>SFC</fullName>
            </value>
            <value>
                <fullName>YC</fullName>
            </value>
            <value>
                <fullName>3 CMG CI</fullName>
            </value>
            <value>
                <fullName>3 FD CI</fullName>
            </value>
            <value>
                <fullName>2 IF4C COR</fullName>
            </value>
            <value>
                <fullName>2 IF4C D2D</fullName>
            </value>
            <value>
                <fullName>2 IF4C DB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Period__c</fullName>
    <description>Master-detail field to relate a financial record to a reporting period.</description>
    <label>Reporting Period</label>
    <referenceTo>ampi__Reporting_Period__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/PU__c.field-meta.xml
<CustomField>
    <fullName>PU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PU</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>P&amp;PU must be Programme Unit or NMU</errorMessage>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>Programme Unit, National Management Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/ampi__Project_Indicator__c.object-meta.xml
<CustomObject>
    <description>Junction linking a catalog indicator to a project</description>
    <label>Project Indicator</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Project Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Project this project indicator belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Project_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/ampi__Reporting_Period__c.object-meta.xml
<CustomObject>
    <description>A period of time for which a project&apos;s targets must be set and results reported</description>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Reporting Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Label__c.field-meta.xml
<CustomField>
    <fullName>ampi__Label__c</fullName>
    <description>Text field to specify the human readable name of reporting period.</description>
    <inlineHelpText>Create a name for your reporting period that matches the duration of time that results are reported on. For example, for annual data, enter the “year name”. For quarterly data, enter “Q1 [year name]”.</inlineHelpText>
    <label>Reporting Period Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Project to which a Reporting Period belongs</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Reporting Periods</relationshipLabel>
    <relationshipName>Project_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Report_Type__c.field-meta.xml
<CustomField>
    <fullName>ampi__Report_Type__c</fullName>
    <description>Duration of time that results are reported on. This field determines what Project Indicator Reporting Period junction records are generated by the Reporting Period triggers.</description>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Life of Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Reporting_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Period_Start_Date__c</fullName>
    <description>Date field to store the start date for this reporting period. This field determines the secondary order in which Reporting Periods are displayed in the dropdown picklist on SetTargets and AddResults.</description>
    <label>Reporting Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monitoring_Period_Config__mdt/Monitoring_Period_Config__mdt.object-meta.xml
<CustomObject>
    <label>Monitoring Period Config</label>
    <pluralLabel>Monitoring Periods Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Monitoring_Period_Config__mdt/fields/Number_MP_Generated_Projects__c.field-meta.xml
<CustomField>
    <fullName>Number_MP_Generated_Projects__c</fullName>
    <defaultValue>(0)</defaultValue>
    <label>Number MP Generated Projects</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExtraCreateObjects.cls
public without sharing class ExtraCreateObjects {    
    public static ampi__Financial__c createFinancialWithPU(String name, String activityId, String category, String budgetId, String reportingPeriodId, boolean isReadonly, String puId) {
			ampi__Financial__c newFinancial = new ampi__Financial__c();
            newFinancial.Name = name;
            if (activityId != '') {
                newFinancial.ampi__Activity__c = activityId;
            }
        	newFinancial.ampi__Category__c = category;
            newFinancial.ampi__Budget__c = budgetId;
            newFinancial.ampi__Reporting_Period__c = reportingPeriodId;
            newFinancial.ampi__Amount_Planned__c = 0;
            newFinancial.ampi__Amount_Actual__c = 0;
            newFinancial.Is_ReadOnly__c = isReadonly;
            newFinancial.PU__c = puId;
            INSERT newFinancial;
        	RETURN newFinancial;
    }
    
    public static void createMonitoringPeriodByProjectAndMonth(Id projectId) {
        String reportType = 'Monthly';
        Integer count = 0, reportingPeriodCounts = 0;
        System.debug('####createMonitoringPeriodByProjectAndMonth 1:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
            
        List<ampi__Reporting_Period__c> reportingPeriods = [SELECT ampi__Reporting_Period_Start_Date__c FROM ampi__Reporting_Period__c 
                                                            WHERE ampi__Project__c =: projectId AND 
                                                            	  CALENDAR_YEAR(ampi__Reporting_Period_Start_Date__c) =: Date.today().year() AND 
																  ampi__Report_Type__c = 'Monthly' ORDER BY ampi__Reporting_Period_Start_Date__c  ASC];
                    
        System.debug('####createMonitoringPeriodByProjectAndMonth 2:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        if (reportingPeriods.size() < 12) {
            	List<Monitoring_Period_Config__mdt> mpconf = Monitoring_Period_Config__mdt.getAll().values();
                Integer monthsToInsert = 0;
            
            	if (mpconf.size() > 0) {
                    monthsToInsert = Integer.ValueOf(mpconf[0].Number_MP_Generated_Projects__c);
                }
            
                //List<ampi__Reporting_Period__c> rps = new List<ampi__Reporting_Period__c>();
                for(Integer i = 1; i <= 12; i++) {
                    try {
                        reportingPeriodCounts = 0;
                        Date initialDate = Date.newinstance(Date.today().year(), i, 1); 
                        Date endDate = initialDate.addMonths(1).addDays(-1);
                        for (ampi__Reporting_Period__c rp : reportingPeriods) {
                            if (initialDate == rp.ampi__Reporting_Period_Start_Date__c) {
                            	reportingPeriodCounts++;
                            }
                        }
                        
                        if (reportingPeriodCounts == 0 && count < monthsToInsert) {
                            ampi__Reporting_Period__c reportingPeriod = new ampi__Reporting_Period__c();
                            reportingPeriod.ampi__Label__c = initialDate.year() + '-' + (initialDate.month() + '').leftPad(2,'0');
                            reportingPeriod.ampi__Report_Type__c = reportType;
                            reportingPeriod.ampi__Reporting_Period_Start_Date__c = initialDate;
                            reportingPeriod.ampi__Reporting_Period_End_Date__c = endDate;//reportingPeriod.ampi__Reporting_Period_Start_Date__c.addYears(durationInYears);
                            reportingPeriod.ampi__Project__c = projectId;
                            INSERT reportingPeriod;
                            System.debug('####createMonitoringPeriodByProjectAndMonth 3:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
                            count++;
                        }
                    } catch(Exception ex) {
                        System.debug('#### MP ex: Month ' + i + ':' + ex.getMessage());
                    }
                    //rps.add(reportingPeriod);
                }
                //INSERT rps;                		
            }        
   	}

    @AuraEnabled(cacheable=true)
    public static String CheckIfCanUpdateResultByProject(String projectId) {
            User currentUser = [SELECT id,Contact.AccountId,Name,Profile.UserLicense.Name, Alias FROM User WHERE Id =:UserInfo.getUserId() LIMIT 1];
            List<string> roles = ExtraCreateObjects.GetRolesAllowedToUpdateResults();
            List<ampi__project_indicator__c> pi = [SELECT id, ampi__project__c, ampi__project__r.RecordType.Name, ampi__project__r.SOS_Implementing_Organisation__c FROM ampi__project_indicator__c WHERE ampi__project__c =: projectId];                    
            
            if (pi.size() > 0) {
                System.debug('####pi[0].ampi__project__c: ' + pi[0].ampi__project__c);
                System.debug('####currentUser.Id: ' + currentUser.Id);
                System.debug('####roles: ' + roles);
                System.debug('####pi[0].ampi__project__r.RecordType.Name: ' + pi[0].ampi__project__r.RecordType.Name);                        
                if (pi[0].ampi__project__r.RecordType.Name == 'Shadow Project') {
                    if (currentUser.Contact.AccountId != pi[0].ampi__project__r.SOS_Implementing_Organisation__c) {
                        return 'INSUFFICIENT_ACCESS_OR_READONLY error for Contact "Organisation" field is different to the project "SOS Implemetation Organisation" field.';
                                // res.addError('INSUFFICIENT_ACCESS_OR_READONLY on "ampi__result__c" row Id:' + res.Id);                                
                    }
                } else {
                    List<Team_member__c> tms = [SELECT Id FROM Team_member__c WHERE Project__c =: pi[0].ampi__project__c AND User__c =: currentUser.Id AND Role__c IN : roles AND Active__c = true];
                    System.debug('####tms.size(): ' + tms.size());        
                    if(tms.size() == 0) {
                        return 'INSUFFICIENT_ACCESS_OR_READONLY error for User is not registered as a "Team member" on the project as Project Contributor or Youthcan roles.';
                        // res.addError('INSUFFICIENT_ACCESS_OR_READONLY on "ampi__result__c" row Id:' + res.Id);
                    }
                }                        
            }
            return ''; 
    }  

    public static String CheckIfCanUpdateResultByProjectIndicator(User currentUser, String project_Indicator, List<string> roles) {
            List<ampi__project_indicator__c> pi = [SELECT id, ampi__project__c, ampi__project__r.RecordType.Name, ampi__project__r.SOS_Implementing_Organisation__c FROM ampi__project_indicator__c WHERE Id =: project_Indicator];                    
            if (pi.size() > 0) {
                System.debug('####pi[0].ampi__project__c: ' + pi[0].ampi__project__c);
                System.debug('####currentUser.Id: ' + currentUser.Id);
                System.debug('####roles: ' + roles);
                System.debug('####pi[0].ampi__project__r.RecordType.Name: ' + pi[0].ampi__project__r.RecordType.Name);                        
                if (pi[0].ampi__project__r.RecordType.Name == 'Shadow Project') {
                    if (currentUser.Contact.AccountId != pi[0].ampi__project__r.SOS_Implementing_Organisation__c) {
                        return 'INSUFFICIENT_ACCESS_OR_READONLY error for Contact "Organisation" field is different to the project "SOS Implemetation Organisation" field.';
                                // res.addError('INSUFFICIENT_ACCESS_OR_READONLY on "ampi__result__c" row Id:' + res.Id);                                
                    }
                } else {
                    List<Team_member__c> tms = [SELECT Id FROM Team_member__c WHERE Project__c =: pi[0].ampi__project__c AND User__c =: currentUser.Id AND Role__c IN : roles AND Active__c = true];
                    System.debug('####tms.size(): ' + tms.size());        
                    if(tms.size() == 0) {
                        return 'INSUFFICIENT_ACCESS_OR_READONLY error for User is not registered as a "Team member" on the project as Project Contributor or Youthcan roles.';
                        // res.addError('INSUFFICIENT_ACCESS_OR_READONLY on "ampi__result__c" row Id:' + res.Id);
                    }
                }                        
            }
            return ''; 
    }  

    public static List<string> GetRolesAllowedToUpdateResults() {
        return new List<string> {'YouthCan! Global MEL Advisor','YouthCan! Global Project Manager','YouthCan! Key Account Manager','YouthCan! Regional Coordinator','YouthCan! Coordinator','YouthCan! Partner','Project Contributor'};
    }
}