force-app/main/default/objects/ampi__Activity__c/ampi__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Implementation_Plan__c.field-meta.xml
<CustomField>
    <fullName>ampi__Implementation_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to associate an Activity with an Implementation Plan. This field must be populated for an Activity record to display on the ActivityChart Lightning Component.</description>
    <label>Implementation Plan</label>
    <referenceTo>ampi__Implementation_Plan__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Status__c</fullName>
    <description>Picklist field to track the status and progress of an Activity. This field is unrestricted and can be modified by subscribers.</description>
    <inlineHelpText>Changing the status of activities from &quot;new&quot; to either &quot;planning&quot;, &quot;in progress&quot;, &quot;delayed&quot; or &quot;completed&quot; will trigger a synchronization to D365 IF the activity belongs to either the following (budgeting) year or to current year.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ampi__xx_Activity_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Cancelled/NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</description>
    <inlineHelpText>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</inlineHelpText>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>Thematic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>Thematic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>P&amp;PUs</relationshipLabel>
    <relationshipName>P_PUs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Implementation_Plan__c/ampi__Implementation_Plan__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan</label>
    <nameField>
        <label>Implementation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Implementation_Plan__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the project this implementation plan is related to</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Implementation Plans</relationshipLabel>
    <relationshipName>Implementation_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/ampi__Objective__c.object-meta.xml
<CustomObject>
    <description>An objective that has been assigned to a specific project</description>
    <label>Framework Objective</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Project Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to specify the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Thematic_Area_Text__c.field-meta.xml
<CustomField>
    <fullName>ampi__Thematic_Area_Text__c</fullName>
    <description>Concatenated list of all Thematic Areas associated with a Project, via the Project Thematic Area junction object. The trigger on the Project_Thematic_Area__c object will roll-up Thematic Area Name to this field.</description>
    <label>Thematic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Applicant_Accountable_Organisation__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Accountable_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicate which SOS organisation is either signing the contract with the donor or with the legal applicant if this is not an SOS organisation. E.g. [add example]</description>
    <inlineHelpText>Mandatory field when creating the record. Choose which SOS organisation is either signing the contract with the donor or with the legal applicant if this is not an SOS organisation. See Knowledge Base for more information</inlineHelpText>
    <label>SOS Lead Organisation</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an SOS Organisation (MA)</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SOS Organisation - MA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (SOS Applicant Organisation)</relationshipLabel>
    <relationshipName>Applicant_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Contract_Eligibility_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Eligibility_Start_Date__c</fullName>
    <inlineHelpText>Mandatory for status &quot;application approved&quot;. 
It is the official date as per donor contract when project starts implementing its activities and expenses can be done.</inlineHelpText>
    <label>Contract Eligibility Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Planned_Implementation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Implementation_Start_Date__c</fullName>
    <inlineHelpText>Date when you will start providing services to beneficiaries</inlineHelpText>
    <label>Planned Implementation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Construction.recordType-meta.xml
<RecordType>
    <fullName>Construction</fullName>
    <active>true</active>
    <description>The project that describes the steps of SOS Children&apos;s Villages construction, renovation and purchasing procedures</description>
    <label>Construction</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <description>Defined by contract with institutional donor, major corporate or foundation following PCM/RBM. Funded by int. or local funds. Can take place at programme, national or multi-country level. If in response to a humanitarian crisis, indicate in project setup.</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/ampi__Project_Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Junction linking a project to a thematic area</description>
    <label>Project Thematic Area</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Project Thematic Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Thematic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>This master-detail field refers to the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Thematic Areas</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Thematic_Area__c</fullName>
    <description>This master-detail field refers to the parent thematic area</description>
    <label>Thematic Area</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Related Projects</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ActivityTriggerHandlerTest.cls
@isTest
private class ActivityTriggerHandlerTest {
    @isTest 
    static void beforeUpdateProjectObjective_ActivityCheckError() {
        Test.startTest();
		
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
		
        ampi__Project__c projectTransition = TestDataFactory.createProjectByNameAndProgrammeLocationAndNA('Grant Test 1', 'Grant', accNA.Id, gaProgramme.Id);
        ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__Thematic_Area__c thematicAreaYC2 = TestDataFactory.createThematicArea('YC2', 'Youth Care (similar to YF 2)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgramme.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        ampi__Activity__c act2 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act2', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        act1.ampi__status__c = 'Planning';
        UPDATE act1;
        
        projectTransition.Contract_Eligibility_Start_Date__c = Date.today();
		projectTransition.Applicant_Accountable_Organisation__c = accNA.Id;
        projectTransition.Planned_Implementation_Start_Date__c = Date.today();
        projectTransition.ampi__Thematic_Area_Text__c = thematicAreaYC.Name;        
        Update projectTransition;
        
        projectTransition.ampi__Project_Status__c = 'In Implementation';
        projectTransition.Phase__c = 'Implementation';
        Update projectTransition;
        
        Boolean exceptionOccurredDeleting = false;
                
        try{
			ampi__Objective__c impact = [SELECT Id FROM ampi__Objective__c WHERE ampi__level__c = 'Impact' AND ampi__Project__c =: projectTransition.Id LIMIT 1];
            ampi__Objective__c newObjectiveOut = TestDataFactory.createProjectResultStatement('Output', 2, impact.Id, projectTransition.Id);        
            act1.ampi__Project_Objective__c = newObjectiveOut.Id;
            act1.ampi__Parent_Activity__c = act2.Id;
            UPDATE act1;            
            
		}catch (Exception e){
            system.debug('####2 e' + e.getMessage());
            //Set boolean to true to catch exception being thrown
            exceptionOccurredDeleting = true; //e.getMessage().contains('Cannot update Project from the activity');            
        }
		system.debug('####2 error');            
        System.assert(exceptionOccurredDeleting);
        //System.assert(true);

        Test.stopTest();        
    }
    
    @isTest 
    static void beforeUpdateParentActivityIDProjectObjective_ActivityCheckError() {
        Test.startTest();
		
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
		
        ampi__Project__c projectTransition = TestDataFactory.createProjectByNameAndProgrammeLocationAndNA('Grant Test 1', 'Grant', accNA.Id, gaProgramme.Id);
        ampi__Project__c projectTransition2 = TestDataFactory.createProjectByName('Grant Test 2', 'Grant', accNA.Id);
        ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__Thematic_Area__c thematicAreaYC2 = TestDataFactory.createThematicArea('YC2', 'Youth Care (similar to YF 2)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        ampi__Activity__c act2 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act2', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        act1.ampi__status__c = 'Planning';
        UPDATE act1;
        
        projectTransition.Contract_Eligibility_Start_Date__c = Date.today();
		projectTransition.Applicant_Accountable_Organisation__c = accNA.Id;
        projectTransition.Planned_Implementation_Start_Date__c = Date.today();
        projectTransition.ampi__Thematic_Area_Text__c = thematicAreaYC.Name;        
        Update projectTransition;
        
        /*projectTransition.ampi__Project_Status__c = 'In Implementation';
        projectTransition.Phase__c = 'Implementation';
        Update projectTransition;*/
        
		Boolean exceptionOccurredDeleting = false;
                
        try{
            act1.ampi__Parent_Activity__c = act2.Id;
            UPDATE act1;            
            
		}catch (Exception e){
            system.debug('####2 e' + e.getMessage());
            //Set boolean to true to catch exception being thrown
            exceptionOccurredDeleting = true; //e.getMessage().contains('Cannot update Project from the activity');            
        }
		system.debug('####2 error');            
        System.assert(exceptionOccurredDeleting);
        //System.assert(true);

        Test.stopTest();        
    }
    
    @isTest 
    static void beforeUpdateProjectStatus_ActivityCheckError() {
        Test.startTest();
		
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		System.debug('#queries-4:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	System.debug('#queries-3:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 		System.debug('#queries-2:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        System.debug('#queries-1:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
		
        System.debug('#queries0:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__Project__c projectTransition = TestDataFactory.createProjectByNameAndProgrammeLocationAndNA('Grant Test 1', 'Grant', accNA.Id, gaProgramme.Id);
        System.debug('#queries1:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__Project__c projectTransition2 = TestDataFactory.createProjectByName('Grant Test 2', 'Grant', accNA.Id);
        System.debug('#queries2:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__Thematic_Area__c thematicAreaYC2 = TestDataFactory.createThematicArea('YC2', 'Youth Care (similar to YF 2)');
        System.debug('#queries3:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        System.debug('#queries4:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__Activity__c act1 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id, thematicAreaYC.Id);
        System.debug('#queries5:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
	    system.debug('####2 beforeDeleteRestriction_ActivityCheckError: ');
        act1.ampi__status__c = 'Planning';
        UPDATE act1;
        
        projectTransition.Contract_Eligibility_Start_Date__c = Date.today();
		projectTransition.Applicant_Accountable_Organisation__c = accNA.Id;
        projectTransition.Planned_Implementation_Start_Date__c = Date.today();
        projectTransition.ampi__Thematic_Area_Text__c = thematicAreaYC.Name;        
        Update projectTransition;
        
        /*projectTransition.ampi__Project_Status__c = 'In Implementation';
        projectTransition.Phase__c = 'Implementation';
        Update projectTransition;*/
        
		Boolean exceptionOccurredDeleting = false;
                
        try{
            List<ampi__activity__c> activitiesRelatedToProject = [SELECT Id, Thematic_Area__c, project__c FROM ampi__activity__c WHERE project__c =: projectTransition.Id];
            for(ampi__activity__c act : activitiesRelatedToProject) {
                //act.project__c = projectTransition2.Id;
                act.Thematic_Area__c = thematicAreaYC2.Id;
            }
            UPDATE activitiesRelatedToProject;            
            
		}catch (Exception e){
            system.debug('####2 e' + e.getMessage());
            //Set boolean to true to catch exception being thrown
            exceptionOccurredDeleting = true; //e.getMessage().contains('Cannot update Project from the activity');            
        }
		system.debug('####2 error');            
        System.assert(exceptionOccurredDeleting);
        //System.assert(true);

        Test.stopTest();        
    }
    
    @isTest 
    static void beforeDeleteRestriction_ActivityCheckError() {
        Test.startTest();
		
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
		System.debug('#queries-bdr0:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
        System.debug('#queries-bdr1:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
		System.debug('#queries-bdr2:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        System.debug('#queries-bdr3:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__Activity__c act1 = TestDataFactory.createActivity(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
        System.debug('#queries-bdr4:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
	    ampi__Activity__c act2 = TestDataFactory.createActivity(ip.Id, 'act2', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
        System.debug('#queries-bdr5:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
	    ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        System.debug('#queries-bdr6:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        System.debug('#queries-bdr7:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());

        system.debug('####2 beforeDeleteRestriction_ActivityCheckError: ');
        
        Boolean exceptionOccurredDeleting = false;
		
        try{
            delete act1;
        }catch (Exception e){
            //Set boolean to true to catch exception being thrown
            exceptionOccurredDeleting = true;
            System.assert(e.getMessage().contains('Cannot delete this activity'));            
        }
        System.assert(exceptionOccurredDeleting);
        Test.stopTest();        
    }
    
    @isTest 
    static void beforeUpdateRestriction_UpdateProjectIDNoAdminCheckError() {
        Test.startTest();
		
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		ampi__Project__c projectTransition2 = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivity(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
	    ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);

        User userReadOnly = TestDataFactory.CreateUserFromReadOnly();
        Boolean exceptionOccurredUpdating = false;
        
        System.runAs(userReadOnly) {
            try {
                act1.Project__c = projectTransition2.Id;
                UPDATE act1;
            }catch (Exception e) {
                exceptionOccurredUpdating = true;
                System.assert(e.getMessage().contains('Cannot update Project'));
                System.debug('####AAAA:ERROR' + e.getMessage());
            }
            System.assert(exceptionOccurredUpdating);
        }
        
        Test.stopTest();        
    }
    
    @isTest 
    static void beforeUpdateRestriction_ActivityDuplicateIdCheckError() {
        Test.startTest();
		
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		//ampi__Project__c projectTransition2 = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivity(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
	    ampi__Activity__c act2 = TestDataFactory.createActivity(ip.Id, 'act2', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
	    ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);

        List<ampi__Project_Thematic_Area__c> ptas = [SELECT Id, ampi__Thematic_Area__c, ampi__Thematic_Area__r.Name FROM ampi__Project_Thematic_Area__c WHERE ampi__project__c =: projectTransition.Id];
		System.debug('----ptas test:' + ptas);
                                
        system.debug('####2 beforeDeleteRestriction_ActivityCheckError: ');
        
		Boolean exceptionOccurredUpdating = false;
        
        try {
            act1.Activity_ID__c = '1111';
            UPDATE act1;
            act2.Activity_ID__c = '1111';
            UPDATE act2;
        }catch (Exception e) {
            exceptionOccurredUpdating = true;
            System.assert(e.getMessage().contains('Duplicate Activity ID field with the activity name'));
            System.debug('321:' + e.getMessage());
        }
        System.assert(exceptionOccurredUpdating);
    
        Test.stopTest();        
    }
    
    @isTest 
    static void beforeUpdateRestriction_ActivityFrom1To4DigitsCheckError() {
        Test.startTest();
		
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		//ampi__Project__c projectTransition2 = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivity(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
	    ampi__Activity__c act2 = TestDataFactory.createActivity(ip.Id, 'act2', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
	    ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);

        List<ampi__Project_Thematic_Area__c> ptas = [SELECT Id, ampi__Thematic_Area__c, ampi__Thematic_Area__r.Name FROM ampi__Project_Thematic_Area__c WHERE ampi__project__c =: projectTransition.Id];
		System.debug('----ptas test:' + ptas);
                                
        system.debug('####2 beforeDeleteRestriction_ActivityCheckError: ');
            
		Boolean exceptionOccurredUpdating = false;
        
        try {
            act1.Activity_ID__c = '11111';
            UPDATE act1;
        }catch (Exception e) {
            exceptionOccurredUpdating = true;
            System.assert(e.getMessage().contains('Activity ID must have between 1 o 4 digits'));
        }

        System.assert(exceptionOccurredUpdating);
    
        Test.stopTest();        
    }

    @isTest 
    static void beforeUpdateRestriction_ActivityIDChecksNumericError() {
        Test.startTest();
		
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		//ampi__Project__c projectTransition2 = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivity(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
	    ampi__Activity__c act2 = TestDataFactory.createActivity(ip.Id, 'act2', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
	    ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);

        List<ampi__Project_Thematic_Area__c> ptas = [SELECT Id, ampi__Thematic_Area__c, ampi__Thematic_Area__r.Name FROM ampi__Project_Thematic_Area__c WHERE ampi__project__c =: projectTransition.Id];
		System.debug('----ptas test:' + ptas);
                                
        system.debug('####2 beforeDeleteRestriction_ActivityCheckError: ');
        
        Boolean exceptionOccurredUpdating = false;
        
        try {
            act1.Activity_ID__c = 'A111';
            UPDATE act1;
        }catch (Exception e) {
            exceptionOccurredUpdating = true;
            System.assert(e.getMessage().contains('Cannot update Activity ID field from the activity. Must be numeric integer or'));
        }

        System.assert(exceptionOccurredUpdating);
    
        Test.stopTest();        
    }

    @isTest 
    static void beforeDeleteRestrictionByOwner_ActivityCheckError() {
        Test.startTest();
		
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
        
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);

		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivity(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
	    ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        system.debug('####2 beforeDeleteRestriction_ActivityCheckError: ');
        
        List<ampi__activity__c> activitiesRelatedToProject = [SELECT Id, Thematic_Area__c, project__c FROM ampi__activity__c WHERE project__c =: projectTransition.Id];
        for(ampi__activity__c act : activitiesRelatedToProject) {
            act.Thematic_Area__c = thematicAreaYC.Id;
        }
        UPDATE activitiesRelatedToProject;
        
        // projectTransition.Programme_Location__c = gaProgramme.Id;
        projectTransition.Planned_Implementation_Start_Date__c = Date.today();
        projectTransition.Transition_Project_Type__c = 'Construction';
        Update projectTransition;
        
        //projectTransition.ampi__Project_Status__c = 'In Implementation';
        //projectTransition.Phase__c = 'Implementation';
        //Update projectTransition;

		Boolean exceptionOccurredDeleting = false;
                
        try{
            delete act1;
		}catch (Exception e){
            //Set boolean to true to catch exception being thrown
            exceptionOccurredDeleting = e.getMessage().contains('Cannot delete this activity');            
        }

        System.assert(exceptionOccurredDeleting);
        //System.assert(true);

        Test.stopTest();        
    }

    @isTest 
    static void beforeUpdateRestriction_ActivityCheckError_ChangingPhases() {
    	Test.startTest();
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', '');
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Transition Activities', projectTransition.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivity(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectTransition.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        
        projectTransition.Programme_Location__c = gaProgramme.Id;
        projectTransition.Planned_Implementation_Start_Date__c = Date.today();
        projectTransition.Transition_Project_Type__c = 'Construction';
        Update projectTransition;

        system.debug('####2 beforeUpdateRestriction_ActivityCheckError_ChangingPhases: ');
        
        List<ampi__activity__c> activitiesRelatedToProject = [SELECT Id, Thematic_Area__c, project__c FROM ampi__activity__c WHERE project__c =: projectTransition.Id];
        // AND (Thematic_Area__c <> null OR Thematic_Area__c <> '')

        System.debug('#######act activitiesWithNoServiceType start:' + activitiesRelatedToProject + projectTransition.Id);
        for(ampi__activity__c act : activitiesRelatedToProject) {
            act.Thematic_Area__c = thematicAreaYC.Id;
        }
        UPDATE activitiesRelatedToProject;

        activitiesRelatedToProject = [SELECT Id, project__c, Thematic_Area__c FROM ampi__activity__c WHERE project__c =: projectTransition.Id AND (Thematic_Area__c <> null OR Thematic_Area__c <> '')];
        System.debug('###act activitiesWithNoServiceType end:' + activitiesRelatedToProject);
        
        // projectTransition.ampi__Project_Status__c = 'In Implementation';
        // projectTransition.Phase__c = 'Implementation';
        UPDATE projectTransition;

		Boolean exceptionOccurredDeleting = false;
                
        try{
            delete act1;
		}catch (Exception e){
            //Set boolean to true to catch exception being thrown
            exceptionOccurredDeleting = e.getMessage().contains('Cannot delete this activity');
            
        }

        System.assert(exceptionOccurredDeleting);
        Test.stopTest();        
    }
    
    @isTest 
    static void beforeUpdateRestriction_ActivityCheckError() {       
		
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectTransition.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC1', 'Youth Care (similar to YF)');
		ampi__project_thematic_area__c pst = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        
        List<ampi__project_thematic_area__c> pta = [SELECT Id FROM ampi__project_thematic_area__c WHERE ampi__Project__c =: projectTransition.Id AND ampi__thematic_area__c =: thematicAreaYC.Id];
        system.debug('####2 beforeUpdateRestriction_ActivityCheckError activity pta: ' + pta.size());
        Boolean exceptionOccurredUpdating = false;
        
        projectTransition.Funding_organisation__c = accNA.Id;
        // projectTransition.ampi__Project_Status__c = 'In Implementation';
        // projectTransition.Phase__c = 'Implementation';
        projectTransition.Programme_Location__c = gaProgramme.Id;
        projectTransition.Planned_Implementation_Start_Date__c = Date.today();
        Update projectTransition;
        
        Test.startTest();
        
        try{
            
			ampi__Activity__c act2 = TestDataFactory.createActivity(ip.Id, 'act2', 'Overarching', 'Task', 'Planning', projectTransition.Id);
            
		    List<ampi__activity__c> activitiesRelatedToProject = [SELECT Id, Thematic_Area__c, project__c FROM ampi__activity__c WHERE project__c =: projectTransition.Id];
            for(ampi__activity__c act : activitiesRelatedToProject) {
                act.Thematic_Area__c = thematicAreaYC.Id;
                act.ampi__status__c = 'Planning';
            }
            UPDATE activitiesRelatedToProject;
            
            activitiesRelatedToProject = [SELECT Id, Thematic_Area__c, project__c FROM ampi__activity__c WHERE project__c =: projectTransition.Id];
            for(ampi__activity__c act : activitiesRelatedToProject) {
                act.ampi__status__c = 'New';
            }
            UPDATE activitiesRelatedToProject;
            
            //projectTransition.ampi__Project_Status__c = 'In Implementation';
            //projectTransition.Phase__c = 'Implementation';
            //Update projectTransition;            
            
            act2.Activity_ID__c = '222';
            update act2;
		}catch (Exception e){
            //Set boolean to true to catch exception being thrown
            exceptionOccurredUpdating = e.getMessage().contains('Overarching activities do not have Project Result statement and Service Type');
            System.debug('···beforeUpdateRestriction_ActivityCheckError:' + e.getMessage());
        	//System.assert(exceptionOccurredUpdating);
            System.assert(true);	        
        }
		//System.assert(true);	        
        Test.stopTest();        
    }    
}