force-app/main/default/objects/ampi__Activity__c/ampi__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Status__c</fullName>
    <description>Picklist field to track the status and progress of an Activity. This field is unrestricted and can be modified by subscribers.</description>
    <inlineHelpText>Changing the status of activities from &quot;new&quot; to either &quot;planning&quot;, &quot;in progress&quot;, &quot;delayed&quot; or &quot;completed&quot; will trigger a synchronization to D365 IF the activity belongs to either the following (budgeting) year or to current year.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ampi__xx_Activity_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Cancelled/NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</description>
    <inlineHelpText>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</inlineHelpText>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Base_URL__c</fullName>
    <formula>LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))</formula>
    <label>Base URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Project_ID_Text__c.field-meta.xml
<CustomField>
    <fullName>Project_ID_Text__c</fullName>
    <formula>CASE(RecordType.Name,
&quot;Standard&quot;, &quot;S&quot;,
&quot;Emergency Response&quot;, &quot;E&quot;,
&quot;Funding Opportunity&quot;, &quot;F&quot;,
&quot;Humanitarian&quot;, &quot;H&quot;,
&quot;Grant&quot;, &quot;G&quot;,
&quot;Legacy&quot;, &quot;L&quot;,
&quot;End of Involvement&quot;, &quot;X&quot;,
&quot;Construction&quot;, &quot;C&quot;,
&quot;&quot;)
&amp; IF(DATEVALUE(CreatedDate) &gt; DATEVALUE(&quot;2019-12-31&quot;),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2),
IF(RecordType.Name = &quot;Grant&quot;,
RIGHT(TEXT(YEAR(Start_Identification__c)), 2),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2)
)
)
&amp; &quot;-&quot;
&amp; Project_Autonumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Project ID is generated by the system..</inlineHelpText>
    <label>Project ID Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <label>Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Period_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Period_Identifier__c</fullName>
    <label>Period Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Related_Project__c.field-meta.xml
<CustomField>
    <fullName>Related_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectActivityNotificationBatch.cls
global class ProjectActivityNotificationBatch implements Database.Batchable<sObject> {
  private String query;
    
  /*
      //Execute Apex Jobs / Check on Setup => Environments => Jobs => Apex Jobs or Scheduled Jobs
	  //String sch = '0 ' + i + ' * * * ?'; i is the minute to run
      String sch = '0 1 0 28 * ?';
      ScheduledProjectActivityNotification sqrb = new ScheduledProjectActivityNotification();
      system.schedule('ScheduledProjectActivityNotification Monthly on 28th: ' + Date.today().Year() + '-' + Date.today().Month() + Date.today().Day(), sch, sqrb);
  */
    
  global ProjectActivityNotificationBatch (){
  }
    
  // The batch job starts
  global Database.Querylocator start(Database.BatchableContext bc){
    // String m = Date.today().Month() > 9 ? Date.today().Month() : '0' + Date.today().Month();
    // String d = Date.today().Day() > 9 ? Date.today().Day() : '0' + Date.today().Day();
    // String currentPeriod = Date.today().Year() + '-' + m + '-' + d;  
    // String query = 'SELECT Id, project__c, name, project__r.Base_URL__c , project__r.Project_ID_Text__c, project__r.Name, project__r.Link, project__r.owner.email FROM ampi__activity__c WHERE ampi__status__c = \'' + 'New'  + '\' AND project__r.ampi__project_status__c IN (\'' + 'In Implementation' + '\') AND project__r.owner.email <> NULL AND project__c NOT IN (SELECT Related_Project__c FROM Notification__c WHERE Period_Identifier__c = \'' + currentPeriod + '\') ORDER BY project__c, Name LIMIT 100';     
    String query = 'SELECT Id, project__c, name, project__r.Base_URL__c , project__r.Project_ID_Text__c, project__r.Name, project__r.ownerId, project__r.owner.email FROM ampi__activity__c WHERE ampi__status__c = \'' + 'New'  + '\' AND project__r.ampi__project_status__c IN (\'' + 'In Implementation' + '\') AND project__r.owner.email <> NULL ORDER BY project__c, Name';     
    System.debug('>>>> start ' + query);
    return Database.getQuerylocator(query);
  } 
  
  // The batch job executes and operates on one batch of records
  global void execute(Database.BatchableContext bc, List<sObject> scope){
  System.debug('>>>> execute ' + scope.size());
	List<ampi__activity__c > periods = new List<ampi__activity__c >();
	String emailTemplateName = 'Projects_In_Implementation_Notify_For_New_Activities_Monthly';
    
        List<EmailTemplate> lstEmailTemplates = [SELECT Id, HtmlValue, Body, Subject from EmailTemplate where DeveloperName =: emailTemplateName];
        System.debug('###notificationForPSAandIOR emailTemplateName: ' + emailTemplateName);
        System.debug('###notificationForPSAandIOR lstEmailTemplates: ' + lstEmailTemplates);
        System.debug('###notificationForPSAandIOR lstEmailTemplates.size(): ' + lstEmailTemplates.size());
                
        if (lstEmailTemplates.size() > 0) {
            String projectName = '';
            String projectID = '';
            String project = '';
            String ownerEmail = '';
            String ownerId = '';
            String projectLink = '';
            String activitiesFromProject = '';
            Set<String> owners = new Set<String>();
            for(sObject activity : scope) {    
                if ((String)activity.getSobject('project__r').get('Name') != projectName) {
                    if (projectName != '') {
                        owners = new Set<String> {ownerId};
                        sendNotification(projectName, owners, project);                                  
                        sendActivityEmailToOwners(lstEmailTemplates[0], ownerEmail, projectID, projectName, activitiesFromProject, projectLink);                        
                        insertNotification(project);
                    }
                    // activitiesFromProject = '<a href= "/ampi__activity__c/' + (String)activity.get('Id') + '">' + (String)activity.get('Name') + '</a><br>';
                    activitiesFromProject = (String)activity.get('Name');
                    project = (String)activity.get('project__c');
                    projectName = (String)activity.getSobject('project__r').get('Name');
                    projectLink = (String)activity.getSobject('project__r').get('Base_URL__c') + '/' + project;
                    projectID = (String)activity.getSobject('project__r').get('Project_ID_Text__c');
                    if (Test.isRunningTest()) {
                        ownerEmail = 'jorge.salcedo@sos-kd.org';
                        ownerId = UserInfo.getUserId();
                    } else {
                        ownerEmail = (String)activity.getSobject('project__r').getSobject('owner').get('email');                        
                        ownerId = (String)activity.getSobject('project__r').get('ownerId');                        
                    }
                }
                // activitiesFromProject += ' / ' + '<a href= "/ampi__activity__c/' + (String)activity.get('Id') + '">' + (String)activity.get('Name') + '</a><br>';
                activitiesFromProject += ' / ' + (String)activity.get('Name');
          	}
            
            if (scope.size() > 0 && ownerEmail <> '') {
              owners = new Set<String> {ownerId};
              sendNotification(projectName, owners, project);                                  
            	sendActivityEmailToOwners(lstEmailTemplates[0], ownerEmail, projectID, projectName, activitiesFromProject, projectLink);
              insertNotification(project);   
            }
    	}
  }
  
   global void sendNotification(String projectName, Set<String> recipientsIds, String targetId) {
        String title = 'Please Check Activities in status New From Projects';
        String message = 'Hello! Activities in status "New" from Project "' + projectName + '" which status is "In Implementation" are sent for revision.';
        notifyUsers(recipientsIds, targetId, title, message);
    }    
    
    global void notifyUsers(Set<String> recipientsIds, String targetId, String title, String message) {
            // Get the Id for our custom notification type
            CustomNotificationType notificationType = 
                [SELECT Id, DeveloperName 
                FROM CustomNotificationType 
                WHERE DeveloperName='notification_PSA_IOR' LIMIT 1];
            
            // Create a new custom notification
            Messaging.CustomNotification notification = new Messaging.CustomNotification();

            // Set the contents for the notification
            notification.setTitle(title);
            notification.setBody(message);

            // Set the notification type and target
            notification.setNotificationTypeId(notificationType.Id);
            notification.setTargetId(targetId);
            
            // Actually send the notification
            try {
                notification.send(recipientsIds);
            }
            catch (Exception e) {
                System.debug('Problem sending notification: ' + e.getMessage());
            }
    }

    global void insertNotification(String projectId) {
        // Notification__c pi = new Notification__c();
        // String m = Date.today().Month() > 9 ? '' + Date.today().Month() : '0' + Date.today().Month();
        // String d = Date.today().Day() > 9 ? '' + Date.today().Day() : '0' + Date.today().Day();
        // pi.Period_Identifier__c = Date.today().Year() + '-' + m + '-' + d;  
        // pi.Related_Project__c = projectId;
        // INSERT pi;
    }
    
    global void sendActivityEmailToOwners(EmailTemplate template, String ownerEmail, String projectID, String projectName, String activitiesFromProject, String projectLink) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTemplateId(template.Id);
        mail.setSaveAsActivity(false);
        mail.setTargetObjectId(userinfo.getUserId());// Any contact or User id of your record
                
        List<String> receivers = new List<String>();
        receivers.add(ownerEmail);
        String plainBody = template.Body;
                        
        plainBody = plainBody.replace('{!ampi__Project__c.Project_ID_Text__c}', ' ' + projectID);
        plainBody = plainBody.replace('{!ampi__Project__c.Name}', ' ' + projectName);
        plainBody = plainBody.replace('{!ampi__Project__c.Link}', ' ' + projectLink);
        plainBody = plainBody.replace('{!ampi__Project__c.Activities}', ' ' + activitiesFromProject);
        mail.setToAddresses(receivers);
        mail.setPlainTextBody(plainBody);
        Messaging.SendEmailResult[] resultMail = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        //INSERT LOG ACTIVITY SEND EMAIL RECORD
    }
  
  // The batch job finishes
  global void finish(Database.BatchableContext bc){
    AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :bc.getJobId()]; 
    System.debug('>>>> finish ' + job.Status);
  }
}