force-app/main/default/objects/ampi__Activity__c/ampi__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Implementation_Plan__c.field-meta.xml
<CustomField>
    <fullName>ampi__Implementation_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to associate an Activity with an Implementation Plan. This field must be populated for an Activity record to display on the ActivityChart Lightning Component.</description>
    <label>Implementation Plan</label>
    <referenceTo>ampi__Implementation_Plan__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</description>
    <inlineHelpText>DO NOT EDIT MANUALLY - This lookup field is set by automation as it is needed for the basis of a Sharing Set in order to share edit access with MA Portal users.</inlineHelpText>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Implementation_Plan__c/ampi__Implementation_Plan__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan</label>
    <nameField>
        <label>Implementation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Implementation_Plan__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the project this implementation plan is related to</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Implementation Plans</relationshipLabel>
    <relationshipName>Implementation_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Base_URL__c</fullName>
    <formula>LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))</formula>
    <label>Base URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Project_ID_Text__c.field-meta.xml
<CustomField>
    <fullName>Project_ID_Text__c</fullName>
    <formula>CASE(RecordType.Name,
&quot;Standard&quot;, &quot;S&quot;,
&quot;Emergency Response&quot;, &quot;E&quot;,
&quot;Funding Opportunity&quot;, &quot;F&quot;,
&quot;Humanitarian&quot;, &quot;H&quot;,
&quot;Grant&quot;, &quot;G&quot;,
&quot;Legacy&quot;, &quot;L&quot;,
&quot;End of Involvement&quot;, &quot;X&quot;,
&quot;Construction&quot;, &quot;C&quot;,
&quot;&quot;)
&amp; IF(DATEVALUE(CreatedDate) &gt; DATEVALUE(&quot;2019-12-31&quot;),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2),
IF(RecordType.Name = &quot;Grant&quot;,
RIGHT(TEXT(YEAR(Start_Identification__c)), 2),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2)
)
)
&amp; &quot;-&quot;
&amp; Project_Autonumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Project ID is generated by the system..</inlineHelpText>
    <label>Project ID Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ScheduledProjectActivityNotificationTest.cls
@isTest
private class ScheduledProjectActivityNotificationTest {
	@isTest
    static void executeBatch_GeneratingExternal() {
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('New Programme Unit based on Callao', gaProgramme.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
            
        ampi__Implementation_Plan__c schedules = TestDataFactory.createActivitySchedule('ASCH', projectStandard.Id);
        String scheduleId = schedules.Id;
        
        ampi__Activity__c a1 = TestDataFactory.createActivity(scheduleId, 'Activity 1', 'Overarching', 'Task', 'New', projectStandard.Id);
        ampi__Activity__c a2 = TestDataFactory.createActivity(scheduleId, 'Activity 2', 'Overarching', 'Task', 'New', projectStandard.Id);
        ampi__Activity__c a3 = TestDataFactory.createActivity(scheduleId, 'Activity 3', 'Overarching', 'Task', 'New', projectStandard.Id);
             
        Test.startTest();
        List<ampi__activity__c> activities = [SELECT Id, project__c, name, project__r.Base_URL__c , project__r.Project_ID_Text__c, project__r.Name, project__r.ownerId, project__r.owner.email FROM ampi__activity__c ORDER BY project__c, Name];     
        System.debug('####activities:' + activities);
        //project__r.ampi__project_status__c IN ('In Implementation') AND
		(new ProjectActivityNotificationBatch()).execute(null, activities);    
        
        //String sch = '0 ' + i + ' * * * ?'; i is the minute to run
      	String sch = '0 1 0 28 * ?';
      	ScheduledProjectActivityNotification sqrb = new ScheduledProjectActivityNotification();
      	system.schedule('ScheduledProjectActivityNotification Monthly on 28th: ' + Date.today().Year() + '-' + Date.today().Month() + Date.today().Day(), sch, sqrb);
        
        Test.stopTest();

        System.assert(true);        
    }
}