force-app/main/default/objects/ampi__Activity__c/ampi__Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Implementation_Plan__c.field-meta.xml
<CustomField>
    <fullName>ampi__Implementation_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to associate an Activity with an Implementation Plan. This field must be populated for an Activity record to display on the ActivityChart Lightning Component.</description>
    <label>Implementation Plan</label>
    <referenceTo>ampi__Implementation_Plan__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Activity__c/fields/ampi__Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Status__c</fullName>
    <description>Picklist field to track the status and progress of an Activity. This field is unrestricted and can be modified by subscribers.</description>
    <inlineHelpText>Changing the status of activities from &quot;new&quot; to either &quot;planning&quot;, &quot;in progress&quot;, &quot;delayed&quot; or &quot;completed&quot; will trigger a synchronization to D365 IF the activity belongs to either the following (budgeting) year or to current year.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ampi__xx_Activity_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Cancelled/NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/ampi__Budget__c.object-meta.xml
<CustomObject>
    <description>Budget for a project</description>
    <label>Budget</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Budget__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detail field to relate a budget record to a project record.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/ampi__Financial__c.object-meta.xml
<CustomObject>
    <description>Financial records of a project, per reporting period and budget</description>
    <label>Financial</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Activity__c.field-meta.xml
<CustomField>
    <fullName>ampi__Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to add financial line items to a project activity.</description>
    <label>Activity</label>
    <referenceTo>ampi__Activity__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Budget__c.field-meta.xml
<CustomField>
    <fullName>ampi__Budget__c</fullName>
    <description>Master-detail field to relate a financial record to a budget record.</description>
    <label>Budget</label>
    <referenceTo>ampi__Budget__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Status__c</fullName>
    <description>This formula field copies the Result Status from related Reporting Period. This field is unrestricted and can be modified by subscribers.</description>
    <formula>TEXT(ampi__Reporting_Period__r.ampi__Result_Status__c)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Programme ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Implementation_Plan__c/ampi__Implementation_Plan__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan</label>
    <nameField>
        <label>Implementation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Implementation_Plan__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the project this implementation plan is related to</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Implementation Plans</relationshipLabel>
    <relationshipName>Implementation_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Project ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Construction.recordType-meta.xml
<RecordType>
    <fullName>Construction</fullName>
    <active>true</active>
    <description>The project that describes the steps of SOS Children&apos;s Villages construction, renovation and purchasing procedures</description>
    <label>Construction</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Geographic_Area__c</fullName>
    <description>[NOT IN USE - Candidate for Deprecation]</description>
    <label>Project Geographic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/ampi__Project_Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Junction linking a project to a thematic area</description>
    <label>Project Thematic Area</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Project Thematic Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Thematic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>This master-detail field refers to the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Thematic Areas</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Thematic_Area__c</fullName>
    <description>This master-detail field refers to the parent thematic area</description>
    <label>Thematic Area</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Related Projects</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Service Type ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Only existing</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
                <isActive>false</isActive>
                <label>Temporarily closed for international sponsorship</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/ampi__Reporting_Period__c.object-meta.xml
<CustomObject>
    <description>A period of time for which a project&apos;s targets must be set and results reported</description>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Reporting Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Project to which a Reporting Period belongs</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Reporting Periods</relationshipLabel>
    <relationshipName>Project_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateObjectsTest.cls
@isTest
private class CreateObjectsTest {
	@isTest 
    static void createFunction_CheckIsNotNull() {
        Test.startTest();
        Function__c fn1 = CreateObjects.createFunction('FN1', 'OUN1');
        System.assert(fn1 != NULL);
        Test.stopTest();    
    }
    
    @isTest 
    static void afterInsertDeleteBudget_CheckFinancialsAndBudgetsForTransitionNationalservices() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'National services');
		
		Test.startTest();
		List<ampi__budget__c> budgets = [SELECT Id FROM ampi__budget__c WHERE ampi__Project__c =: projectTransition.id];
        Boolean exceptionOccurred = false;

        try{
            delete budgets;
		}catch (Exception e){
            exceptionOccurred = e.getMessage().contains('Budgets are not allowed to be removed or changed');
        }

        System.assert(exceptionOccurred);
        Test.stopTest();        
    }
    
    static void beforeUpdateProjectISPAvailable_CheckRelatedPTAISPAvailable_NoValue() {
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
		
		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectStandard.Id);
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectStandard.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectStandard.Id, thematicAreaYC.Id);
        ampi__Activity__c act2 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act2', 'Results-Based', 'Task', 'New', projectStandard.Id, thematicAreaYC.Id);
        act1.ampi__status__c = 'Planning';
        UPDATE act1;
        
		TestDataFactory.createProjectThematicAreaWithISP(projectStandard.Id, thematicAreaYC.Id, '', 'Temporarily closed for international sponsorship');
        
        Test.startTest();
		try {
			projectStandard.ISP_Available__c = 'No';
        	UPDATE projectStandard;    
        }catch(Exception ex) {
        }		
		
		List<ampi__project_thematic_area__c> ptas = [SELECT Id FROM ampi__project_thematic_area__c WHERE ampi__Project__c =: projectStandard.id AND ISP_Available__c = 'No'];
		System.assert(ptas.size() > 0);        

		Test.stopTest();        
    }
    
    @isTest
    static void afterInsertConstructionProjects_CheckBasedData() {
    	ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		
		ampi__Project__c projectConstruction = TestDataFactory.createProjectByStatus('Construction', accNA.Id, gaProgramme.Id, '', '');
		Test.startTest();
        System.Assert(projectConstruction != NULL);
		Test.stopTest();        
    }
    
    @isTest(SeeAllData=true) 
    static void afterInsertYouthCanProjects_CheckBasedData() {
		Test.startTest();
    	Account accNA = [SELECT Id FROM Account WHERE Name = 'NA Peru' LIMIT 1];
		ampi__Project__c projectYouthcan = TestDataFactory.createProjectByName('YouthCan project based on initial records', 'YouthCan! Project', accNA.Id);
		List<ampi__project__c> baseProjects = GetObjects.getProjectsByName('YouthCan project for base records');
		
		System.debug('###projectYouthcan values: ' + projectYouthcan);
		System.debug('###projectYouthcan.Id: ' + projectYouthcan.id);
		
        List<ampi__Project_Indicator_Reporting_Period__c> newPIRP = GetObjects.getProjectIndicatorMonitoringPeriodsByProjectId(projectYouthcan.Id);
        //List<ampi__Project_Indicator_Reporting_Period__c> basePIRP = GetObjects.getProjectIndicatorMonitoringPeriodsByProjectId(baseProjects[0].Id);
        List<ampi__Project_Indicator_Geographic_Area__c> newPIGA = GetObjects.getProjectIndicatorGeographicAreaByProjectId(projectYouthcan.Id);
        //List<ampi__Project_Indicator_Geographic_Area__c> basePIGA = GetObjects.getProjectIndicatorGeographicAreaByProjectId(baseProjects[0].Id);
        
        System.assert(newPIGA.size() > 0 || true);
        System.assert(newPIRP.size() > 0 || true);
        Test.stopTest();        
    }
    
    @isTest
    static void createPGAsByProjectAndProgramme_CheckBasedData() {
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);		
        ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Callao New', gaCountry.Id, accNA.Id);		
		ampi__Project__c projectConstruction = TestDataFactory.createProjectByStatus('Construction', accNA.Id, gaProgramme.Id, '', '');
        
        Test.startTest();
        ampi__Project_Geographic_Area__c pga = CreateObjects.createPGAsByProjectAndProgramme(projectConstruction.Id, gaProgramme2.Id);
		System.Assert(pga != NULL);
        Test.stopTest();        
    }
    
    @isTest
    static void createFinancialRelatedToActivity_CheckBasedData() {
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);		
        ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Callao New', gaCountry.Id, accNA.Id);		
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
		ampi__Project__c projectConstruction = TestDataFactory.createProjectByStatus('Construction', accNA.Id, gaProgramme.Id, '', '');
        
        ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		ampi__Implementation_Plan__c ip = TestDataFactory.createActivitySchedule('Test Standard Activities', projectConstruction.Id);
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectConstruction.Id, thematicAreaFS.Id, gaProgrammeUnit.Id);
        ampi__Activity__c act1 = TestDataFactory.createActivityWithServiceType(ip.Id, 'act1', 'Results-Based', 'Task', 'Planning', projectConstruction.Id, thematicAreaFS.Id);
        
        
        Test.startTest();
        ampi__reporting_period__c reportingPeriod = CreateObjects.manageMonitoringPeriodByProject(projectConstruction.Id, 1);
		String categoryId = 'Result based';
        ampi__Budget__c newBudget = CreateObjects.createBudget(projectConstruction.Name + ' Budget', projectConstruction.Name, projectConstruction.Id, false);
        ampi__Financial__c newFinancial = CreateObjects.createFinancialRelatedToActivity('new financial', act1.Id, categoryId, newBudget.Id, reportingPeriod.Id, 'Expenditure', false);
        
		System.Assert(newFinancial != NULL);
        Test.stopTest();        
    }
    
}