force-app/main/default/objects/ampi__Indicator__c/ampi__Indicator__c.object-meta.xml
<CustomObject>
    <description>Catalog indicators that can be used to track progress against goals for a range of projects</description>
    <label>Indicator</label>
    <nameField>
        <displayFormat>IND-{00000}</displayFormat>
        <label>Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Indicator__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to relevant project record if the indicator is only added to a specific project and not the indicator catalog</description>
    <label>Specific Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Indicators</relationshipLabel>
    <relationshipName>Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Indicator__c/fields/ampi__Reporting_Frequency__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Frequency__c</fullName>
    <description>Picklist field to set the frequency at which either only results or results and targets are reported.</description>
    <inlineHelpText>Use this field to set the frequency at which either only results or results and targets are reported.</inlineHelpText>
    <label>Reporting Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Life of Project</fullName>
            </value>
            <value>
                <fullName>--</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Indicator__c/fields/ampi__Target_Frequency__c.field-meta.xml
<CustomField>
    <fullName>ampi__Target_Frequency__c</fullName>
    <description>Picklist field to set a frequency for reporting targets. If this is left blank, target frequency is considered same as reporting frequency</description>
    <inlineHelpText>Use this field to set a frequency at which only targets are reported.</inlineHelpText>
    <label>Target Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Life of Project</fullName>
            </value>
            <value>
                <fullName>--</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Indicator__c/fields/ampi__Type_of_Results__c.field-meta.xml
<CustomField>
    <fullName>ampi__Type_of_Results__c</fullName>
    <description>Picklist to specify how the results are being generated, i.e. inputted, aggregated over source records, or calculated using the results from other indicators</description>
    <label>Type of Results</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Input</fullName>
                <default>true</default>
                <label>Input</label>
            </value>
            <value>
                <fullName>Aggregated</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Indicator__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Participants</fullName>
            </value>
            <value>
                <fullName>Former participants</fullName>
            </value>
            <value>
                <fullName>Households</fullName>
            </value>
            <value>
                <fullName>Former households</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Children &amp; Young People</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Indicator__c/fields/Source_Document__c.field-meta.xml
<CustomField>
    <fullName>Source_Document__c</fullName>
    <label>Source Document</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Statistics Handbook V3</fullName>
                <default>true</default>
                <label>Statistics Handbook V3</label>
            </value>
            <value>
                <fullName>2030 Measures Project</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
            <value>
                <fullName>Case Management and SDGs Indicators Monitored in PDB2</fullName>
            </value>
            <value>
                <fullName>SOS Care Promise Indicators Booklet</fullName>
            </value>
            <value>
                <fullName>Case Management and SDGs Indicators Monitored in PDB3</fullName>
            </value>
            <value>
                <fullName>Statistics Handbook Version Nov 2017</fullName>
            </value>
            <value>
                <fullName>Statistics Handbook Version 3 2022</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/SOS_Implementing_Organisation__c.field-meta.xml
<CustomField>
    <fullName>SOS_Implementing_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Mandatory field for status &quot;in identification&quot;.
Indicate which SOS organisation will implement the project. For Umbrella projects, select &quot;Global-multiple MAs&quot; and register sub-projects for each implementating organisation in a separate step.</inlineHelpText>
    <label>SOS Implementing Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only an SOS Organisation can be an Implementing Organisation.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SOS Organisation - MA</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation - GSC Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funds (SOS Implementing Organisation)</relationshipLabel>
    <relationshipName>Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/ampi__Project_Indicator__c.object-meta.xml
<CustomObject>
    <description>Junction linking a catalog indicator to a project</description>
    <label>Project Indicator</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Project Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Catalog_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Catalog_Indicator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to specify the parent catalog indicator. This field must be populated for several of the formula fields on Project Indicator to print correctly (e.g. Data Type).</description>
    <label>Related Indicator</label>
    <referenceTo>ampi__Indicator__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Project this project indicator belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Project_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Related_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Related_Indicator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the related project indicator to create a hierarchy of Project Indicators.</description>
    <label>Related Project Indicator</label>
    <referenceTo>ampi__Project_Indicator__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Reporting_Frequency__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Frequency__c</fullName>
    <description>This picklist field is used to set the frequency at which either only results or results and targets are reported. The value in this field determines what Project Indicator Reporting Period records are generated by  the Project Indicator triggers.</description>
    <inlineHelpText>Use this field to set the frequency at which either only results or results and targets are reported.</inlineHelpText>
    <label>Reporting Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Life of Project</fullName>
            </value>
            <value>
                <fullName>--</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Target_Frequency__c.field-meta.xml
<CustomField>
    <fullName>ampi__Target_Frequency__c</fullName>
    <description>This picklist field is used to set a frequency at which only targets are reported.</description>
    <inlineHelpText>Use this field to set a frequency at which only targets are reported.</inlineHelpText>
    <label>Target Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Life of Project</fullName>
            </value>
            <value>
                <fullName>--</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Type_of_Results__c.field-meta.xml
<CustomField>
    <fullName>ampi__Type_of_Results__c</fullName>
    <defaultValue>&quot;Input&quot;</defaultValue>
    <description>Picklist field to select whether the results for this project indicator should be input manually, calculated from the results of other project indicators, or aggregated from individual-level data. The value in this field determines whether results are displayed as input or output text on AddResults and whether the user can access the popups for either the Aggregation Criteria or the Calculation Formula.</description>
    <inlineHelpText>Select whether the results for this Project Indicator should be input manually, calculated from the results of other indicators, or aggregated from individual-level data.</inlineHelpText>
    <label>Type of Results</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Input</fullName>
            </value>
            <value>
                <fullName>Aggregated</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/Catalogue_Source_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Catalogue_Source_Unique_ID__c</fullName>
    <description>Contains a unique ID made up of the Project ID and related Catalog Indicator ID. This is populated by Flow when adding an Indicator from the Catalogue (via the &quot;Create Project indicator flow), ensuring that there are no duplicate Project Indicators,</description>
    <inlineHelpText>Contains a unique ID made up of the Project ID and related Catalog Indicator ID. This is populated by Flow when adding an Indicator from the Catalogue (via the &quot;Create Project indicator flow), ensuring that there are no duplicate Project Indicators,</inlineHelpText>
    <label>Catalogue Source Unique ID</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProjectIndicatorTriggerHandler.cls
public class ProjectIndicatorTriggerHandler {
    public void beforeInsertProjectIndicators_SetTypeResultAggregated(List<ampi__project_indicator__c> newProjectIndicators) {
        Set<Id> newIndicatorIds = new Set<Id>();
        Set<Id> newProjectIds = new Set<Id>();

        for(ampi__project_indicator__c pi : newProjectIndicators) {
            System.debug('####pi:' + pi);
            //ampi__Related_Indicator__c
            if (pi.ampi__Catalog_Indicator__c <> null && !newIndicatorIds.contains(pi.ampi__Catalog_Indicator__c)) {
                newIndicatorIds.add(pi.ampi__Catalog_Indicator__c);
            }

            if (pi.ampi__Project__c <> null && !newProjectIds.contains(pi.ampi__Project__c)) {
                newProjectIds.add(pi.ampi__Project__c);
            }
        }

        // SOS Implementing Organisation "Is PDB In Use?"=No. 
        // List<ampi__project_indicator__c> projectIndicatorsToUpdate = [SELECT ampi__Catalog_Indicator__r.ampi__Reporting_Frequency__c, ampi__Catalog_Indicator__r.ampi__Target_Frequency__c, Id, ampi__Type_of_Results__c FROM ampi__project_indicator__c WHERE Id IN :newIds AND ampi__Catalog_Indicator__r.Source_Document__c = 'Statistics Handbook V3' AND ampi__Catalog_Indicator__r.Level__c <> 'Staff' AND ampi__Type_of_Results__c <> 'Aggregated' AND ampi__Project__r.SOS_Implementing_Organisation__r.Is_PDB_In_Use__c = 'Yes'];
        // List<ampi__project_indicator__c> projectIndicatorsToUpdate = [SELECT ampi__Catalog_Indicator__r.ampi__Reporting_Frequency__c, ampi__Catalog_Indicator__r.ampi__Target_Frequency__c, Id, ampi__Type_of_Results__c, ampi__Catalog_Indicator__r.Source_Document__c, ampi__Catalog_Indicator__r.Level__c, ampi__Project__r.SOS_Implementing_Organisation__r.Is_PDB_In_Use__c FROM ampi__project_indicator__c WHERE Id IN :newIds];
        List<ampi__indicator__c> indicatorsRelated = [SELECT Id, ampi__Reporting_Frequency__c, ampi__Target_Frequency__c, Source_Document__c, Level__c FROM ampi__indicator__c WHERE Id IN :newIndicatorIds];
        List<ampi__Project__c> projectsRelated = [SELECT Id, SOS_Implementing_Organisation__r.Is_PDB_In_Use__c FROM ampi__project__c WHERE Id IN :newProjectIds];

        System.debug('####newIndicatorIds:' + newIndicatorIds);
        System.debug('####indicatorsRelated:' + indicatorsRelated);
        // System.debug('····projectIndicatorsToUpdate:' + projectIndicatorsToUpdate);
        System.debug('····Schema.sObjectType.ampi__project_indicator__c.isUpdateable():' + Schema.sObjectType.ampi__project_indicator__c.isUpdateable());
        // If (projectIndicatorsToUpdate.size() > 0 &&  Schema.sObjectType.ampi__project_indicator__c.isUpdateable()) {
        If (Schema.sObjectType.ampi__project_indicator__c.isUpdateable()) {
            for(ampi__project_indicator__c projectIndicatorToUpdate : newProjectIndicators) {

                String Source_Document = '';
                String Catalogue_Source_Unique_ID = '';
                String Level = '';
                String Reporting_Frequency = '';
                String Target_Frequency = '';
                String Is_PDB_In_Use = '';
                boolean indicatorExists = false;
                boolean projectExists = false;
                for(ampi__indicator__c ind : indicatorsRelated) {
                    //not for custom indicators (news)
                    if (ind.Id == projectIndicatorToUpdate.ampi__Catalog_Indicator__c) {
                        //TODO: && projectIndicatorToUpdate.Catalogue_Source_Unique_ID__c <> null) {
                        Source_Document = ind.Source_Document__c;
                        Level = ind.Level__c;
                        Reporting_Frequency = ind.ampi__Reporting_Frequency__c;
                        Target_Frequency = ind.ampi__Target_Frequency__c;
                        indicatorExists = true;
                    }
                }

                for(ampi__Project__c proj : projectsRelated) {
                    if (proj.Id == projectIndicatorToUpdate.ampi__project__c) {
                        Is_PDB_In_Use = proj.SOS_Implementing_Organisation__r.Is_PDB_In_Use__c;
                        projectExists = true;
                    }
                }
                System.debug('····projectExists: ' + projectExists);
                System.debug('····indicatorExits: ' + indicatorExists);
                System.debug('····projectIndicatorToUpdate.ampi__Type_of_Results__c: ' + projectIndicatorToUpdate.ampi__Type_of_Results__c);
                System.debug('····Source_Document__c: ' + Source_Document);
                System.debug('····Level__c: ' + Level);
                System.debug('····Is_PDB_In_Use__c: ' + Is_PDB_In_Use);
                System.debug('····Reporting_Frequency: ' + Reporting_Frequency);
                System.debug('····Target_Frequency: ' + Target_Frequency);

                if (projectExists && indicatorExists) {
                    if (projectIndicatorToUpdate.ampi__Type_of_Results__c <> 'Aggregated' && 
                        Source_Document == 'Statistics Handbook V3' && 
                        Level <> 'Staff' && 
                        Is_PDB_In_Use == 'Yes') {
                        projectIndicatorToUpdate.ampi__Type_of_Results__c = 'Aggregated';
                    }      

                    projectIndicatorToUpdate.ampi__Reporting_Frequency__c = Reporting_Frequency;
                    projectIndicatorToUpdate.ampi__Target_Frequency__c = Target_Frequency;
                    // System.debug('····pi vs indicator Target_Frequency: ' + projectIndicatorToUpdate.ampi__Target_Frequency__c + ' - ' + Target_Frequency);
                    // projectIndicatorToUpdate.ampi__Target_Frequency__c = '--';
                    // projectIndicatorToUpdate.ampi__Reporting_Frequency__c = '--';
                }
                System.debug('····projectIndicatorToUpdate: ' + projectIndicatorToUpdate);
            }
            // UPDATE projectIndicatorsToUpdate;
        }
    }
}