force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>Thematic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>P&amp;PUs</relationshipLabel>
    <relationshipName>P_PUs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Indicator__c/ampi__Indicator__c.object-meta.xml
<CustomObject>
    <description>Catalog indicators that can be used to track progress against goals for a range of projects</description>
    <label>Indicator</label>
    <nameField>
        <displayFormat>IND-{00000}</displayFormat>
        <label>Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Indicator__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to relevant project record if the indicator is only added to a specific project and not the indicator catalog</description>
    <label>Specific Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Indicators</relationshipLabel>
    <relationshipName>Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Indicator_Thematic_Area__c/ampi__Indicator_Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Mechanism to tag an indicator with a theme</description>
    <label>Indicator Thematic Area</label>
    <nameField>
        <displayFormat>ITA-{0000}</displayFormat>
        <label>Indicator Thematic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Indicator_Thematic_Area__c/fields/ampi__Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Indicator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the parent Indicator to this junction object</description>
    <label>Indicator</label>
    <referenceTo>ampi__Indicator__c</referenceTo>
    <relationshipLabel>Indicator Thematic Areas</relationshipLabel>
    <relationshipName>Indicator_Thematic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Indicator_Thematic_Area__c/fields/ampi__Required__c.field-meta.xml
<CustomField>
    <fullName>ampi__Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox field to specify if the parent Indicator is required to be added to a project if the parent Thematic Area is added to that project.</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Indicator_Thematic_Area__c/fields/ampi__Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Thematic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the parent Thematic Area to this junction object</description>
    <label>Thematic Area</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Indicator Thematic Areas</relationshipLabel>
    <relationshipName>Indicator_Thematic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Geographic_Area__c</fullName>
    <description>Master-detail to specify parent geographic area</description>
    <label>Geographic Area</label>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Project Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Geographic_Area__c</fullName>
    <description>[NOT IN USE - Candidate for Deprecation]</description>
    <label>Project Geographic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/Delete_PIGAs__c.field-meta.xml
<CustomField>
    <fullName>Delete_PIGAs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete PIGAs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/ampi__Project_Indicator__c.object-meta.xml
<CustomObject>
    <description>Junction linking a catalog indicator to a project</description>
    <label>Project Indicator</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Project Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Catalog_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Catalog_Indicator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to specify the parent catalog indicator. This field must be populated for several of the formula fields on Project Indicator to print correctly (e.g. Data Type).</description>
    <label>Related Indicator</label>
    <referenceTo>ampi__Indicator__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Project this project indicator belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Project_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator_Geographic_Area__c/ampi__Project_Indicator_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project indicator</description>
    <label>Project Indicator Geographic Area</label>
    <nameField>
        <displayFormat>PIGA-{0000}</displayFormat>
        <label>Project Indicator Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicator Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator_Geographic_Area__c/fields/ampi__Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Geographic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify parent geographic area. This value is populated by the trigger on Project Geographic Area. This field determines what gets concatenated the Geographic Area field on the parent Project Indicator record.</description>
    <label>Geographic Area</label>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Project Indicator Geographic Areas</relationshipLabel>
    <relationshipName>Project_Indicator_Geographic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator_Geographic_Area__c/fields/ampi__Project_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify parent project indicator. This field determines what Project Indicator is being updated by the trigger on Project Indicator Geographic Area.</description>
    <label>Project Indicator</label>
    <referenceTo>ampi__Project_Indicator__c</referenceTo>
    <relationshipLabel>Project Indicator Geographic Areas</relationshipLabel>
    <relationshipName>Project_Indicator_Geographic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectGeographicAreaService.cls
public class ProjectGeographicAreaService  {

	public static void deletePIGAs(List<ampi__Project_Geographic_Area__c> projectGeographicAreas, Map<Id, ampi__Project_Geographic_Area__c> oldProjectGeographicAreas){
		Set<Id> gAreasIds = new Set<Id>();
		Set<Id> pIds = new Set<Id>();
		for(ampi__Project_Geographic_Area__c pga : projectGeographicAreas){
			if(pga.Delete_PIGAs__c && !oldProjectGeographicAreas.get(pga.Id).Delete_PIGAs__c){
				gAreasIds.add(pga.ampi__Geographic_Area__c);
				pIds.add(pga.ampi__Project__c);
			}
		}
		System.debug('#### ' + gAreasIds.size());
		if(gAreasIds.size()>0){// && pIds.size()>0){
			List<ampi__Project_Indicator_Geographic_Area__c> PIGAs = [SELECT Id, ampi__Geographic_Area__c, ampi__Geographic_Area__r.Thematic_Area__c, ampi__Project_Indicator__c, ampi__Project_Indicator__r.ampi__Project__c, ampi__Project_Indicator__r.ampi__Catalog_Indicator__c FROM ampi__Project_Indicator_Geographic_Area__c WHERE ampi__Geographic_Area__c IN: gAreasIds];// AND ampi__Project_Indicator__r.ampi__Project__c IN: pIds];
			if(PIGAs.size()>0){
				System.debug('#### ' + PIGAs.size());
					//delete PIGAs;
				List<ampi__Geographical_Area__c> gAreas = [SELECT Id, Thematic_Area__c FROM ampi__Geographical_Area__c WHERE Id IN: gAreasIds];
				Set<Id> thematicAreaIds = new Set<Id>();
				if(gAreas.size()>0){
					System.debug('#### ' + gAreas.size());
					for(ampi__Geographical_Area__c ga : gAreas){
						thematicAreaIds.add(ga.Thematic_Area__c);
					}
					if(thematicAreaIds.size()>0){
						System.debug('#### ' + thematicAreaIds.size());
						List<ampi__Indicator_Thematic_Area__c> ITAs = [SELECT Id, ampi__Indicator__c, ampi__Required__c, ampi__Thematic_Area__c FROM ampi__Indicator_Thematic_Area__c WHERE ampi__Thematic_Area__c IN: thematicAreaIds];
						Map<Id, Set<Id>> ITAThematicArea = new Map<Id, Set<Id>>();
						for(Id id : thematicAreaIds){
							Set<Id> ITAIndicators = new Set<Id>();	
							for(ampi__Indicator_Thematic_Area__c ITA : ITAs){
								if(id == ITA.ampi__Thematic_Area__c){
									ITAIndicators.add(ITA.ampi__Indicator__c);
								}
							}
							ITAThematicArea.put(id, ITAIndicators);
						}					
						
						System.debug('#### ' + ITAThematicArea.size());
						List<ampi__Project_Indicator_Geographic_Area__c> PIGAs2Delete = new List<ampi__Project_Indicator_Geographic_Area__c>();
						for(ampi__Project_Indicator_Geographic_Area__c PIGA : PIGAs){
							Boolean found = false;
							//for(ampi__Indicator_Thematic_Area__c ITA : ITAs){								
								//if(PIGA.ampi__Project_Indicator__r.ampi__Catalog_Indicator__c == ITA.ampi__Indicator__c){
								//System.debug('#### ' + PIGA.ampi__Geographic_Area__c + ' ' + PIGA.ampi__Project_Indicator__r.ampi__Catalog_Indicator__c + ' ' + PIGA.ampi__Geographic_Area__r.Thematic_Area__c);
								if(ITAThematicArea.containsKey(PIGA.ampi__Geographic_Area__r.Thematic_Area__c)){
									if(ITAThematicArea.get(PIGA.ampi__Geographic_Area__r.Thematic_Area__c).contains(PIGA.ampi__Project_Indicator__r.ampi__Catalog_Indicator__c)){
										found = true;	
									}
									else{
									
									}
								}
								//if(ITAIndicators.contains(PIGA.ampi__Project_Indicator__r.ampi__Catalog_Indicator__c)){
									//found = true;
								//}
								else{
									//System.debug('#### ' + PIGA.ampi__Geographic_Area__c + ' ' + PIGA.ampi__Project_Indicator__r.ampi__Catalog_Indicator__c + ' ' + ITAIndicators.contains(PIGA.ampi__Project_Indicator__r.ampi__Catalog_Indicator__c));
								}
							//}
							if(!found){
								PIGAs2Delete.add(PIGA);		
							}
						}
						if(PIGAs2Delete.size()>0){
							delete PIGAs2Delete;
						}
					}
					else{
						delete PIGAs;
					}
				}
				/*
						Set<Id> indicatorIds = new Set<Id>();
						for(ampi__Indicator_Thematic_Area__c ita : ITAs){
							if(ita.ampi__Indicator__c != NULL){
								indicatorIds.add(ita.ampi__Indicator__c);
							}
						}
						List<ampi__Project_Indicator__c> porjectIndicators = [SELECT Id, ampi__Catalog_Indicator__c FROM ampi__Project_Indicator__c WHERE ampi__Catalog_Indicator__c IN: indicatorIds];
						List<ampi__Project_Indicator_Geographic_Area__c> newPIGAs = new List<ampi__Project_Indicator_Geographic_Area__c>();
						if(porjectIndicators.size()>0){
							for(ampi__Project_Geographic_Area__c pga : projectGeographicAreas){
								for(ampi__Geographical_Area__c ga : gAreas){
									for(ampi__Indicator_Thematic_Area__c ita : ITAs){
										for(ampi__Project_Indicator__c pi : porjectIndicators){
											if(pi.ampi__Catalog_Indicator__c == ita.ampi__Indicator__c){
												if(ita.ampi__Thematic_Area__c == ga.Thematic_Area__c){
													if(ga.Thematic_Area__c == pga.ampi__Geographic_Area__c){
														ampi__Project_Indicator_Geographic_Area__c newPIGA = new ampi__Project_Indicator_Geographic_Area__c();
														newPIGA.ampi__Geographic_Area__c = ga.Id;
														newPIGA.ampi__Project_Indicator__c = pi.Id;
														newPIGAs.add(newPIGA);
													}
												}
											}
										}
									}
								}
							}
							if(newPIGAs.size()>0){
								insert newPIGAs;
							}
						}
						else{
					
						}
					}
				}*/
			}

		}
	}
}