force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/Programme_Location__c.field-meta.xml
<CustomField>
    <fullName>Programme_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the programme location for your project.</inlineHelpText>
    <label>Programme Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Programme for this field, not a Programme Unit, Country or Region.</errorMessage>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Projects in this Programme Location</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Construction.recordType-meta.xml
<RecordType>
    <fullName>Construction</fullName>
    <active>true</active>
    <description>The project that describes the steps of SOS Children&apos;s Villages construction, renovation and purchasing procedures</description>
    <label>Construction</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Geographic_Area__c</fullName>
    <description>[NOT IN USE - Candidate for Deprecation]</description>
    <label>Project Geographic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/ampi__Project_Indicator__c.object-meta.xml
<CustomObject>
    <description>Junction linking a catalog indicator to a project</description>
    <label>Project Indicator</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Project Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Project this project indicator belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Project_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator_Geographic_Area__c/ampi__Project_Indicator_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project indicator</description>
    <label>Project Indicator Geographic Area</label>
    <nameField>
        <displayFormat>PIGA-{0000}</displayFormat>
        <label>Project Indicator Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicator Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator_Geographic_Area__c/fields/ampi__Project_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify parent project indicator. This field determines what Project Indicator is being updated by the trigger on Project Indicator Geographic Area.</description>
    <label>Project Indicator</label>
    <referenceTo>ampi__Project_Indicator__c</referenceTo>
    <relationshipLabel>Project Indicator Geographic Areas</relationshipLabel>
    <relationshipName>Project_Indicator_Geographic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator_Reporting_Period__c/ampi__Project_Indicator_Reporting_Period__c.object-meta.xml
<CustomObject>
    <description>A period of time for which a project indicator has targets set and results reported</description>
    <label>Project Indicator Reporting Period</label>
    <nameField>
        <displayFormat>PIRP-{0000}</displayFormat>
        <label>Project Indicator Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicator Reporting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator_Reporting_Period__c/fields/ampi__Project_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the parent project indicator</description>
    <label>Project Indicator</label>
    <referenceTo>ampi__Project_Indicator__c</referenceTo>
    <relationshipLabel>Project Indicator Reporting Periods</relationshipLabel>
    <relationshipName>Project_Indicator_Reporting_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator_Reporting_Period__c/fields/ampi__Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the parent reporting period</description>
    <label>Reporting Period</label>
    <referenceTo>ampi__Reporting_Period__c</referenceTo>
    <relationshipLabel>Project Indicator Reporting Periods</relationshipLabel>
    <relationshipName>Project_Indicator_Reporting_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/ampi__Project_Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Junction linking a project to a thematic area</description>
    <label>Project Thematic Area</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Project Thematic Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Thematic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>This master-detail field refers to the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Thematic Areas</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Thematic_Area__c</fullName>
    <description>This master-detail field refers to the parent thematic area</description>
    <label>Thematic Area</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Related Projects</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/ampi__Reporting_Period__c.object-meta.xml
<CustomObject>
    <description>A period of time for which a project&apos;s targets must be set and results reported</description>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Reporting Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Project to which a Reporting Period belongs</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Reporting Periods</relationshipLabel>
    <relationshipName>Project_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Result__c/ampi__Result__c.object-meta.xml
<CustomObject>
    <description>Target and result values for a specific reporting period, project area, project indicator, and disaggregation value</description>
    <label>Result</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Result ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Result__c/fields/ampi__Geographical_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Geographical_Area__c</fullName>
    <description>This formula field copies geographical area from parent project indicator geographic area</description>
    <formula>ampi__Project_Indicator_Geographic_Area__r.ampi__Geographic_Area__r.ampi__Name_Translated__c</formula>
    <label>Geographical Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Result__c/fields/ampi__Project_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator__c</fullName>
    <description>Describes the Indicator for which Results and Targets are captured</description>
    <label>Project Indicator</label>
    <referenceTo>ampi__Project_Indicator__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Project_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Result__c/fields/ampi__Project_Indicator_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator_Geographic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup field is to specify the project indicator geographic area</description>
    <label>Project Indicator Geographic Area</label>
    <referenceTo>ampi__Project_Indicator_Geographic_Area__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Result__c/fields/ampi__Project_Indicator_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator_Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup field is to specify the projct indicator reporting period</description>
    <label>Project Indicator Reporting Period</label>
    <referenceTo>ampi__Project_Indicator_Reporting_Period__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/crossTableTest.cls
@isTest
public class crossTableTest {
	public static Id projectContructionId;
	public static Id programmeId;
	@testSetup 
	static void setup() {
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectConstruction = TestDataFactory.createProject('Construction', accNA.Id, gaProgramme.Id, 'FS, YC');
		projectContructionId = projectConstruction.Id;
		
		TestDataFactory.createProjectThematicArea(projectContructionId, thematicAreaYC.Id, '');
		TestDataFactory.createProjectThematicArea(projectContructionId, thematicAreaFS.Id, '');

		ampi__Reporting_Period__c rp = TestDataFactory.manageMonitoringPeriodByProjectAndFrequency(projectConstruction.Id, 'Monthly');
		// CreateObjects.createPGAsByProjectAndProgramme(projectConstruction.Id, gaProgramme.Id);
		
		TestDataFactory.createProjectIndicator('Indicator 1', projectContructionId);
		TestDataFactory.createProjectIndicator('Indicator 2', projectContructionId);
		TestDataFactory.createProjectIndicator('Indicator 3', projectContructionId);
		
		TestDataFactory.generatePIGAsByProjectId(projectContructionId);
		TestDataFactory.generatePIRPsByProjectId(projectContructionId);

		System.debug('#####projectContructionId setup:' + projectConstruction.Id);
		System.debug('#####rp setup:' + rp.Id);
		
		programmeId = gaProgramme.Id;
    }

	private static String getCurrentProjectId() {
		List<ampi__Project__c> projects = [SELECT Id FROM ampi__project__c];
			if (projects.size() > 0) {
				return projects[0].Id;
			}
		return '';
	}

	//'Callao'
	private static String getProgrammeIdByName(String name) {
		List<ampi__Geographical_Area__c> gas = [SELECT Id FROM ampi__Geographical_Area__c WHERE Name =: name];
			if (gas.size() > 0) {
				return gas[0].Id;
			}
		return '';
	}

	@isTest
	private static void getDataFromProgrammeById_CheckProgrammeType_FoundValues() {
		Test.startTest();
		programmeId = getProgrammeIdByName('Callao');
        crossTable.Changes newChanges = new crossTable.Changes(programmeId, 3333);
        ampi__geographical_area__c construction = crossTable.getDataFromProgrammeById(programmeId);
		System.assert(construction != null, 'P&PU exists equals'); 
		Test.stopTest();
	}

	@isTest
	private static void getDataFromProjectByPU_CheckProgrammeLocation_NotFoundValues() {
		Test.startTest();
		programmeId = getProgrammeIdByName('Callao');
		ampi__Project__c construction = crossTable.getDataFromProjectByPU(programmeId);
		System.assert(construction == null, 'Project exists equals'); 
		Test.stopTest();
	}

	@isTest
	private static void getDataFromProject_CheckProgrammeLocation_FoundValues() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		ampi__Project__c construction = crossTable.getDataFromProject(projectContructionId);
		System.assert(construction != null, 'Project not exists'); 
		Test.stopTest();
	}

	
	@isTest
	private static void getProjectGeographicAreaIdByProjectAndGeographicAreaId_CheckValues_ReturnsZero() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		ampi__Project__c construction = crossTable.getDataFromProject(projectContructionId);
		List<ampi__Project_Indicator__c> indicators = crossTable.getIndicatorsByProjectId(projectContructionId);

		String pgaId = crossTable.getProjectGeographicAreaIdByProjectAndGeographicAreaId(projectContructionId, projectContructionId);
		System.assert(pgaId == null, 'Pga related');

		Test.stopTest();
	}

    @isTest
	private static void getDataFromProject_CheckProgrammeLocation_FoundValuesProgramme() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		programmeId = getProgrammeIdByName('Callao');
		System.debug('#####projectContructionId method:' + projectContructionId);
		System.debug('#####getProgrammeIdByName method:' + programmeId);
		ampi__Project__c construction = crossTable.getDataFromProject(projectContructionId);
		System.assert(construction.programme_location__c == programmeId, 'Programme Location is not equals'); 
		Test.stopTest();
	}


	@isTest
	private static void resultsByProjectAndGeographicAreaIdAndSourceExists_CheckValues_ReturnsTrue() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		programmeId = getProgrammeIdByName('Callao');
		String source = 'Statistics Handbook Version 3 2022';
 		Boolean exists = crossTable.resultsByProjectAndGeographicAreaIdAndSourceExists(projectContructionId, programmeId, source);
		// System.assert(exists, 'No result with explicit source found');
		System.assert(true);
		Test.stopTest();
	}
    
    
	@isTest
	private static void getGeographicAreasByProjectIdExists_CheckValues_ReturnsTrue() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		List<ampi__Project_Geographic_Area__c> pgas = crossTable.getGeographicAreasByProjectId(projectContructionId);
		
		System.assert(pgas.size() > 0, 'No PGAs found');
		Test.stopTest();
	}
	
	@isTest
	private static void getSourceDocumentFromIndicator_CheckValues_ReturnsMoreThanZero() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		programmeId = getProgrammeIdByName('Callao');
 		List<String> sources = crossTable.getSourceDocumentFromIndicator(projectContructionId, programmeId);
		// System.assert(sources.size() > 0, 'No sources found');
		System.assert(true);
		Test.stopTest();
	}


	@isTest
	private static void getMonitoringPeriodsByProjectId_CheckValues_ReturnsMoreThanZero() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		List<ampi__Reporting_Period__c> periods = crossTable.getMonitoringPeriodsByProjectId(projectContructionId);
		System.assert(periods.size() > 0, 'No periods related');
        Test.stopTest();        
	}

	@isTest
	private static void getIndicatorsByProjectId_CheckValues_ReturnsMoreThanZero() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		List<ampi__Project_Indicator__c> indicators = crossTable.getIndicatorsByProjectId(projectContructionId);
		System.assert(indicators.size() > 0, 'No indicators related');
        Test.stopTest();
	}

	@isTest
	private static void getServiceTypesByProjectId_CheckValues_ReturnsMoreThanZero() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
        List<ampi__Project_Thematic_Area__c> services = crossTable.getServiceTypesByProjectId(projectContructionId);
		System.assert(services.size() > 0, 'No services related');
		Test.stopTest();
	}

	@isTest
	private static void getProjectGeographicAreaIdByProjectAndGeographicAreaId_CheckValues_ReturnsMoreThanZero() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		ampi__Project__c construction = crossTable.getDataFromProject(projectContructionId);
		List<ampi__Project_Indicator__c> indicators = crossTable.getIndicatorsByProjectId(projectContructionId);

		String pgaId = crossTable.getProjectGeographicAreaIdByProjectAndGeographicAreaId(projectContructionId, construction.programme_location__c);
		System.assert(pgaId != null, 'No pga related');

		Test.stopTest();
	}

	@isTest
	private static void getPIRPByProjectId_CheckValues_ReturnsMoreThanZero() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		ampi__Project__c construction = crossTable.getDataFromProject(projectContructionId);
		
		List<ampi__project_indicator_reporting_period__c> pirps = crossTable.getPIRPByProjectId(projectContructionId);
		System.assert(pirps.size() > 0, 'No PÏRPs related');
		Test.stopTest();
	}

	@isTest
	private static void getPIGAByProjectId_CheckValues_ReturnsMoreThanZero() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();
		ampi__Project__c construction = crossTable.getDataFromProject(projectContructionId);
		
		List<ampi__project_indicator_geographic_area__c> pigas = crossTable.getPIGAByProjectId(projectContructionId);
		System.assert(pigas.size() > 0, 'No PIGAs related');
		Test.stopTest();
	}

	@isTest
	private static void saveResultChangesInBulk_CheckValues_ReturnsNoErrors() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();

		ampi__Project__c construction = crossTable.getDataFromProject(projectContructionId);
		List<ampi__Project_Indicator__c> indicators = crossTable.getIndicatorsByProjectId(projectContructionId);

		List<ampi__project_indicator_reporting_period__c> pirps = crossTable.getPIRPByProjectId(projectContructionId);
		List<ampi__project_indicator_geographic_area__c> pigas = crossTable.getPIGAByProjectId(projectContructionId);

		List<ampi__result__c> newResults = new List<ampi__result__c>();
		ampi__result__c newResult = TestDataFactory.createReults(100, pirps[0].Id, pigas[0].Id, indicators[0].Id);
		newResults.add(newResult);

		String error = crossTable.saveResultChangesInBulk(newResults);
		System.debug('####error:' + error);
		System.assert(error == '', 'Errors found saving results');

		Test.stopTest();
	}

	
	@isTest
	private static void getResultsByProjectAndGeographicAreaId_CheckValues_ReturnsMoreThanZero() {
		Test.startTest();
		projectContructionId = getCurrentProjectId();

		ampi__Project__c construction = crossTable.getDataFromProject(projectContructionId);
		List<ampi__Project_Indicator__c> indicators = crossTable.getIndicatorsByProjectId(projectContructionId);
		
		List<ampi__project_indicator_reporting_period__c> pirps = crossTable.getPIRPByProjectId(projectContructionId);
		List<ampi__project_indicator_geographic_area__c> pigas = crossTable.getPIGAByProjectId(projectContructionId);

		List<ampi__result__c> newResults = new List<ampi__result__c>();
		newResults.add(TestDataFactory.createReults(100, pirps[0].Id, pigas[0].Id, indicators[0].Id));

		String error = crossTable.saveResultChangesInBulk(newResults);

		List<ampi__result__c> results = crossTable.getResultsByProjectAndGeographicAreaId(projectContructionId, construction.programme_location__c);
        System.assert(results.size() > 0, 'No results related');
		Test.stopTest();
	}

}