force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <inlineHelpText>Indicates whether unit or Programme is still active.</inlineHelpText>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/ampi__Parent_Geographical_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Parent_Geographical_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to relate a geographic area to its parent and create a hierarchy of geographic areas.</description>
    <label>Parent Geographic Area</label>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Child Geographic Areas</relationshipLabel>
    <relationshipName>Related_Geographical_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/ampi__Type__c.field-meta.xml
<CustomField>
    <fullName>ampi__Type__c</fullName>
    <description>Picklist to specify the type of geographic area (Country/ State etc.)</description>
    <inlineHelpText>System defined. Amp Impact Indicator page (for adding a new indicator) looks at this field specifically in order to enable the behaviour of the custom page.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Programme</fullName>
            </value>
            <value>
                <fullName>Programme Unit</fullName>
            </value>
            <value>
                <fullName>National Management Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <inlineHelpText>Derived from LUCY Data: Region Code (3 digits), Country Code (2 Characters), Programme Code (10 digits), Programme Unit Code (R-code)</inlineHelpText>
    <label>Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Date_Founded__c.field-meta.xml
<CustomField>
    <fullName>Date_Founded__c</fullName>
    <inlineHelpText>Start date is mandatory for Programmes</inlineHelpText>
    <label>Operation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Extent_Information__c.field-meta.xml
<CustomField>
    <fullName>Extent_Information__c</fullName>
    <label>Extent Information</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Programme ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Operation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Operation_End_Date__c</fullName>
    <inlineHelpText>End date is mandatory for Programmes</inlineHelpText>
    <label>Operation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Parent_MA__c.field-meta.xml
<CustomField>
    <fullName>Parent_MA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent MA for Programmes</inlineHelpText>
    <label>Parent MA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SOS Organisation - MA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programmes &amp; Programme Units</relationshipLabel>
    <relationshipName>Programmes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Program_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Unit_Type__c</fullName>
    <label>Programme Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programme_Unit_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>Thematic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>P&amp;PUs</relationshipLabel>
    <relationshipName>P_PUs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/recordTypes/Country.recordType-meta.xml
<RecordType>
    <fullName>Country</fullName>
    <active>true</active>
    <label>Country</label>
</RecordType>

force-app/main/default/objects/ampi__Geographical_Area__c/recordTypes/Organisational_Unit.recordType-meta.xml
<RecordType>
    <fullName>Organisational_Unit</fullName>
    <active>true</active>
    <label>Organisational Unit</label>
</RecordType>

force-app/main/default/objects/ampi__Geographical_Area__c/recordTypes/Programme_Location.recordType-meta.xml
<RecordType>
    <fullName>Programme_Location</fullName>
    <active>true</active>
    <label>Programme</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Project ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Programme_Location__c.field-meta.xml
<CustomField>
    <fullName>Programme_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the programme location for your project.</inlineHelpText>
    <label>Programme Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Programme for this field, not a Programme Unit, Country or Region.</errorMessage>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Projects in this Programme Location</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/ampi__Project_Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Junction linking a project to a thematic area</description>
    <label>Project Thematic Area</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Project Thematic Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Thematic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>This master-detail field refers to the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Thematic Areas</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Programme unit code</description>
    <formula>Programme_Unit__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Legacy code of PU</inlineHelpText>
    <label>PU Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Service Type ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Only existing</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
                <isActive>false</isActive>
                <label>Temporarily closed for international sponsorship</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/Programme_Unit__c.field-meta.xml
<CustomField>
    <fullName>Programme_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>3 AND (1 OR 2)</booleanFilter>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>Programme Unit</value>
        </filterItems>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>National Management Unit</value>
        </filterItems>
        <filterItems>
            <field>ampi__Geographical_Area__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Organisational Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Project Service Types</relationshipLabel>
    <relationshipName>Project_Service_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/PU_Extent_Information__c.field-meta.xml
<CustomField>
    <fullName>PU_Extent_Information__c</fullName>
    <label>PU Extent Information</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GeographicAreaTriggerHandler.cls
public class GeographicAreaTriggerHandler {
    public void manageBeforeInsertGA(List<ampi__Geographical_Area__c> newPUs) {
        Map<ID,Schema.RecordTypeInfo> rt_Map = ampi__Geographical_Area__c.sObjectType.getDescribe().getRecordTypeInfosById();
        
        for(ampi__Geographical_Area__c ga: newPUs) {    
             String recordTypeName = rt_map.get(ga.RecordTypeId).getDeveloperName();                
             if (recordTypeName == 'Country') {                 
                 checkGACountry(ga);
             }             
         }
    }
    
    public void manageBeforeUpdateGA(List<ampi__Geographical_Area__c> oldPUs, List<ampi__Geographical_Area__c> newPUs) {
        for (ampi__Geographical_Area__c newPU : newPUs) {
            ampi__Geographical_Area__c currentGA = null;
        	for (ampi__Geographical_Area__c oldPU : oldPUs) {
                if (oldPU.Id == newPU.Id) {
                    currentGA = oldPU;
                }
            }
            
        	beforeUpdateProgrammeRecords(currentGA, newPU);
            beforeUpdateProjectServiceTypeUpdate(currentGA, newPU);
            beforeUpdateGeographicalAreaISPAvailable(currentGA, newPU);
        }
    	
    }
        
    private void checkGACountry(ampi__Geographical_Area__c ga) {                     
                     if (ga.Code__c != NULL && ga.Code__c.length() == 3) {
                         List<ampi__Geographical_Area__c > gas = [SELECT Id FROM ampi__Geographical_Area__c WHERE Code__c=:ga.Code__c AND RecordType.Name = 'Country'];
                         if (gas.size() > 0) {
                             ga.addError('Country code must be unique');
                         }
                     } else {
                         ga.addError('Country code must have 3 characters');                     
                     }
	}
    
    private void beforeUpdateProgrammeRecords(ampi__Geographical_Area__c oldPU, ampi__Geographical_Area__c newPU) {
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Manage_Restrictions');

        if (hasCustomPermission)
            return;
                
        Set<Id> pusToUpdate = new Set<Id>();
             Map<ID,Schema.RecordTypeInfo> rt_Map = ampi__Geographical_Area__c.sObjectType.getDescribe().getRecordTypeInfosById();
             //System.debug('###rt_map.get(oldPU.RecordTypeId).getDeveloperName():' + rt_map.get(oldPU.RecordTypeId).getDeveloperName());
             //All Programmes with the “Active” value “NO” as well as all Programmes without any active projects/released PUs (or the like in future) have to have an Operation End Date.
             if ((rt_map.get(oldPU.RecordTypeId).getDeveloperName() == 'Organisational_Unit' && (oldPU.ampi__Type__c == 'National Office Programme')) || 
                 (rt_map.get(oldPU.RecordTypeId).getDeveloperName() == 'Programme_Location')) {
                 List<ampi__project__c> projectsRelated = [SELECT Id FROM ampi__project__c WHERE programme_location__c =: oldPU.Id];
                 //System.debug('####projectsRelated:' + projectsRelated.size());
                 //List<ampi__geographical_area__c> programmeInfoRelated = [SELECT Id FROM ampi__geographical_area__c WHERE ampi__Parent_Geographical_Area__c =: oldPU.Id];
                 //System.debug('####programmeInfoRelated:' + programmeInfoRelated.size());
                 List<ampi__geographical_area__c> puRelated = [SELECT Id FROM ampi__geographical_area__c WHERE ampi__Parent_Geographical_Area__c =: oldPU.Id];
                 //System.debug('####puRelated:' + puRelated.size());
                     
                 System.debug('####newPU.Active__c:' + newPU.Active__c);
                 if (oldPU.Id == newPU.Id && newPU.Active__c == 'No' && (newPU.Operation_End_Date__c == null  || newPU.Date_Founded__c > newPU.Operation_End_Date__c) && projectsRelated.size() == 0 && puRelated.size() == 0) {
                 	newPU.addError('Operation End Date field must be completed because the Programme is inactive and has no projects and programme units related and has to be greater than Operational Start Date');                    
                }
             }             
        }
    
    private void beforeUpdateProjectServiceTypeUpdate(ampi__Geographical_Area__c oldPU, ampi__Geographical_Area__c newPU) {
        Set<Id> pusToUpdate = new Set<Id>();
        Map<ID,Schema.RecordTypeInfo> rt_Map = ampi__Geographical_Area__c.sObjectType.getDescribe().getRecordTypeInfosById();
        System.debug('####rt_map.get(oldPU.RecordTypeId).getDeveloperName():' + rt_map.get(oldPU.RecordTypeId).getDeveloperName());
        System.debug('####oldPU.ampi__Type__c:' + oldPU.ampi__Type__c);
        if (rt_map.get(oldPU.RecordTypeId).getDeveloperName() == 'Organisational_Unit' && (oldPU.ampi__Type__c == 'Programme Unit' || oldPU.ampi__Type__c == 'National Management Unit')) {
        	if (oldPU.Extent_Information__c != newPU.Extent_Information__c) {
            	pusToUpdate.add(oldPU.Id);
            }
        }
        System.debug('####pusToUpdate.size():' + pusToUpdate.size());
        if (pusToUpdate.size() > 0) {
            List<ampi__Project_Thematic_Area__c> psts = [SELECT PU_Extent_Information__c, Id, Programme_Unit__c FROM ampi__Project_Thematic_Area__c WHERE Programme_Unit__c IN : pusToUpdate];
            for (ampi__Project_Thematic_Area__c pst : psts) {
                if (newPU.Id == pst.Programme_Unit__c) {
                	pst.PU_Extent_Information__c = newPU.Extent_Information__c;
                    System.debug('####newPU.Extent_Information__c:' + newPU.Extent_Information__c);
                }
            }
            UPDATE psts;
        }
    }

    private void beforeUpdateGeographicalAreaISPAvailable(ampi__Geographical_Area__c prsToCheck, ampi__Geographical_Area__c prsUpdated) {
        System.debug('##### enter beforeUpdateGeographicalAreaISPAvailable');
        
		if (prsUpdated.ISP_Available__c != prsToCheck.ISP_Available__c) {
        	List<string> projIds = new List<string>();
                    
            String IPS_value = prsUpdated.ISP_Available__c;                
                    //TODO: comented because of ticket AMIMSP-2043
                    /*if (prsUpdated.ISP_Available__c == 'No' || prsUpdated.ISP_Available__c == 'Temporarily closed for international sponsorship') {
                        System.debug('##### enter beforeUpdateGeographicalAreaISPAvailable ISP Different same Id');
                        
                        List<ampi__project__c> projs = [SELECT Id, ISP_Available__c FROM ampi__project__c WHERE programme_location__c =: prsUpdated.Id AND ISP_Available__c <> :IPS_value AND RecordType.Name IN ('Standard', 'Transition')];

                        for (ampi__project__c proj : projs) {
                            projIds.add(proj.Id);
                            proj.ISP_Available__c = IPS_value;
                        }

                        if (projs.size() == 0) {
                            continue;
                        }

                        Database.SaveResult[] updateResult = Database.update(projs, false);  
                        for (Database.SaveResult r : updateResult){  
                            if (!r.isSuccess()){  
                                prsUpdated.addError('Project related records have missing mandatory fields');                            
                            }  
                        }                                                 
                    }*/
        }
    }

	/*public void beforeCheckMandatoryFieldsForPUsAndNMUs(List<ampi__Geographical_Area__c> oldPUs, List<ampi__Geographical_Area__c> newPUs) {  
        System.debug('####beforeCheckMandatoryFieldsForPUsAndNMUs');
        for (ampi__Geographical_Area__c oldPU : oldPUs) {
             if (oldPU.ampi__Type__c == 'Programme Unit' || oldPU.ampi__Type__c == 'National Management Unit') {
                 for (ampi__Geographical_Area__c newPU : newPUs) {                     
                    if (oldPU.Id == newPU.Id && (newPU.Active__c == null || newPU.ampi__Parent_Geographical_Area__c == null || newPU.Program_Unit_Type__c == null || newPU.Thematic_Area__c == null || newPU.Parent_MA__c == null)) {
        				newPU.addError('Programme Units and National Management Units have mandatory fields: Type, Active, Parent Geographical Area, Programme Unit Type, Service Type and Parent MA');                            
    				}                         
                }
             }             
        }
    }*/
}