force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project</description>
    <inlineHelpText>Add description of your project (1024 char max), describe specific objectives. Include key words to ease the search (e.g. country, donor). The description can be changed and updated at any time and is shown on the Team Site.</inlineHelpText>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <description>Defined by contract with institutional donor, major corporate or foundation following PCM/RBM. Funded by int. or local funds. Can take place at programme, national or multi-country level. If in response to a humanitarian crisis, indicate in project setup.</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Geographic_Area__c</fullName>
    <description>[NOT IN USE - Candidate for Deprecation]</description>
    <label>Project Geographic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Register__c/ampi__Risk_Register__c.object-meta.xml
<CustomObject>
    <description>Track risks associated with projects/grants so staff can have better visibility into identified risks across a portfolio</description>
    <label>Risk Register</label>
    <nameField>
        <label>Risk Register Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Risk_Register__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Risk Registers must be associated with a Project so that grant-makers can, at the grant/project-level, make decisions on the grant/project based on the related Risks.</description>
    <inlineHelpText>Associated with a Project with a Risk Register so that grant-makers can, at the grant/project-level, make decisions on the grant/project based on the related Risks</inlineHelpText>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Risk Registers</relationshipLabel>
    <relationshipName>Risk_Registers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Thematic_Area__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to descrive the thematic area</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/customRelatedListsTest.cls
@isTest 
private class customRelatedListsTest {
	@isTest
	private static void getProjectGeographicAreaByProjectId_ForGrantProject_InactivatingOneGA() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao 3', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima 3', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme3 = TestDataFactory.createProgramme('Areq 3', gaCountry.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		ampi__Project__c projectGrant = TestDataFactory.createProject('Grant', accNA.Id, gaProgramme.Id, 'FS, YC');
		ampi__Project_Geographic_Area__c pga = TestDataFactory.createPGA(projectGrant.Id, gaProgramme2.Id);
		ampi__Project_Geographic_Area__c pga2 = TestDataFactory.createPGA(projectGrant.Id, gaProgramme3.Id);
		//ampi__Project_Geographic_Area__c pga2 = TestDataFactory.createPGA(projectGrant.Id, gaProgramme2.Id);

		TestDataFactory.updateProgrammeStatus(gaProgramme, false);

		Test.startTest();
		System.debug('###projectGrant values: ' + projectGrant);
		System.debug('###projectGrant.Id: ' + projectGrant.id);

		List<customRelatedLists.RelatedPGAListWrapper> pgas = customRelatedLists.getProjectGeographicAreaByProjectId(projectGrant.id, 100, 0);
		System.assertEquals(2, pgas.size());
		Test.stopTest();
	}

	
	@isTest
	private static void getProjectGeographicAreaByProjectId_ForGrantProject() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao 2', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima 2', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme3 = TestDataFactory.createProgramme('Areq 2', gaCountry.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		ampi__Project__c projectGrant = TestDataFactory.createProject('Grant', accNA.Id, gaProgramme.Id, 'FS, YC');
		ampi__Project_Geographic_Area__c pga = TestDataFactory.createPGA(projectGrant.Id, gaProgramme2.Id);
		ampi__Project_Geographic_Area__c pga2 = TestDataFactory.createPGA(projectGrant.Id, gaProgramme3.Id);

		Test.startTest();
		System.debug('###projectGrant values: ' + projectGrant);
		System.debug('###projectGrant.Id: ' + projectGrant.id);

		List<customRelatedLists.RelatedPGAListWrapper> pgas = customRelatedLists.getProjectGeographicAreaByProjectId(projectGrant.id, 100, 0);
		System.assertEquals(3, pgas.size());
		Test.stopTest();
	}


	@isTest
	private static void getProjectsByOrganisationId_OrganisationId() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao 3', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima 3', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme3 = TestDataFactory.createProgramme('Areq 3', gaCountry.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		ampi__Project__c projectGrant = TestDataFactory.createProject('Grant', accNA.Id, gaProgramme.Id, 'FS, YC');
		ampi__Project__c projectGrant2 = TestDataFactory.createProject('Grant', accNA.Id, gaProgramme.Id, 'FS, YC');
		ampi__Project__c projectGrant3 = TestDataFactory.createProject('Grant', accNA.Id, gaProgramme.Id, 'FS, YC');

		ampi__Project_Geographic_Area__c pga = TestDataFactory.createPGA(projectGrant.Id, gaProgramme2.Id);
		ampi__Project_Geographic_Area__c pga2 = TestDataFactory.createPGA(projectGrant2.Id, gaProgramme3.Id);

		Test.startTest();
		System.debug('###projectGrant values: ' + projectGrant);
		System.debug('###projectGrant.Id: ' + projectGrant.id);

		List<customRelatedLists.RelatedProjectListWrapper> projects = customRelatedLists.getProjectsByOrganisationId(accNA.Id, 100, 0);
		System.assertEquals(3, projects.size());
		Test.stopTest();
	}

	
	@isTest
	private static void getGeographicAreaByAccountId() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		Test.startTest();
		List<customRelatedLists.RelatedGAListWrapper> geographicAreas = customRelatedLists.getGeographicAreaByAccountId(accNA.Id, true, true, true, 100, 0);
		System.assertEquals(2, geographicAreas.size());

		geographicAreas = customRelatedLists.getGeographicAreaByAccountId(accNA.Id, false, true, true, 100, 0);
		System.assertEquals(0, geographicAreas.size());
		Test.stopTest();
	}
	
	@isTest
	private static void getDescriptionRiskDatafieldName_CountTwoAccounts() {
		User u = TestDataFactory.CreateUserFromSystemAdminSpanish();
		System.runAs(u) {
			String spa= customRelatedLists.getDescriptionRiskDatafieldName();
			System.assert(spa == 'Risk_Description_Language_1__c');
		}
		u = TestDataFactory.CreateUserFromSystemAdminFrench();
		System.runAs(u) {
			String fra= customRelatedLists.getDescriptionRiskDatafieldName();
			System.assert(fra == 'Risk_Description_Language_2__c');
		}
		u = TestDataFactory.CreateUserFromSystemAdminRussian();
		System.runAs(u) {
			String rus= customRelatedLists.getDescriptionRiskDatafieldName();
			System.assert(rus == 'Risk_Description_Language_3__c');
		}
		u = TestDataFactory.CreateUserFromSystemAdmin();
		System.runAs(u) {
			String eng= customRelatedLists.getDescriptionRiskDatafieldName();
			System.assert(eng == 'ampi__Description__c');
		}
	}

	@isTest
	private static void getRisksByProgrammeId_CountTwoAccounts_NotIncludingSafety() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		TestDataFactory.createRisk('Name 1', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 2', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 3', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 4', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 5', gaProgramme.Id, accNA.Id, false, '');
		TestDataFactory.createRisk('Name 6', gaProgramme.Id, accNA.Id, false, '');
		List<SObject> spa= customRelatedLists.getRisksByProgrammeId(gaProgramme.Id, '', false, 0, 0);
		System.assert(spa.size() == 2);
	}

	@isTest
	private static void getRisksByProgrammeId_CountTwoAccounts_IncludingSafety() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		TestDataFactory.createRisk('Name 1', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 2', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 3', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 4', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 5', gaProgramme.Id, accNA.Id, false, '');
		TestDataFactory.createRisk('Name 6', gaProgramme.Id, accNA.Id, false, '');
		List<SObject> spa= customRelatedLists.getRisksByProgrammeId(gaProgramme.Id, '', true, 0, 0);
		System.assert(spa.size() == 4);
	}

	@isTest
	private static void getNumberRisksByProgrammeId_CountTwoAccounts_IncludingSafety() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		TestDataFactory.createRisk('Name 1', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 2', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 3', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 4', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 5', gaProgramme.Id, accNA.Id, false, '');
		TestDataFactory.createRisk('Name 6', gaProgramme.Id, accNA.Id, false, '');
		Integer spa= customRelatedLists.getNumberRisksByProgrammeId(gaProgramme.Id, '', true);
		System.assert(spa == 4);
	}

	@isTest
	private static void getNumberRisksByProgrammeId_CountTwoAccounts_NotIncludingSafety() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		TestDataFactory.createRisk('Name 1', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 2', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 3', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 4', gaProgramme.Id, accNA.Id, true, '');
		TestDataFactory.createRisk('Name 5', gaProgramme.Id, accNA.Id, false, '');
		TestDataFactory.createRisk('Name 6', gaProgramme.Id, accNA.Id, false, '');
		Integer spa= customRelatedLists.getNumberRisksByProgrammeId(gaProgramme.Id, '', false);
		System.assert(spa == 2);
	}

	@isTest
	private static void getMAName_ReturnNA_Peru() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		String spa= customRelatedLists.getMAName(accNA.Id);
		System.assert(spa == 'NA Peru');
	}
	
	
	@isTest
	private static void getRecordTypeIdByName_ReturnNotEmpty() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		String spa= customRelatedLists.getRecordTypeIdByName('Programme Location Risk');
		System.assert(String.isNotBlank(spa));
	}

	@isTest
	private static void isInternal_ReturnTrue() {
		Boolean result = customRelatedLists.isInternal();
		System.assert(result == true);
	}
	

	@isTest
	private static void getRisksByRiskRegisterId_CountSixRisks() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);

		TestDataFactory.createRiskRegister('Name 1', gaProgramme.Id);
		ampi__Risk_Register__c riskRegister = [SELECT Id FROM ampi__Risk_Register__c WHERE Name = 'Name 1' LIMIT 1];
		String riskRegisterId = riskRegister.Id;
		TestDataFactory.createRisk('Name 1', gaProgramme.Id, accNA.Id, true, riskRegisterId);
		TestDataFactory.createRisk('Name 2', gaProgramme.Id, accNA.Id, true, riskRegisterId);
		TestDataFactory.createRisk('Name 3', gaProgramme.Id, accNA.Id, true, riskRegisterId);
		TestDataFactory.createRisk('Name 4', gaProgramme.Id, accNA.Id, true, riskRegisterId);
		TestDataFactory.createRisk('Name 5', gaProgramme.Id, accNA.Id, false, riskRegisterId);
		TestDataFactory.createRisk('Name 6', gaProgramme.Id, accNA.Id, false, riskRegisterId);
		List<SObject> spa= customRelatedLists.getRisksByRiskRegisterId(riskRegisterId, '', 0, 0);
		System.assert(spa.size() == 6);
	}

	@isTest
	private static void getNumberOfRisksByRiskRegisterId_CountSixRisks() {
		Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);

		TestDataFactory.createRiskRegister('Name 1', gaProgramme.Id);
		ampi__Risk_Register__c riskRegister = [SELECT Id FROM ampi__Risk_Register__c WHERE Name = 'Name 1' LIMIT 1];
		String riskRegisterId = riskRegister.Id;
		TestDataFactory.createRisk('Name 1', gaProgramme.Id, accNA.Id, true, riskRegisterId);
		TestDataFactory.createRisk('Name 2', gaProgramme.Id, accNA.Id, true, riskRegisterId);
		TestDataFactory.createRisk('Name 3', gaProgramme.Id, accNA.Id, true, riskRegisterId);
		TestDataFactory.createRisk('Name 4', gaProgramme.Id, accNA.Id, true, riskRegisterId);
		TestDataFactory.createRisk('Name 5', gaProgramme.Id, accNA.Id, false, riskRegisterId);
		TestDataFactory.createRisk('Name 6', gaProgramme.Id, accNA.Id, false, riskRegisterId);
		Integer spa= customRelatedLists.getNumberOfRisksByRiskRegisterId(riskRegisterId, '');
		System.assert(spa == 6);
	}
	
	@isTest
	private static void getResultsQueryDynamic_CountTwoAccounts() {
		TestDataFactory.createOrganisation('');
		TestDataFactory.createOrganisation('');
		List<SObject> count = customRelatedLists.getResultsQueryDynamic('Account', 'Id, Name', '', 3, 0);
		System.assert(count.size() == 2);
	}


	@isTest
	private static void getNumberResultsQueryDynamic_CountTwoAccounts() {
		TestDataFactory.createOrganisation('');
		TestDataFactory.createOrganisation('');
		integer count = customRelatedLists.getNumberResultsQueryDynamic('Account', '');
		System.assert(count == 2);
	}
	
}