force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <inlineHelpText>Indicates whether unit or Programme is still active.</inlineHelpText>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/ampi__Type__c.field-meta.xml
<CustomField>
    <fullName>ampi__Type__c</fullName>
    <description>Picklist to specify the type of geographic area (Country/ State etc.)</description>
    <inlineHelpText>System defined. Amp Impact Indicator page (for adding a new indicator) looks at this field specifically in order to enable the behaviour of the custom page.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Programme</fullName>
            </value>
            <value>
                <fullName>Programme Unit</fullName>
            </value>
            <value>
                <fullName>National Management Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <inlineHelpText>Derived from LUCY Data: Region Code (3 digits), Country Code (2 Characters), Programme Code (10 digits), Programme Unit Code (R-code)</inlineHelpText>
    <label>Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Long_Name__c.field-meta.xml
<CustomField>
    <fullName>Long_Name__c</fullName>
    <inlineHelpText>Programme Unit Type (written in words) + Programme/Location</inlineHelpText>
    <label>Long Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Parent_MA__c.field-meta.xml
<CustomField>
    <fullName>Parent_MA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent MA for Programmes</inlineHelpText>
    <label>Parent MA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SOS Organisation - MA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programmes &amp; Programme Units</relationshipLabel>
    <relationshipName>Programmes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Pillar__c.field-meta.xml
<CustomField>
    <fullName>Pillar__c</fullName>
    <formula>CASE(
LEFT((RIGHT(TEXT( Program_Unit_Type__c ), 3)),1)
,
&quot;1&quot;, &quot;Alternative Care (AC)&quot;, &quot;2&quot;, &quot;Family Strengthening (FS)&quot;,
&quot;3&quot;,&quot;Education&quot;,
&quot;4&quot;, &quot;Health&quot;,
&quot;5&quot;, &quot;Other&quot;,
&quot;6&quot;, &quot;Other&quot;,
&quot;9&quot;, &quot;Non-Programmatic&quot;
,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pillar</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Program_Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Unit_Type__c</fullName>
    <label>Programme Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Programme_Unit_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project</description>
    <inlineHelpText>Add description of your project (1024 char max), describe specific objectives. Include key words to ease the search (e.g. country, donor). The description can be changed and updated at any time and is shown on the Team Site.</inlineHelpText>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ampi__Start_Date__c</fullName>
    <description>Date field to specify the start date of the project</description>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/SOS_Implementing_Organisation__c.field-meta.xml
<CustomField>
    <fullName>SOS_Implementing_Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Mandatory field for status &quot;in identification&quot;.
Indicate which SOS organisation will implement the project. For Umbrella projects, select &quot;Global-multiple MAs&quot; and register sub-projects for each implementating organisation in a separate step.</inlineHelpText>
    <label>SOS Implementing Organisation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Only an SOS Organisation can be an Implementing Organisation.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>SOS Organisation - MA</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation - GSC Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funds (SOS Implementing Organisation)</relationshipLabel>
    <relationshipName>Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Geographic_Area__c</fullName>
    <description>Master-detail to specify parent geographic area</description>
    <label>Geographic Area</label>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Project Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Geographic_Area__c</fullName>
    <description>[NOT IN USE - Candidate for Deprecation]</description>
    <label>Project Geographic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Type__c.field-meta.xml
<CustomField>
    <fullName>ampi__Type__c</fullName>
    <description>This formula field prints the project geographic area type from the parent geographic area.</description>
    <formula>TEXT(ampi__Geographic_Area__r.ampi__Type__c)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Risk__c/ampi__Risk__c.object-meta.xml
<CustomObject>
    <description>Track conversations, decisions, and actions taken by an organization aimed at mitigating identified risks and managing risk events</description>
    <label>Risk</label>
    <nameField>
        <label>Risk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Risk__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Text field to describe Risk in detail</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Risk__c/fields/ampi__Risk_Register__c.field-meta.xml
<CustomField>
    <fullName>ampi__Risk_Register__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Risk Register which contains this Risk.</description>
    <label>Risk Register</label>
    <referenceTo>ampi__Risk_Register__c</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/ampi__Risk_Assessment__c.object-meta.xml
<CustomObject>
    <description>Monitor and reassess identified risks, identify new risks, and track risk events related to projects/grants for evaluation</description>
    <label>Risk Assessment</label>
    <nameField>
        <label>Risk Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/National_Association__c.field-meta.xml
<CustomField>
    <fullName>National_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Association</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Risk Reviews: National Security Context</relationshipLabel>
    <relationshipName>Risk_Reviews_National_Association</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Waiting for approval</fullName>
            </value>
            <value>
                <fullName>Aligned</fullName>
            </value>
            <value>
                <fullName>Revision needed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Risk_Register__c/ampi__Risk_Register__c.object-meta.xml
<CustomObject>
    <description>Track risks associated with projects/grants so staff can have better visibility into identified risks across a portfolio</description>
    <label>Risk Register</label>
    <nameField>
        <label>Risk Register Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Risk_Register__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Risk Registers must be associated with a Project so that grant-makers can, at the grant/project-level, make decisions on the grant/project based on the related Risks.</description>
    <inlineHelpText>Associated with a Project with a Risk Register so that grant-makers can, at the grant/project-level, make decisions on the grant/project based on the related Risks</inlineHelpText>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Risk Registers</relationshipLabel>
    <relationshipName>Risk_Registers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Register__c/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ampi__Geographical_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Location Security Risk Assessments</relationshipLabel>
    <relationshipName>Risk_Registers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Risk_Register__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Waiting for approval</fullName>
            </value>
            <value>
                <fullName>Aligned</fullName>
            </value>
            <value>
                <fullName>Revision needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/customRelatedLists.cls
public without sharing class customRelatedLists  {

    @AuraEnabled(cacheable=true)
    public static String getRiskApproverAndReviewerByOrganisationId(String organisationId, Boolean includeProfile) {
        List<Account> soqlData = [SELECT NA_Risk_Reviewer__r.email, NA_Director__r.email
                FROM Account 
                WHERE Id =: organisationId];
        
        String result = '';
        for(Account currentRecord : soqlData) {
            if (currentRecord.NA_Risk_Reviewer__r.email == UserInfo.getUserEmail()) {
                result = 'Reviewer';
            }
            if (currentRecord.NA_Director__r.email == UserInfo.getUserEmail()) {
                result += '/Approver';
            }
        } 

        if (includeProfile) {
            String profileName = [SELECT Name FROM Profile WHERE Id =: UserInfo.getProfileId()].Name;
            result += '/' + profileName;
        }
        return result;
    }

    @AuraEnabled(cacheable=true)
    public static String getOrganisationIdByProgrammeId(String programmeId) {
        List<ampi__Geographical_Area__c> soqlData = [SELECT Parent_MA__c
                FROM ampi__Geographical_Area__c 
                WHERE Id =: programmeId];
        
        for(ampi__Geographical_Area__c currentRecord : soqlData) {
            return currentRecord.Parent_MA__c;
        } 

        return '';
    }

    @AuraEnabled(cacheable=true)
    public static List<RelatedPGAListWrapper> getProjectGeographicAreaByProjectId(String projectId, Integer maxRecords, Integer offSetCount) {
        List<ampi__Project_Geographic_Area__c> soqlData = [SELECT Id, ampi__Geographic_Area__r.ampi__Type__c,
                    ampi__Geographic_Area__r.Name, ampi__Geographic_Area__r.Active__c,
                    ampi__Geographic_Area__r.Long_Name__c, ampi__Geographic_Area__r.Pillar__c
                FROM ampi__Project_Geographic_Area__c 
                WHERE ampi__Project__r.Id =: projectId  AND ampi__Geographic_Area__r.Active__c = 'Yes'
                ORDER BY ampi__Geographic_Area__r.Name ASC LIMIT :maxRecords OFFSET :offSetCount];
        
        List<RelatedPGAListWrapper> data = new List<RelatedPGAListWrapper>();

        for(ampi__Project_Geographic_Area__c currentRecord : soqlData) {
            RelatedPGAListWrapper item = new RelatedPGAListWrapper(currentRecord);
            data.add(item);
        } 
        return data;
    }

    @AuraEnabled(cacheable=true)
    public static List<ampi__Risk_Register__c> getRiskRegisterByProgrammeId(String programmeId, Integer maxRecords, Integer offSetCount) {
        List<ampi__Risk_Register__c> soqlData = [SELECT Name, Status__c, Programme__r.Parent_MA__c FROM ampi__Risk_Register__c 
                WHERE Programme__c =: programmeId
                ORDER BY Name ASC 
                LIMIT :maxRecords OFFSET :offSetCount];
        
        return soqlData;
    }

    @AuraEnabled(cacheable=true)
    public static List<ampi__Risk_Assessment__c> getRiskAssessmentByMAId(String maId, Integer maxRecords, Integer offSetCount) {
        List<ampi__Risk_Assessment__c> soqlData = [SELECT Name, Status__c, National_Association__c FROM ampi__Risk_Assessment__c 
                WHERE National_Association__c =: maId
                ORDER BY Name ASC 
                LIMIT :maxRecords OFFSET :offSetCount];
        
        return soqlData;
    }


    @AuraEnabled(cacheable=true)
    public static List<RelatedProjectListWrapper> getProjectsByOrganisationId(String organisationId, Integer maxRecords, Integer offSetCount) {

        Id profileId= userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        List<ampi__Project__c> soqlData= null;

        if(profileName == 'System Administrator') {
            soqlData = [SELECT Id, Name ,ampi__Description__c, RecordType.Name, ampi__Start_Date__c
                    FROM ampi__Project__c 
                    WHERE SOS_Implementing_Organisation__c =: organisationId LIMIT :maxRecords OFFSET :offSetCount];
        } else {
           soqlData = [SELECT Id, Name ,ampi__Description__c, RecordType.Name, ampi__Start_Date__c
                    FROM ampi__Project__c 
                    WHERE SOS_Implementing_Organisation__c =: organisationId
                    and RecordType.Name <> 'Shadow Project' LIMIT :maxRecords OFFSET :offSetCount];
        }
        
        boolean isInternalLink = isInternal();

        List<RelatedProjectListWrapper> data = new List<RelatedProjectListWrapper>();

        for(ampi__Project__c currentRecord : soqlData) {
            RelatedProjectListWrapper item = new RelatedProjectListWrapper(currentRecord, isInternalLink);
            data.add(item);
        } 
            
        return data;
    }

    @AuraEnabled(cacheable=true)
    public static List<RelatedGAListWrapper> getGeographicAreaByAccountId(String accountId, Boolean programmesVisible, Boolean programmeUnitsVisible, Boolean nationalManagementUnitsVisible, Integer maxRecords, Integer offSetCount) {
        List<ampi__Geographical_Area__c> soqlData = [SELECT Id, ampi__Type__c,
                        Code__c, Name, Program_Unit_type__c, Active__c
                    FROM ampi__Geographical_Area__c 
                    WHERE Parent_MA__c =: accountId AND Active__c = 'Yes'
                    ORDER BY ampi__Type__c ASC, Name ASC
                    LIMIT :maxRecords OFFSET :offSetCount];
        
        List<RelatedGAListWrapper> data = new List<RelatedGAListWrapper>();
        String MAName = getMAName(accountId);
        boolean isInternalLink = isInternal();

        while (soqlData.size() > 0) {
            List<Id> ids = new List<Id>();
            for(ampi__Geographical_Area__c currentRecord : soqlData) {
                    if ((programmesVisible == true && currentRecord.ampi__Type__c == 'Programme') || 
                        (programmeUnitsVisible == true && currentRecord.ampi__Type__c == 'Programme Unit') ||
                        (nationalManagementUnitsVisible == true && currentRecord.ampi__Type__c == 'National Management Unit')) {
                        RelatedGAListWrapper item = new RelatedGAListWrapper(currentRecord, isInternalLink);
                        item.ParentId = accountId;
                        if (!isInternalLink) {
                            item.ParentNameUrl = '/geographical-area/' + accountId;
                        } else {
                            item.ParentNameUrl = '/lightning/r/ampi__Geographical_Area__c/' + accountId + '/view/';
                        }
                        item.ParentName = MAName;
                        data.add(item);
                        ids.add(currentRecord.ID);
                    }
            }

            soqlData = [SELECT Id, ampi__Type__c,
                        Code__c, Name, Program_Unit_type__c, Active__c
                    FROM ampi__Geographical_Area__c 
                    WHERE Parent_MA__c IN: ids AND Active__c = 'Yes'
                    ORDER BY ampi__Type__c ASC, Name ASC];
        }
        return data;
    }

    @AuraEnabled(cacheable=true)
    public static String getDescriptionRiskDatafieldName() {
        User u = [SELECT toLabel(LanguageLocaleKey) FROM User WHERE Id = :UserInfo.getUserId()];        
        //User u = [SELECT FirstName FROM User WHERE Id = :UserInfo.getUserId()];        
        
        //String shortLanguageCode = u.FirstName; 
        String shortLanguageCode = u.LanguageLocaleKey.trim();    
        if (shortLanguageCode == 'Español') {
              return 'Risk_Description_Language_1__c';
        } else if (shortLanguageCode == 'Français') {
              return 'Risk_Description_Language_2__c';
        } else if (shortLanguageCode == 'Русский') {
              return 'Risk_Description_Language_3__c';
        } else {
            return 'ampi__Description__c';
        }
        //return 'ampi__Description__c';
    }
    
    @AuraEnabled(cacheable=true)
    public static List<SObject> getRisksByProgrammeId(String programmeId, String category, Boolean includeCatalogueRisk, Integer maxRecords, Integer offSetCount) {
        //List<RelatedRiskListWrapper> data = new List<RelatedRiskListWrapper>();
        List<SObject> data = new List<SObject>();
        string description_field = getDescriptionRiskDatafieldName();

        string fields = 'Id, ' + description_field + ', toLabel(ampi__Category__c), Risk_Value__c, Risk_Name_Translated__c, Probability_Value__c, Impact_Value__c ';
        string filters = ' Programme_Location__c = \'' + programmeId + '\'';
        string catalogueSafety = 'Safety and Security Risks';

        if (includeCatalogueRisk == true) {
            filters += ' AND Catalogue_Type__c = \''  + catalogueSafety + '\'';
        } else {
            filters += ' AND Catalogue_Type__c <> \''  + catalogueSafety + '\'';
        }   

        if (!String.isBlank(category)) {
            filters += ' AND ampi__Category__c = \'' + category + '\'';
        }
        
        try {
            data = getResultsQueryDynamicWithSorting('ampi__Risk__c',fields,filters,maxRecords,offSetCount, 'Risk_Name_Translated__c ASC');
        }
        catch(DmlException e) 
        {
            System.debug('#### ERROR: ' + e.getMessage());
        }
        return data;
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getRisksByRiskRegisterId(String riskRegisterId, String category, Integer maxRecords, Integer offSetCount) {
        List<SObject> data = new List<SObject>();
        string description_field = getDescriptionRiskDatafieldName();
        
        string fields = 'Id, ' + description_field + ', toLabel(ampi__Category__c), Risk_Value__c, Risk_Name_Translated__c, Probability_Value__c, Impact_Value__c ';
        string filters = ' ampi__Risk_Register__c = \'' + riskRegisterId + '\'';

        if (!String.isBlank(category)) {
            filters += ' AND ampi__Category__c = \'' + category + '\'';
        }
        
        try {
            data = getResultsQueryDynamicWithSorting('ampi__Risk__c', fields, filters, maxRecords, offSetCount, 'Risk_Name_Translated__c ASC');
        }
        catch(DmlException e) 
        {
            System.debug('#### ERROR: ' + e.getMessage());
        }
        return data;
    }
    
    @AuraEnabled(cacheable=true)
    public static integer getNumberOfRiskRegisterByProgrammeId(String programmeId) {
        integer totalCount = 0;
        string filters = ' Programme__c = \'' + programmeId + '\'';
        
        try {
            totalCount = getNumberResultsQueryDynamic('ampi__Risk_Register__c', filters);
        }
        catch(DmlException e) 
        {
            System.debug('#### ERROR: ' + e.getMessage());
        }
        return totalCount;
    }

    @AuraEnabled(cacheable=true)
    public static integer getNumberOfRiskAssessmentByMAId(String maId) {
        integer totalCount = 0;
        string filters = ' National_Association__c = \'' + maId + '\'';
        
        try {
            totalCount = getNumberResultsQueryDynamic('ampi__Risk_Assessment__c', filters);
        }
        catch(DmlException e) 
        {
            System.debug('#### ERROR: ' + e.getMessage());
        }
        return totalCount;
    }

    @AuraEnabled(cacheable=true)
    public static integer getNumberOfRisksByRiskRegisterId(String riskRegisterId, String category) {
        integer totalCount = 0;

        string filters = ' ampi__Risk_Register__c = \'' + riskRegisterId + '\'';
        
        if (!String.isBlank(category)) {
            filters += ' AND ampi__Category__c = \'' + category + '\'';
        }
        try {
            totalCount = getNumberResultsQueryDynamic('ampi__Risk__c', filters);
        }
        catch(DmlException e) 
        {
            System.debug('#### ERROR: ' + e.getMessage());
        }
        return totalCount;
    }

    @AuraEnabled(cacheable=true)
    public static integer getNumberRisksByProgrammeId(String programmeId, String category, Boolean includeCatalogueRisk) {
        integer totalCount = 0;

        string filters = ' Programme_Location__c = \'' + programmeId + '\'';
        string catalogueSafety = 'Safety and Security Risks';

        if (includeCatalogueRisk == true) {
            filters += ' AND Catalogue_Type__c = \''  + catalogueSafety + '\'';
        } else {
            filters += ' AND Catalogue_Type__c <> \''  + catalogueSafety + '\'';
        }   

        if (!String.isBlank(category)) {
            filters += ' AND ampi__Category__c = \'' + category + '\'';
        }
        
        try {
            totalCount = getNumberResultsQueryDynamic('ampi__Risk__c',filters);
        }
        catch(DmlException e) 
        {
            System.debug('#### ERROR: ' + e.getMessage());
        }
        return totalCount;
    }

    @AuraEnabled(cacheable=true)
    public static String getMAName(String accountId) {
        List<Account> soqlData = [SELECT Name
                FROM Account 
                WHERE Id =: accountId];
        
        for(Account currentRecord : soqlData) {
            return currentRecord.Name;
        } 
        return '';
    }

    @AuraEnabled(cacheable=true)
    public static String getRecordTypeIdByName(String name) {
        List<RecordType> soqlData = [SELECT id from RecordType where Name =: name];
        
        for(RecordType currentRecord : soqlData) {
            return currentRecord.id;
        } 
        return '';
    }
    
    @AuraEnabled(cacheable=true)
    public static Boolean isInternal() {
        System.debug('####URL.getSalesforceBaseUrl().toExternalForm():' + URL.getSalesforceBaseUrl().toExternalForm());
        return URL.getSalesforceBaseUrl().toExternalForm().contains('.salesforce.com');
    }

    public static List<sObject> getResultsQueryDynamic(String objectName, String datafields, String filters, integer limitNumber, integer offsetCount) {
        String query = 'SELECT ' + datafields + ' FROM ' + objectName + ' '; 
        String whereClause = '';
        if (String.isNotEmpty(filters)) {
            if (String.isNotEmpty(filters)){
                whereClause += filters;
            }

            if (String.isNotEmpty(whereClause)) {
                query += ' WHERE ' + whereClause;
            }

            if (limitNumber > 0) {
                query += ' LIMIT ' + limitNumber;
            }

            if (offsetCount > 0) {
                query += ' OFFSET ' + offsetCount;
            }
        }
        System.debug('##### QUERY: ' + query);
        return Database.query(query);
    }

    public static List<sObject> getResultsQueryDynamicWithSorting(String objectName, String datafields, String filters, integer limitNumber, integer offsetCount, string sortedBy) {
        String query = 'SELECT ' + datafields + ' FROM ' + objectName + ' '; 
        String whereClause = '';
        if (String.isNotEmpty(filters)) {
            if (String.isNotEmpty(filters)){
                whereClause += filters;
            }

            if (String.isNotEmpty(whereClause)) {
                query += ' WHERE ' + whereClause;
            }

            if (String.isNotEmpty(sortedBy)) {
                query += ' ORDER BY ' + sortedBy;
            }

            if (limitNumber > 0) {
                query += ' LIMIT ' + limitNumber;
            }

            if (offsetCount > 0) {
                query += ' OFFSET ' + offsetCount;
            }
        }
        System.debug('##### QUERY: ' + query);
        return Database.query(query);
    }

    public static integer getNumberResultsQueryDynamic(String objectName, String filters) {
        String query = 'SELECT Count() FROM ' + objectName + ' '; 
        String whereClause = '';
        if (String.isNotEmpty(filters)) {
            if (String.isNotEmpty(filters)){
                whereClause += filters;
            }

            if (String.isNotEmpty(whereClause)) {
                query += ' WHERE ' + whereClause;
            }
        }
        System.debug('##### QUERY: ' + query);
        return Database.countQuery(query);
    }
    
    public class RelatedPGAListWrapper{
        @AuraEnabled
        public String Name { get; set;}
        @AuraEnabled
        public String LongName  { get; set;}
        @AuraEnabled 
        public Boolean IsActive { get; set;}
        @AuraEnabled
        public String Type { get; set;}
        @AuraEnabled
        public String Pillar { get; set;}
        @AuraEnabled
        public String ID { get; set;}
        public RelatedPGAListWrapper(ampi__Project_Geographic_Area__c record){
            this.Name = record.ampi__Geographic_Area__r.Name;
            this.LongName = record.ampi__Geographic_Area__r.Long_Name__c;
            this.IsActive = (record.ampi__Geographic_Area__r.Active__c == 'Yes');
            this.Type = record.ampi__Geographic_Area__r.ampi__Type__c;
            this.Pillar = record.ampi__Geographic_Area__r.Pillar__c;
            this.ID = record.ID;
        }
    }

    public class RelatedGAListWrapper{
        @AuraEnabled
        public String Name { get; set;}
        @AuraEnabled
        public String NameUrl { get; set;}
        @AuraEnabled
        public String LongName  { get; set;}
        @AuraEnabled 
        public String ParentId  { get; set;}
        @AuraEnabled
        public String ParentName  { get; set;}
        @AuraEnabled
        public String ParentNameUrl  { get; set;}
        @AuraEnabled
        public Boolean IsActive { get; set;}
        @AuraEnabled
        public String Type { get; set;}
        @AuraEnabled
        public String ProgramUnitType { get; set;}
        @AuraEnabled
        public String ID { get; set;}

        public RelatedGAListWrapper(ampi__Geographical_Area__c record, boolean isInternalLink){
            this.Name = record.Name;
            if (!isInternalLink) {
                this.NameUrl = '/geographical-area/' + record.ID;
            } else {
                this.NameUrl = '/lightning/r/ampi__Geographical_Area__c/' + record.ID + '/view/';
            }
            this.LongName = record.Code__c + ' ' + record.Name;
            this.IsActive = (record.Active__c == 'Yes');
            this.Type = record.ampi__Type__c;
            this.ProgramUnitType = record.Program_Unit_type__c;
            this.ID = record.ID;
        }
    }

    public class RelatedProjectListWrapper{
        @AuraEnabled
        public String Name { get; set;}
        @AuraEnabled
        public String NameUrl { get; set;}
        @AuraEnabled
        public String ID { get; set;}
        @AuraEnabled
        public String Description  { get; set;}
        @AuraEnabled
        public Date ProjectStartDate  { get; set;}

        public RelatedProjectListWrapper(ampi__Project__c record, boolean isInternalLink){
            this.Name = record.Name;
            if (!isInternalLink) {
                this.NameUrl = '/project/' + record.ID;
            } else {
                this.NameUrl = '/lightning/r/ampi__Project__c/' + record.ID + '/view/';
            }
            this.Description = record.ampi__Description__c;
            this.ProjectStartDate   =record.ampi__Start_Date__c;
        }
    }
}