force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/ampi__Parent_Geographical_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Parent_Geographical_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to relate a geographic area to its parent and create a hierarchy of geographic areas.</description>
    <label>Parent Geographic Area</label>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Child Geographic Areas</relationshipLabel>
    <relationshipName>Related_Geographical_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Continent__c.field-meta.xml
<CustomField>
    <fullName>Continent__c</fullName>
    <label>Continent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>America</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Oceania</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>To be defined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Extent_Information__c.field-meta.xml
<CustomField>
    <fullName>Extent_Information__c</fullName>
    <label>Extent Information</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Programme ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/recordTypes/Country.recordType-meta.xml
<RecordType>
    <fullName>Country</fullName>
    <active>true</active>
    <label>Country</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Project ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Programme_Location__c.field-meta.xml
<CustomField>
    <fullName>Programme_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the programme location for your project.</inlineHelpText>
    <label>Programme Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Programme for this field, not a Programme Unit, Country or Region.</errorMessage>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Projects in this Programme Location</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/ampi__Project_Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Junction linking a project to a thematic area</description>
    <label>Project Thematic Area</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Project Thematic Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Thematic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>This master-detail field refers to the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Thematic Areas</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Thematic_Area__c</fullName>
    <description>This master-detail field refers to the parent thematic area</description>
    <label>Thematic Area</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Related Projects</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Service Type ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Only existing</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
                <isActive>false</isActive>
                <label>Temporarily closed for international sponsorship</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/PU_Extent_Information__c.field-meta.xml
<CustomField>
    <fullName>PU_Extent_Information__c</fullName>
    <label>PU Extent Information</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GeographicAreaTriggerHandlerTest.cls
@isTest
private class GeographicAreaTriggerHandlerTest {
    @isTest 
    static void beforeInsertGeographicalAreaCountry_DuplicateCodeValue() {
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Test.startTest();
		try {
		    ampi__Geographical_Area__c gaCountry2 = TestDataFactory.createCountry('Peru 2', gaRegion.Id);			
        }catch(Exception ex) {
            if (ex.getMessage().contains('Country code must be unique')) {
                System.assert(true);
            }
        }		
		
		Test.stopTest();        
	}

    @isTest 
    static void beforeInsertGeographicalAreaCountry_NoCodeValue() {
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		Test.startTest();
		try {
		    ampi__Geographical_Area__c gaCountry = new ampi__Geographical_Area__c();
            gaCountry.Name = 'Peru';
            gaCountry.ampi__Parent_Geographical_Area__c = gaRegion.Id;
            gaCountry.Continent__c = 'South America';
            gaCountry.RecordTypeId = ampi__Geographical_Area__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('Country').getRecordTypeId();
            insert gaCountry;
        }catch(Exception ex) {
            if (ex.getMessage().contains('Country code must have 3 characters')) {
                System.assert(true);
            }
        }		
		
		Test.stopTest();        
	}

    @isTest 
    static void beforeUpdateGeographicalAreaISPAvailable_CheckRelatedProject_PTAISPAvailable_NoValue() {
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YCA', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FSA', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
		
		TestDataFactory.createProjectThematicAreaWithISP(projectStandard.Id, thematicAreaYC.Id, '', 'No');
		TestDataFactory.createProjectThematicAreaWithISP(projectStandard.Id, thematicAreaFS.Id, '', 'No');

		Test.startTest();
		try {
			gaProgramme.ISP_Available__c = 'No';
        	UPDATE projectStandard;    
        }catch(Exception ex) {
        }		
		//TODO: comented because of ticket AMIMSP-2043
		//List<ampi__project__c> projs = [SELECT Id FROM ampi__project__c WHERE programme_location__c =: gaProgramme.Id AND ISP_Available__c = 'No' AND RecordType.Name IN ('Standard', 'Transition')];
		//List<ampi__project_thematic_area__c> ptas = [SELECT Id FROM ampi__project_thematic_area__c WHERE ampi__Project__c IN :projs AND ISP_Available__c = 'No'];
		//System.assert(projs.size() > 0 && ptas.size() > 0);        
		System.Assert(true);
		Test.stopTest();        
	}

    @isTest 
    static void beforeProjectServiceTypeUpdate_ExtentInformationUpdated() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Child Money Gift');
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        
        Test.startTest();
        gaProgrammeUnit.Extent_Information__c = 'Extent_Information__c was changed';
        UPDATE gaProgrammeUnit;
        ampi__project_thematic_area__c ptaUpdated = [SELECT Id, PU_Extent_Information__c FROM ampi__project_thematic_area__c WHERE Id =: pta.Id LIMIT 1];
        System.debug('####ptaUpdated:' + ptaUpdated);
        System.assert(ptaUpdated.PU_Extent_Information__c == 'Extent_Information__c was changed');
        Test.stopTest();        
    }

	@isTest 
    static void beforeProjectServiceTypeUpdate_ExtentInformationUpdated_DifferentISP() {
    	// Account accNA = TestDataFactory.createMA('NA Peru');
		// ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Child Money Gift');

        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);

		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);

		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC2', 'Youth Care (similar to YF)');
		
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectStandard.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        
        Test.startTest();
        gaProgrammeUnit.ISP_Available__c = 'Yes';
        UPDATE gaProgrammeUnit;

		gaProgrammeUnit.ISP_Available__c = 'No';
        UPDATE gaProgrammeUnit;

        ampi__project_thematic_area__c ptaUpdated = [SELECT Id, ISP_Available__c, PU_Extent_Information__c FROM ampi__project_thematic_area__c WHERE Id =: pta.Id LIMIT 1];
        System.debug('####ptaUpdated:' + ptaUpdated);
        System.assert(ptaUpdated.ISP_Available__c == 'No');
        Test.stopTest();        
    }
}