force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Indicator__c/ampi__Indicator__c.object-meta.xml
<CustomObject>
    <description>Catalog indicators that can be used to track progress against goals for a range of projects</description>
    <label>Indicator</label>
    <nameField>
        <displayFormat>IND-{00000}</displayFormat>
        <label>Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Indicator__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to relevant project record if the indicator is only added to a specific project and not the indicator catalog</description>
    <label>Specific Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Indicators</relationshipLabel>
    <relationshipName>Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Indicator__c/fields/ampi__Type_of_Results__c.field-meta.xml
<CustomField>
    <fullName>ampi__Type_of_Results__c</fullName>
    <description>Picklist to specify how the results are being generated, i.e. inputted, aggregated over source records, or calculated using the results from other indicators</description>
    <label>Type of Results</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Input</fullName>
                <default>true</default>
                <label>Input</label>
            </value>
            <value>
                <fullName>Aggregated</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Indicator__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Participants</fullName>
            </value>
            <value>
                <fullName>Former participants</fullName>
            </value>
            <value>
                <fullName>Households</fullName>
            </value>
            <value>
                <fullName>Former households</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>Children &amp; Young People</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Indicator__c/fields/Source_Document__c.field-meta.xml
<CustomField>
    <fullName>Source_Document__c</fullName>
    <label>Source Document</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Statistics Handbook V3</fullName>
                <default>true</default>
                <label>Statistics Handbook V3</label>
            </value>
            <value>
                <fullName>2030 Measures Project</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
            <value>
                <fullName>Case Management and SDGs Indicators Monitored in PDB2</fullName>
            </value>
            <value>
                <fullName>SOS Care Promise Indicators Booklet</fullName>
            </value>
            <value>
                <fullName>Case Management and SDGs Indicators Monitored in PDB3</fullName>
            </value>
            <value>
                <fullName>Statistics Handbook Version Nov 2017</fullName>
            </value>
            <value>
                <fullName>Statistics Handbook Version 3 2022</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Indicator__c/ampi__Project_Indicator__c.object-meta.xml
<CustomObject>
    <description>Junction linking a catalog indicator to a project</description>
    <label>Project Indicator</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Project Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Catalog_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Catalog_Indicator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to specify the parent catalog indicator. This field must be populated for several of the formula fields on Project Indicator to print correctly (e.g. Data Type).</description>
    <label>Related Indicator</label>
    <referenceTo>ampi__Indicator__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Project this project indicator belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Project_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Type_of_Results__c.field-meta.xml
<CustomField>
    <fullName>ampi__Type_of_Results__c</fullName>
    <defaultValue>&quot;Input&quot;</defaultValue>
    <description>Picklist field to select whether the results for this project indicator should be input manually, calculated from the results of other project indicators, or aggregated from individual-level data. The value in this field determines whether results are displayed as input or output text on AddResults and whether the user can access the popups for either the Aggregation Criteria or the Calculation Formula.</description>
    <inlineHelpText>Select whether the results for this Project Indicator should be input manually, calculated from the results of other indicators, or aggregated from individual-level data.</inlineHelpText>
    <label>Type of Results</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Input</fullName>
            </value>
            <value>
                <fullName>Aggregated</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectIndicatorTriggerHandlerTest.cls
@isTest
public class ProjectIndicatorTriggerHandlerTest {
    @isTest 
    static void afterInsertProjectIndicators_SetTypeResultAggregated_ReturnsProjectIndicatorsAggregated() {
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 		accNA.Is_PDB_In_Use__c = 'Yes';
        UPDATE accNA;
            
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
		ampi__Project_Indicator__c pi =  TestDataFactory.createProjectIndicator('indicatorName Test', projectStandard.Id, 'Statistics Handbook V3');

        Test.startTest();
        List<ampi__project_indicator__c> pis = [SELECT Id, ampi__Type_of_Results__c FROM ampi__project_indicator__c WHERE ampi__Catalog_Indicator__r.Source_Document__c = 'Statistics Handbook V3' AND ampi__Catalog_Indicator__r.Level__c <> 'Staff' AND ampi__Type_of_Results__c = 'Aggregated'];
        System.assert(pis.size() > 0);

        Test.stopTest();
	}
}