force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Geographic_Area__c</fullName>
    <description>[NOT IN USE - Candidate for Deprecation]</description>
    <label>Project Geographic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator__c/ampi__Project_Indicator__c.object-meta.xml
<CustomObject>
    <description>Junction linking a catalog indicator to a project</description>
    <label>Project Indicator</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Project Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Project this project indicator belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Project Indicators</relationshipLabel>
    <relationshipName>Project_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator_Geographic_Area__c/ampi__Project_Indicator_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project indicator</description>
    <label>Project Indicator Geographic Area</label>
    <nameField>
        <displayFormat>PIGA-{0000}</displayFormat>
        <label>Project Indicator Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicator Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator_Geographic_Area__c/fields/ampi__Project_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify parent project indicator. This field determines what Project Indicator is being updated by the trigger on Project Indicator Geographic Area.</description>
    <label>Project Indicator</label>
    <referenceTo>ampi__Project_Indicator__c</referenceTo>
    <relationshipLabel>Project Indicator Geographic Areas</relationshipLabel>
    <relationshipName>Project_Indicator_Geographic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator_Reporting_Period__c/ampi__Project_Indicator_Reporting_Period__c.object-meta.xml
<CustomObject>
    <description>A period of time for which a project indicator has targets set and results reported</description>
    <label>Project Indicator Reporting Period</label>
    <nameField>
        <displayFormat>PIRP-{0000}</displayFormat>
        <label>Project Indicator Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicator Reporting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator_Reporting_Period__c/fields/ampi__Project_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the parent project indicator</description>
    <label>Project Indicator</label>
    <referenceTo>ampi__Project_Indicator__c</referenceTo>
    <relationshipLabel>Project Indicator Reporting Periods</relationshipLabel>
    <relationshipName>Project_Indicator_Reporting_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator_Reporting_Period__c/fields/ampi__Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the parent reporting period</description>
    <label>Reporting Period</label>
    <referenceTo>ampi__Reporting_Period__c</referenceTo>
    <relationshipLabel>Project Indicator Reporting Periods</relationshipLabel>
    <relationshipName>Project_Indicator_Reporting_Periods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/ampi__Reporting_Period__c.object-meta.xml
<CustomObject>
    <description>A period of time for which a project&apos;s targets must be set and results reported</description>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Reporting Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Project to which a Reporting Period belongs</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Reporting Periods</relationshipLabel>
    <relationshipName>Project_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Result__c/ampi__Result__c.object-meta.xml
<CustomObject>
    <description>Target and result values for a specific reporting period, project area, project indicator, and disaggregation value</description>
    <label>Result</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Result ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Result__c/fields/ampi__Geographical_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Geographical_Area__c</fullName>
    <description>This formula field copies geographical area from parent project indicator geographic area</description>
    <formula>ampi__Project_Indicator_Geographic_Area__r.ampi__Geographic_Area__r.ampi__Name_Translated__c</formula>
    <label>Geographical Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Result__c/fields/ampi__Project_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator__c</fullName>
    <description>Describes the Indicator for which Results and Targets are captured</description>
    <label>Project Indicator</label>
    <referenceTo>ampi__Project_Indicator__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Project_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Result__c/fields/ampi__Project_Indicator_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator_Geographic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup field is to specify the project indicator geographic area</description>
    <label>Project Indicator Geographic Area</label>
    <referenceTo>ampi__Project_Indicator_Geographic_Area__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Result__c/fields/ampi__Project_Indicator_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator_Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup field is to specify the projct indicator reporting period</description>
    <label>Project Indicator Reporting Period</label>
    <referenceTo>ampi__Project_Indicator_Reporting_Period__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ResultTriggerHandlerTest.cls
@isTest
private class ResultTriggerHandlerTest {
    @isTest
    private static void beforeInsertUpdateResultsInCommunityProfiles_CheckIfPossibleToSaveWithCommunityUser_ControllingException() {
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('New Programme Unit based on Callao', gaProgramme.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
		ampi__Reporting_Period__c mp = TestDataFactory.manageMonitoringPeriodByProjectAndFrequency(projectStandard.Id, 'Monthly');
        // ampi__Project_Geographic_Area__c pga = TestDataFactory.createPGA(projectStandard.Id, gaProgramme.Id);
        // ampi__Project_Geographic_Area__c pga = TestDataFactory.createPGA(projectStandard.Id, gaProgrammeUnit.Id);

        ampi__Project_Indicator__c pi1 = TestDataFactory.createProjectIndicator('Indicator 1', projectStandard.Id);
        ampi__Project_Indicator__c pi2 = TestDataFactory.createProjectIndicator('Indicator 2', projectStandard.Id);
        
        List<ampi__project_indicator_reporting_period__c> pirps = TestDataFactory.generatePIRPsByProjectId(projectStandard.Id);
        List<ampi__project_indicator_geographic_area__c> pigas = TestDataFactory.generatePIGAsByProjectId(projectStandard.Id);

		Test.startTest();

        User newUser = TestDataFactory.CreateUserFromSystemAdminByAlias('xxzzzccc');
        //Team_member__c tm = TestDataFactory.createTeammember(projectStandard.Id, newUser.Id, 'Project Contributor', accNA.Id);        
        Team_member__c tm = TestDataFactory.createTeammember(projectStandard.Id, newUser.Id, 'YouthCan! Partner', accNA.Id);                

        System.runAs(newUser) {
            try {
                ampi__result__c res = TestDataFactory.createReults(30, pirps[0].Id, pigas[0].Id, pi1.Id);
                INSERT res;    
                
                if (res.Id == null) {
                    System.assert(false);
                    return;
                }
            }catch(Exception ex) {
                Boolean expectedExceptionThrown = ex.getMessage().contains('INSUFFICIENT_ACCESS_OR_READONLY') ? true : false;
                if (expectedExceptionThrown) {
                    System.assert(false);
                    return;
                }
            }
        }		
		
		System.assert(true);
        Test.stopTest();        
	}


    @isTest
    private static void beforeInsertUpdateResultsInCommunityProfiles_CheckIfPossibleToSaveWithCommunityUser_ThrowsException() {
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('New Programme Unit based on Callao', gaProgramme.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
		ampi__Reporting_Period__c mp = TestDataFactory.manageMonitoringPeriodByProjectAndFrequency(projectStandard.Id, 'Monthly');
        
        ampi__Project_Indicator__c pi1 = TestDataFactory.createProjectIndicator('Indicator 1', projectStandard.Id);
        ampi__Project_Indicator__c pi2 = TestDataFactory.createProjectIndicator('Indicator 2', projectStandard.Id);
        
        List<ampi__project_indicator_reporting_period__c> pirps = TestDataFactory.generatePIRPsByProjectId(projectStandard.Id);
        List<ampi__project_indicator_geographic_area__c> pigas = TestDataFactory.generatePIGAsByProjectId(projectStandard.Id);

		Test.startTest();
        User newUser = TestDataFactory.CreateUserFromSystemAdminByAlias('xxzzzccc');
        
        System.runAs(newUser) {
            try {
                ampi__result__c res = TestDataFactory.createReults(30, pirps[0].Id, pigas[0].Id, pi1.Id);
                INSERT res;    
                if (res.Id == null) {
                    System.assert(true);
                    return;
                }
            }catch(Exception ex) {
                Boolean expectedExceptionThrown = ex.getMessage().contains('INSUFFICIENT_ACCESS_OR_READONLY') ? true : false;
                if (expectedExceptionThrown) {
                    System.assert(true);
                    return;
                }
            }
        }		
		
		System.assert(false);
        Test.stopTest();        
	}
    
}