force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/Programme_Location__c.field-meta.xml
<CustomField>
    <fullName>Programme_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the programme location for your project.</inlineHelpText>
    <label>Programme Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Programme for this field, not a Programme Unit, Country or Region.</errorMessage>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Projects in this Programme Location</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Active__c.field-meta.xml
<CustomField>
    <fullName>ampi__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to indicate if this project geographic area is active</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Geographic_Area__c</fullName>
    <description>Master-detail to specify parent geographic area</description>
    <label>Geographic Area</label>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Project Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project_Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Geographic_Area__c</fullName>
    <description>[NOT IN USE - Candidate for Deprecation]</description>
    <label>Project Geographic Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Thematic_Area__c/fields/ampi__Active__c.field-meta.xml
<CustomField>
    <fullName>ampi__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox field to specify if the thematic area is active</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/createPGAProgrammeTest.cls
@isTest
private  class createPGAProgrammeTest {
    @isTest
    private static void createPGAProgrammeTest_CreatingProgramme() {
        Test.startTest();
        
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('New Programme Unit based on Callao', gaProgramme.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
		List<Id> newProjectIds = new List<Id>();
        newProjectIds.add(projectStandard.Id);

        List<ampi__Project_Geographic_Area__c> pgas1 = [SELECT Id, ampi__geographic_area__c, ampi__Active__c FROM ampi__Project_Geographic_Area__c WHERE ampi__Project__c IN :newProjectIds];
        System.debug('####pgas 1: ' + pgas1);
        
        projectStandard.Programme_Location__c = gaProgramme2.Id;
        UPDATE projectStandard;
        
        //createPGAProgramme.createPGAProgramme(newProjectIds);   

        List<ampi__Project_Geographic_Area__c> pgas2 = [SELECT Id, ampi__geographic_area__c, ampi__Active__c FROM ampi__Project_Geographic_Area__c WHERE ampi__Project__c IN :newProjectIds];
        System.debug('####pgas 2: ' + pgas2);
        System.assert(pgas2.size() >= 2);
        
        projectStandard.Programme_Location__c = gaProgramme.Id;
        UPDATE projectStandard;
        
        List<ampi__Project_Geographic_Area__c> pgas3 = [SELECT Id, ampi__geographic_area__c, ampi__Active__c FROM ampi__Project_Geographic_Area__c WHERE ampi__Project__c IN :newProjectIds];
        System.debug('####pgas 3: ' + pgas3);
        System.assert(pgas3.size() >= 2);
        
        //createPGAProgramme.createPGAProgramme(newProjectIds);
        Test.stopTest();                
    }
}