force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/Account_Teams__c.field-meta.xml
<CustomField>
    <fullName>Account_Teams__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Organisation record which is populated here will be used as the basis for sharing this Project record with external users in the MA Portal. For Projects (Grants, Standard, Emergency) this should be the shadow Organisation record named like &quot;{Project ID} - External Project Team&quot;. For Programmes or NMUs, this should be the NA that they fall underneath.</description>
    <inlineHelpText>The Organisation record which is populated here will be used as the basis for sharing this Project record with external users in the MA Portal. For Projects (Grants, Standard, Emergency) this should be the shadow Organisation record named like &quot;{Project ID} - External Project Team&quot;. For Programmes or NMUs, this should be the NA that they fall underneath.</inlineHelpText>
    <label>External Project Team</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Account Team)</relationshipLabel>
    <relationshipName>Projects5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/createTeamMemberProjectTest.cls
@isTest
private class createTeamMemberProjectTest {
    @isTest
    private static void createTeammemberProject_CreatingACR() {
        Test.startTest();
        
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('New Programme Unit based on Callao', gaProgramme.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
		
        List<createTeamMemberProject.FlowInputs> requests = new List<createTeamMemberProject.FlowInputs>();
        createTeamMemberProject.FlowInputs request = new createTeamMemberProject.FlowInputs();
        request.projectId = projectStandard.Id;
        request.userId = UserInfo.getUserId();
        request.role = 'Project Contributor';
        requests.add(request);
	
        createTeamMemberProject.createTeammember_Project(requests);
        
        String accountId = '';
        String contactId = '';
		List<User> contacts = [SELECT Id, Firstname, ContactId, Contact.AccountId FROM User WHERE Id =: request.userId];         
        
        System.assert(contacts.size() > 0);

        if (contacts.size() > 0) {
            contactId = contacts[0].Id;
            accountId = contacts[0].Contact.AccountId;            
        }
        
        ampi__project__c project = [SELECT Id, Account_Teams__c FROM ampi__project__c WHERE Id =: projectStandard.Id LIMIT 1];            
        List<AccountContactRelation> acrs = [SELECT AccountId, ContactId, IsActive FROM AccountContactRelation WHERE ContactId =: contactId AND AccountId =: project.Account_Teams__c];
        
        System.debug('####CTMP Test contacts:' + contacts);
        System.debug('####CTMP Test acrs:' + acrs);
        System.debug('###CTMP Test: contactId:' + contactId);
        System.debug('###CTMP Test: project.Account_Teams__c:' + project.Account_Teams__c);
        for(AccountContactRelation acr : acrs) {
            acr.IsActive = false;
        }
        UPDATE acrs;
        
        createTeamMemberProject.createTeammember_Project(requests);
        
        //System.debug('###acrs: contacts:' + contacts);
		//System.debug('###acrs: contactId:' + contactId);
        //System.debug('###acrs: accountId:' + accountId);
        //List<AccountContactRelation> acrs = [SELECT ID FROM AccountContactRelation WHERE ContactId =: contactId AND AccountId =: accountId];
        //System.assert(acrs.size() > 0);
        
        Test.stopTest();                
    }
}