force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Extent_Information__c.field-meta.xml
<CustomField>
    <fullName>Extent_Information__c</fullName>
    <label>Extent Information</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
            <value>
                <fullName>Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identification</fullName>
                <default>true</default>
                <label>Identification</label>
            </value>
            <value>
                <fullName>Formulation</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Closure</fullName>
            </value>
            <value>
                <fullName>In Setup</fullName>
            </value>
            <value>
                <fullName>In Tendering</fullName>
            </value>
            <value>
                <fullName>In Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Construction.recordType-meta.xml
<RecordType>
    <fullName>Construction</fullName>
    <active>true</active>
    <description>The project that describes the steps of SOS Children&apos;s Villages construction, renovation and purchasing procedures</description>
    <label>Construction</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <description>Defined by contract with institutional donor, major corporate or foundation following PCM/RBM. Funded by int. or local funds. Can take place at programme, national or multi-country level. If in response to a humanitarian crisis, indicate in project setup.</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/ampi__Project_Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Junction linking a project to a thematic area</description>
    <label>Project Thematic Area</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Project Thematic Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Thematic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>This master-detail field refers to the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Thematic Areas</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Thematic_Area__c</fullName>
    <description>This master-detail field refers to the parent thematic area</description>
    <label>Thematic Area</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Related Projects</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/order_project__c.field-meta.xml
<CustomField>
    <fullName>order_project__c</fullName>
    <defaultValue>1</defaultValue>
    <label>order project</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/Programme_Unit__c.field-meta.xml
<CustomField>
    <fullName>Programme_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>3 AND (1 OR 2)</booleanFilter>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>Programme Unit</value>
        </filterItems>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>National Management Unit</value>
        </filterItems>
        <filterItems>
            <field>ampi__Geographical_Area__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Organisational Unit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Project Service Types</relationshipLabel>
    <relationshipName>Project_Service_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/PU_Extent_Information__c.field-meta.xml
<CustomField>
    <fullName>PU_Extent_Information__c</fullName>
    <label>PU Extent Information</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectServiceTypeTriggerHandler.cls
public class ProjectServiceTypeTriggerHandler {
    public void beforeInsertProjectServiceTypes(List<ampi__Project_Thematic_Area__c> newPTAs) {
           Set<Id> newPus = new Set<Id>();           
           for (ampi__Project_Thematic_Area__c pst : newPTAs) {
                System.debug('####pst:' + pst);
                System.debug('####pst.ampi__thematic_area__c:' + pst.ampi__thematic_area__c);
                
                List<ampi__Project_Thematic_Area__c> checkDuplicates = [SELECT Id, Programme_Unit__c, ampi__project__r.RecordType.Name FROM ampi__Project_Thematic_Area__c 
                                                                       WHERE ampi__project__c =: pst.ampi__project__c AND ampi__thematic_area__c =: pst.ampi__thematic_area__c AND ((Programme_Unit__c =: pst.Programme_Unit__c AND ampi__project__r.RecordType.Name NOT IN ('Standard','Grant','Humanitarian')) OR (ampi__project__r.RecordType.Name IN ('Standard','Grant','Humanitarian')))] ;

                //List<ampi__Project_Thematic_Area__c> checkDuplicates2 = [SELECT Id, ampi__project__r.RecordType.Name FROM ampi__Project_Thematic_Area__c 
                //                                                       WHERE ampi__project__c =: pst.ampi__project__c AND ampi__thematic_area__c =: pst.ampi__thematic_area__c AND ampi__project__r.RecordType.Name IN ('Standard','Grant','Humanitarian')];
                            
               if (checkDuplicates.size() > 0) {
                   Set<string> projectTypes = new Set<string>{'Standard','Grant','Humanitarian'};
                    boolean duplicated = false;
                    boolean serviceExists = false;
                    for (ampi__Project_Thematic_Area__c currentPST : checkDuplicates) {
                        if (currentPST.Programme_Unit__c == pst.Programme_Unit__c && !projectTypes.contains(currentPST.ampi__project__r.RecordType.Name)) {
                            duplicated = true;
                        }
                        if (projectTypes.contains(currentPST.ampi__project__r.RecordType.Name)) {
                            serviceExists = true; 
                        }
                    }
                   
                    if (duplicated) {
                    	pst.addError('Project Service Type can\'t be duplicated. Please check Service Type, Project and Programme Unit datafields.');
                        return;
                    }
                   
                    if (serviceExists) {
                        pst.addError('Selected Service type already exists. Please use different Service type for this project.');
                        return;
                    }
                }
                
                List<ampi__Project_Thematic_Area__c> ptaSameProject = [SELECT order_project__c FROM ampi__Project_Thematic_Area__c 
                                                                       WHERE ampi__project__c =: pst.ampi__project__c AND ampi__thematic_area__c =: pst.ampi__thematic_area__c AND order_project__c <> NULL ORDER BY order_project__c DESC];
                System.debug('#####ptaSameProject.size():' + ptaSameProject.size());
                if (ptaSameProject.size() > 0) {
                    pst.order_project__c = ptaSameProject[0].order_project__c + 1;
                }
                System.debug('#####pst.order_project__c:' + pst.order_project__c);
                
                if (pst.Programme_Unit__c != null) {
                    newPus.add(pst.Programme_Unit__c);                    
                }
            } 

            if (newPus.size() > 0) {
                List<ampi__Geographical_Area__c> gas = [SELECT Id, Extent_Information__c FROM ampi__Geographical_Area__c WHERE Id =: newPus];

                for (ampi__Geographical_Area__c ga : gas) {
                    for (ampi__Project_Thematic_Area__c pst : newPTAs) {
                        if (pst.Programme_Unit__c != null && pst.Programme_Unit__c == ga.Id) {
                            pst.PU_Extent_Information__c = ga.Extent_Information__c;                                                
                        }                
                    }
                }
                //UPDATE newPTAs;
            }
    }    

    public void beforeDeleteRestrictProjectServiceTypeDeletion(List<ampi__Project_Thematic_Area__c> oldServiceTypeProjects) {
        Boolean hasCustomPermission = FeatureManagement.checkPermission('Manage_Restrictions');
        if (hasCustomPermission) {
            Integer countUsers = [SELECT Count() FROM User WHERE Id =:UserInfo.getUserId() AND Profile.Name = 'System Administrator'];
            if (countUsers > 0) {
                return;
            }                            
        }

        System.debug('####enter beforeDeleteRestrictProjectServiceTypeDeletion!');
        for(ampi__Project_Thematic_Area__c acc : oldServiceTypeProjects){
            List<ampi__project__c> projectsData = [SELECT RecordType.Name, ampi__Project_Status__c, Phase__c FROM ampi__project__c WHERE Id =: acc.ampi__project__c];

            if (projectsData.size() > 0) {
                if ((projectsData[0].RecordType.Name == 'Transition' && projectsData[0].ampi__Project_Status__c == 'In Implementation') ||
                    (projectsData[0].RecordType.Name == 'Standard' && (projectsData[0].ampi__Project_Status__c == 'Funding Approved' || projectsData[0].Phase__c == 'Implementation' || projectsData[0].Phase__c == 'Closure')) ||
                    (projectsData[0].RecordType.Name == 'Grant' && (projectsData[0].ampi__Project_Status__c == 'Application Approved' || projectsData[0].ampi__Project_Status__c == 'In Implementation' || projectsData[0].Phase__c == 'Implementation' || projectsData[0].Phase__c == 'Closure')) ||
                    (projectsData[0].RecordType.Name == 'Humanitarian' && (projectsData[0].ampi__Project_Status__c == 'Plan Submitted' || projectsData[0].Phase__c == 'Implementation' || projectsData[0].Phase__c == 'Closure')) ||
                    (projectsData[0].RecordType.Name == 'Construction' && projectsData[0].ampi__Project_Status__c == 'Total Funding Available')) {
                    acc.addError('Service Type Projects are not allowed to be removed');
                }
            }
        } 
    }
}