force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Extent_Information__c.field-meta.xml
<CustomField>
    <fullName>Extent_Information__c</fullName>
    <label>Extent Information</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/ampi__Project_Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Junction linking a project to a thematic area</description>
    <label>Project Thematic Area</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Project Thematic Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Thematic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>This master-detail field refers to the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Thematic Areas</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Thematic_Area__c</fullName>
    <description>This master-detail field refers to the parent thematic area</description>
    <label>Thematic Area</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Related Projects</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/PU_Extent_Information__c.field-meta.xml
<CustomField>
    <fullName>PU_Extent_Information__c</fullName>
    <label>PU Extent Information</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectServiceTypeTriggerHandlerTest.cls
@isTest
private class ProjectServiceTypeTriggerHandlerTest {
    @isTest 
    static void beforeInsertProjectServiceTypes_ExtentInformationUpdated() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Child Money Gift');
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
        
        Test.startTest();

        try {
            gaProgrammeUnit.Extent_Information__c = 'Extent_Information__c was changed';
            UPDATE gaProgrammeUnit;
            
            ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
            ampi__project_thematic_area__c ptaUpdated = [SELECT Id, PU_Extent_Information__c FROM ampi__project_thematic_area__c WHERE Id =: pta.Id LIMIT 1];
            System.assert(ptaUpdated.PU_Extent_Information__c == 'Extent_Information__c was changed');
        }catch(Exception ex) {
            Boolean expectedExceptionThrown =  ex.getMessage().contains('Project Service Type can\'t be duplicated. Please check Service Type, Project and Programme Unit datafields.') ? true : false;
            //TODO: System.assertEquals(expectedExceptionThrown, true);
			System.assert(true);
        }

        Test.stopTest();        
    }

    @isTest 
    static void beforeInsertProjectServiceTypes_CheckDuplicates() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Child Money Gift');
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
        
        Test.startTest();
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        
        try {
        	ampi__project_thematic_area__c pta2 = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);        
        }catch(Exception ex) {
            Boolean expectedExceptionThrown =  ex.getMessage().contains('Project Service Type can\'t be duplicated. Please check Service Type, Project and Programme Unit datafields.') ? true : false;
            //TODO: System.assertEquals(expectedExceptionThrown, true);
			System.assert(true);
        }  

        
        Test.stopTest();        
    }

    @isTest 
    static void beforeDeletetProjectServiceTypes_ExtentInformationUpdated() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Child Money Gift');
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('YC Callao', gaProgramme.Id, accNA.Id);
        
        ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
        // projectTransition.ampi__Project_Status__c = 'In Implementation';
        // UPDATE projectTransition;

        Test.startTest();
        
        ampi__project_thematic_area__c pta = TestDataFactory.createProjectThematicArea(projectTransition.Id, thematicAreaYC.Id, gaProgrammeUnit.Id);
        ampi__project_thematic_area__c ptaUpdated = [SELECT Id, PU_Extent_Information__c FROM ampi__project_thematic_area__c WHERE Id =: pta.Id LIMIT 1];

        try {
        	delete ptaUpdated;    
        }catch(Exception ex) {
            Boolean expectedExceptionThrown =  ex.getMessage().contains('Service Type Projects are not allowed to be removed') ? true : false;
			System.assert(true);
        }      

        Test.stopTest();        
    }
}