force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/Account_Teams__c.field-meta.xml
<CustomField>
    <fullName>Account_Teams__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Organisation record which is populated here will be used as the basis for sharing this Project record with external users in the MA Portal. For Projects (Grants, Standard, Emergency) this should be the shadow Organisation record named like &quot;{Project ID} - External Project Team&quot;. For Programmes or NMUs, this should be the NA that they fall underneath.</description>
    <inlineHelpText>The Organisation record which is populated here will be used as the basis for sharing this Project record with external users in the MA Portal. For Projects (Grants, Standard, Emergency) this should be the shadow Organisation record named like &quot;{Project ID} - External Project Team&quot;. For Programmes or NMUs, this should be the NA that they fall underneath.</inlineHelpText>
    <label>External Project Team</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Account Team)</relationshipLabel>
    <relationshipName>Projects5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Programme_Location__c.field-meta.xml
<CustomField>
    <fullName>Programme_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the programme location for your project.</inlineHelpText>
    <label>Programme Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Programme for this field, not a Programme Unit, Country or Region.</errorMessage>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Projects in this Programme Location</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Project_ID_Text__c.field-meta.xml
<CustomField>
    <fullName>Project_ID_Text__c</fullName>
    <formula>CASE(RecordType.Name,
&quot;Standard&quot;, &quot;S&quot;,
&quot;Emergency Response&quot;, &quot;E&quot;,
&quot;Funding Opportunity&quot;, &quot;F&quot;,
&quot;Humanitarian&quot;, &quot;H&quot;,
&quot;Grant&quot;, &quot;G&quot;,
&quot;Legacy&quot;, &quot;L&quot;,
&quot;End of Involvement&quot;, &quot;X&quot;,
&quot;Construction&quot;, &quot;C&quot;,
&quot;&quot;)
&amp; IF(DATEVALUE(CreatedDate) &gt; DATEVALUE(&quot;2019-12-31&quot;),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2),
IF(RecordType.Name = &quot;Grant&quot;,
RIGHT(TEXT(YEAR(Start_Identification__c)), 2),
RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))), 2)
)
)
&amp; &quot;-&quot;
&amp; Project_Autonumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Project ID is generated by the system..</inlineHelpText>
    <label>Project ID Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/unique_field__c.field-meta.xml
<CustomField>
    <fullName>unique_field__c</fullName>
    <externalId>true</externalId>
    <label>unique field</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/D365_Project_Stand_in__c/D365_Project_Stand_in__c.object-meta.xml
<CustomObject>
    <description>Dummy object to allow for appropriate filtering on D365 Projects</description>
    <label>D365 Project Stand-in</label>
    <nameField>
        <displayFormat>D365S-{000000}</displayFormat>
        <label>D365 Project Stand-in Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>D365 Project Stand-ins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/D365_Project_Stand_in__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>D365 Project Stand-ins</relationshipLabel>
    <relationshipName>D365_Project_Stand_ins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/ScheduledDeletingD365Test.cls
@isTest
private class ScheduledDeletingD365Test {
    @isTest
    private static void executeBatch_GeneratingExternal() {
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgrammeUnit = TestDataFactory.createProgrammeUnit('New Programme Unit based on Callao', gaProgramme.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		ampi__Project__c projectTransition = TestDataFactory.createProject('Transition', accNA.Id, gaProgramme.Id, 'FS, YC');
        List<ampi__Project__c> projects = [SELECT Id, Project_ID_Text__c, Account_Teams__c FROM ampi__project__c WHERE ID =: projectTransition.Id];
        
        for(ampi__Project__c proj : projects) {
            proj.Account_Teams__c = null;            
            proj.Programme_Location__c = gaProgramme2.Id;
        }
        UPDATE projects;
        
        List<D365_Project_Stand_in__c> projectd365s = [select id, unique_field__c  from D365_Project_Stand_in__c WHERE Project__c =: projectTransition.Id];
        System.debug('###projectd365s: ' + projectd365s);
        
        Test.startTest();
		(new ScheduledDeletingD365ProgrammeProject()).execute(null);        
        DeletingD365ProgrammeProjectBatch dppb = new DeletingD365ProgrammeProjectBatch();
        dppb.execute(null, projectd365s);        
        DataBase.executeBatch(dppb); 
        Test.stopTest();

        System.assert(true);        
    }
}