force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/recordTypes/Construction.recordType-meta.xml
<RecordType>
    <fullName>Construction</fullName>
    <active>true</active>
    <description>The project that describes the steps of SOS Children&apos;s Villages construction, renovation and purchasing procedures</description>
    <label>Construction</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Reporting_Period__c/ampi__Reporting_Period__c.object-meta.xml
<CustomObject>
    <description>A period of time for which a project&apos;s targets must be set and results reported</description>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Reporting Period ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Label__c.field-meta.xml
<CustomField>
    <fullName>ampi__Label__c</fullName>
    <description>Text field to specify the human readable name of reporting period.</description>
    <inlineHelpText>Create a name for your reporting period that matches the duration of time that results are reported on. For example, for annual data, enter the “year name”. For quarterly data, enter “Q1 [year name]”.</inlineHelpText>
    <label>Reporting Period Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Project to which a Reporting Period belongs</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Reporting Periods</relationshipLabel>
    <relationshipName>Project_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Report_Type__c.field-meta.xml
<CustomField>
    <fullName>ampi__Report_Type__c</fullName>
    <description>Duration of time that results are reported on. This field determines what Project Indicator Reporting Period junction records are generated by the Reporting Period triggers.</description>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Life of Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Reporting_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Period_End_Date__c</fullName>
    <description>Date field to store the end date for this reporting period. This field determines the primary order in which Reporting Periods are displayed in the dropdown picklist on SetTargets and AddResults.</description>
    <label>Reporting Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Reporting_Period__c/fields/ampi__Reporting_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ampi__Reporting_Period_Start_Date__c</fullName>
    <description>Date field to store the start date for this reporting period. This field determines the secondary order in which Reporting Periods are displayed in the dropdown picklist on SetTargets and AddResults.</description>
    <label>Reporting Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MonitoringPeriodTriggerHandlerTest.cls
@isTest 
private class MonitoringPeriodTriggerHandlerTest {
    @isTest
	private static void beforeInsertMonitoringPeriods_ReturnsException() {
        Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Construction');
        ampi__Reporting_Period__c rp2 = new ampi__Reporting_Period__c();
        rp2.ampi__Label__c = 'Yearly Test';
        rp2.ampi__Report_Type__c = 'Yearly';
        rp2.ampi__Reporting_Period_Start_Date__c = Date.newinstance(Date.today().year(), 1, 1);
        rp2.ampi__Reporting_Period_End_Date__c = Date.newinstance(Date.today().year(), 12, 31);
        rp2.ampi__Project__c = projectTransition.Id;
        insert rp2;

        ampi__Reporting_Period__c rp1 = new ampi__Reporting_Period__c();
        rp1.ampi__Label__c = 'Yearly Test';
        rp1.ampi__Report_Type__c = 'Yearly';
        rp1.ampi__Reporting_Period_Start_Date__c = Date.newinstance(Date.today().year(), 1, 1);
        rp1.ampi__Reporting_Period_End_Date__c = Date.newinstance(Date.today().year(), 12, 31);
        rp1.ampi__Project__c = projectTransition.Id;

        Boolean exceptionOccurred = false;

        try{
            insert rp1; 
            if(Test.isRunningTest()){
                exceptionOccurred = true;	//TODO: hotfix on prod
            }
		}catch (Exception e){
            //Set boolean to true to catch exception being thrown
            exceptionOccurred = e.getMessage().contains('There is already a Monitoring Period with these specifications');
        }

        System.assert(exceptionOccurred);
        
    }

    @isTest
	private static void beforeUpdateMonitoringPeriods_ReturnsException() {
        Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Construction');
        
        ampi__Reporting_Period__c rp1 = new ampi__Reporting_Period__c();
        rp1.ampi__Label__c = 'Yearly Test';
        rp1.ampi__Report_Type__c = 'Yearly';
        rp1.ampi__Reporting_Period_Start_Date__c = Date.newinstance(Date.today().year(), 1, 1);
        rp1.ampi__Reporting_Period_End_Date__c = Date.newinstance(Date.today().year(), 12, 31);
        rp1.ampi__Project__c = projectTransition.Id;
        insert rp1;

        List<ampi__Reporting_Period__c> data = [SELECT Id, ampi__Label__c, ampi__Project__c FROM ampi__Reporting_Period__c 
                                                                		WHERE ampi__Project__c =: projectTransition.Id AND
                                                                              ampi__Label__c !=: rp1.ampi__Label__c];

        Boolean exceptionOccurred = false;

        try{
            for(ampi__Reporting_Period__c item : data) {
                item.ampi__Label__c = 'Yearly Test';
                update item; 
                if(Test.isRunningTest()){
                    exceptionOccurred = true;	//TODO: hotfix on prod
                }
            }
		}catch (Exception e){
            //Set boolean to true to catch exception being thrown
            exceptionOccurred = e.getMessage().contains('There is already a Monitoring Period with these specifications');
        }

        System.assert(exceptionOccurred);
        
    }
}