force-app/main/default/objects/Deliverable__c/Deliverable__c.object-meta.xml
<CustomObject>
    <label>Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deliverable__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Project ID to which the deliverable is related. Filled by the system.</inlineHelpText>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Deliverables</relationshipLabel>
    <relationshipName>Deliverables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deliverable__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Set to done once the deliverable is available and passed applicable validation cycle. Add link to the Sharepoint where the deliverable is stored.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Done</fullName>
                <default>true</default>
                <label>Not Done</label>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Agreement in progress</fullName>
            </value>
            <value>
                <fullName>In development</fullName>
            </value>
            <value>
                <fullName>Agreement signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deliverable__c/recordTypes/Agreement.recordType-meta.xml
<RecordType>
    <fullName>Agreement</fullName>
    <active>true</active>
    <label>Agreement</label>
</RecordType>

force-app/main/default/classes/agreementQueries.cls
public without sharing class agreementQueries {
    
    @AuraEnabled(cacheable=true)
    public static Deliverable__c getAgreementFromProjectId(String projectId) {													
        List<Deliverable__c> res = [SELECT Id, Status__c FROM Deliverable__c WHERE project__c =: projectId AND recordType.Name =: 'Agreement'];
        
        if (res.size() > 0) {
            return res[0];
        }
        return null;
    }
    
    
    public static List<Deliverable__c> getAgreementsFromProjects(Set<Id> projIds) {
        return [SELECT Id, project__c FROM deliverable__c WHERE project__c IN : projIds AND recordType.Name =: 'Agreement'];
    } 
    
    public static boolean existsAgreementFromProject(List<Deliverable__c> deliverables, String projectId) {
        for(deliverable__c aggr : deliverables) {
			if (aggr.project__c == projectId) {
            	return true;
            }
        }
        return false;
    }
}