force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>P&amp;PUs</relationshipLabel>
    <relationshipName>P_PUs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/Corresponding_address_different__c.field-meta.xml
<CustomField>
    <fullName>Corresponding_address_different__c</fullName>
    <label>Correspondance address different</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/Actuals_Total_Project_Expenditures_LC__c.field-meta.xml
<CustomField>
    <fullName>Actuals_Total_Project_Expenditures_LC__c</fullName>
    <inlineHelpText>Indicate total actual amount of project expenditures in local currency.</inlineHelpText>
    <label>Actuals Total Project Expenditures (LCY)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Captures the status of a project record once it has been submitted into an approval process. This field will update at the three various stages on the project lifecycle: In Identification, In Formulation, and In Implementation.</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved by NA</fullName>
            </value>
            <value>
                <fullName>Rejected by NA</fullName>
            </value>
            <value>
                <fullName>Rejected by IOR</fullName>
            </value>
            <value>
                <fullName>Reviewed by IOR</fullName>
            </value>
            <value>
                <fullName>Reviewed by PSA</fullName>
            </value>
            <value>
                <fullName>Rejected by PSA</fullName>
            </value>
            <value>
                <fullName>Approved by IO</fullName>
                <isActive>false</isActive>
                <label>Approved by IO</label>
            </value>
            <value>
                <fullName>Approved by IOR</fullName>
                <isActive>false</isActive>
                <label>Approved by IOR</label>
            </value>
            <value>
                <fullName>Rejected by IO</fullName>
                <isActive>false</isActive>
                <label>Rejected by IO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RiskControllerTest.cls
@isTest 
private class RiskControllerTest {

    @isTest
	private static void RiskControllerTest_checkIfUserCanManage_Project_ReturnTrue() {
		//Name
		User u = TestDataFactory.CreateUserFromSystemAdmin();
		System.runAs(u) {
			boolean result = RiskController.checkIfUserCanEditObject('ampi__Project__c');
			System.assertEquals(result, true); 
		}

		u = TestDataFactory.CreateUserFromSystemAdmin();
		System.runAs(u) {
			boolean result = RiskController.checkIfUserCanDeleteObject('ampi__Project__c');
			System.assertEquals(result, true); 
		}
        
        u = TestDataFactory.CreateUserFromSystemAdmin();
		System.runAs(u) {
			boolean result = RiskController.checkIfUserCanCreateObject('ampi__Project__c');
			System.assertEquals(result, true); 
		}
        
        u = TestDataFactory.CreateUserFromSystemAdmin();
		System.runAs(u) {
			boolean result = RiskController.checkIfUserCanAccessObject('ampi__Project__c');
			System.assertEquals(result, true); 
		}
	}
    
	@isTest
	private static void RiskControllerTest_checkIfUserCanEditDatafield_ProjectName_ReturnFalse() {
		//Name
		User u = TestDataFactory.CreateUserFromSystemAdmin();
		System.runAs(u) {
			boolean result = RiskController.checkIfUserCanEditDatafield('ampi__Project__c','Name');
			System.assertEquals(result, true); 
		}

		u = TestDataFactory.CreateUserFromReadOnly();
		System.runAs(u) {
			boolean result = RiskController.checkIfUserCanEditDatafield('ampi__Project__c','Name');
			System.assertEquals(result, false); 
		}
	}

	@isTest
	private static void RiskControllerTest_getPickListValuesFromDatafield_ProjectPriority_ReturnListWithValues() {
		//Priority__c
		List<String> values = RiskController.getPickListValuesFromDatafield('ampi__Project__c', 'Priority__c');
		System.assert(values.size() > 0);
	}

	@isTest
	private static void RiskControllerTest_getLabelFromDatafield_Project_ApprovalStatus_ReturnApprovalStatus() {
		//Approval_Status__c
		string value = RiskController.getLabelFromDatafield('ampi__Project__c', 'Approval_Status__c');
		//System.debug(K'####Approval_Status__c:' + Approval_Status__c);
		System.assertEquals(true, String.isNotBlank(value) && value <> 'Approval_Status__c');
	}

	@isTest
	private static void RiskControllerTest_getHelpTextFromDatafield_Project_Actuals_Total_Project_Expenditures_LC_ReturnValue() {
		//Actuals_Total_Project_Expenditures_LC
		string value = RiskController.getHelpTextFromDatafield('ampi__Project__c', 'Actuals_Total_Project_Expenditures_LC__c');
		System.assertEquals(true, String.isNotBlank(value));
	}

	
	@isTest
	private static void RiskControllerTest_isSOSOrganisationMA_NAPeru_ReturnTrueValue() {
		//Actuals_Total_Project_Expenditures_LC
		Account newOrg = TestDataFactory.createOrganisationWithRecordType('SOS Organisation - MA');
		Boolean value = RiskController.isSOSOrganisationMA('Account', newOrg.Id);
		System.assertEquals(true, value);


		Account newOrgFailed = TestDataFactory.createOrganisationWithRecordType('Organization');
		Boolean valueFailed = RiskController.isSOSOrganisationMA('Account', newOrgFailed.Id);
		System.assertEquals(false, valueFailed);

		
	}

    
    @isTest
	private static void RiskControllerTest_AddAddressSOSOrganisationMA_NAPeru_ReturnsTrue() {
		//Actuals_Total_Project_Expenditures_LC
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);

		Account accLE = new Account();
        accLE.Name = 'Legal Entity Test';
        accLE.Type = 'NA';
        accLE.RecordTypeId = Account.sObjectType.getDescribe().getRecordTypeInfosByName().get('Legal Entity').getRecordTypeId();
		INSERT accLE;

        Address__c addrMA = TestDataFactory.createAddress(accNA.Id, gaCountry.Id, accLE.Id);
        Address__c addrPro = TestDataFactory.createAddress(accNA.Id, gaCountry.Id, accLE.Id);
        
        RiskController.updateCorrespondanceAddressFromPU(gaProgramme.Id, 'Yes'); 
        RiskController.updateAddressFromOrganisation(accNA.Id, addrMa.Id);
        RiskController.updateAddressFromPUs(gaProgramme.Id, addrPro.Id, true);
            
        ampi__geographical_area__c ga = RiskController.getCorrespondanceAddressFromPU(gaProgramme.Id);
        List<Address__c> addrFromPro = RiskController.getAddressFromPUs(gaProgramme.Id, false);
        List<Address__c> addrProAdditional = RiskController.getAddressFromPUs(gaProgramme.Id, true);
        List<Address__c> addrFromMA = RiskController.getAddressFromOrganisation(accNA.Id);

		String newAddressId = RiskController.insertAddress('Lima', gaCountry.Id, 'Pueblo Libre', '222222', '2222222', 'Address Test 1', '1122333', 'Lima', gaCountry.Id, '5555222', '44222', accLE.Id, 'La Luz 102', 'ada');
        String updateResult = RiskController.updateAddress(newAddressId, 'Lima Upd', gaCountry.Id, 'Pueblo Libre', '222222', '2222222', 'Address Test 1', '1122333', 'Lima', gaCountry.Id, '5555222', '44222',accLE.Id, 'La Luz 102', 'ada');
        
        String countryName = RiskController.getCountryNameFromAddress(newAddressId);
		List<sObject> resObject = RiskController.getSystemInfoFromObject('address__c', newAddressId);
            
		System.assertEquals(true, ga <> null && ga.Corresponding_address_different__c == 'Yes');		        
        // System.assertEquals(true, addrFromPro.size() > 0 && addrProAdditional.size() > 0 && addrFromMA.size() > 0);		
	}
}