force-app/main/default/objects/ampi__Project_Indicator__c/ampi__Project_Indicator__c.object-meta.xml
<CustomObject>
    <description>Junction linking a catalog indicator to a project</description>
    <label>Project Indicator</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Project Indicator ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator_Objective__c/ampi__Project_Indicator_Objective__c.object-meta.xml
<CustomObject>
    <description>An objective that has been assigned to a specific project indicator</description>
    <label>Project Indicator Objective</label>
    <nameField>
        <displayFormat>PIO-{0000}</displayFormat>
        <label>Project Indicator Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Indicator Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Indicator_Objective__c/fields/ampi__Project_Indicator__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Indicator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify parent project indicator</description>
    <label>Project Indicator</label>
    <referenceTo>ampi__Project_Indicator__c</referenceTo>
    <relationshipLabel>Project Indicator Objectives</relationshipLabel>
    <relationshipName>Project_Indicator_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Indicator_Objective__c/fields/ampi__xx_Framework_Objective__c.field-meta.xml
<CustomField>
    <fullName>ampi__xx_Framework_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup field refers to parent framework objective</description>
    <label>Framework Objective</label>
    <referenceTo>ampi__Objective__c</referenceTo>
    <relationshipLabel>Project Indicator Objectives</relationshipLabel>
    <relationshipName>Project_Indicator_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilTestCases.cls
@isTest
private class UtilTestCases {
    @isTest(SeeAllData=true)
    static void createProjectIndicatorObjective_From_ProjectManagerUser() {
        User u = [SELECT Id, profileId, email, username FROM User WHERE Id = '0053N00000AiWxB' LIMIT 1];
        System.runAs(u) {
            //CREAR REGISTROS: Create Project Indicator Objective record
            //Crear un registro ampi__Project_Indicator_Objective__c donde:
            ampi__Project_Indicator_Objective__c pio = new ampi__Project_Indicator_Objective__c();
            pio.ampi__Project_Indicator__c = 'a0f3N000002ULm6QAG';
            pio.ampi__xx_Framework_Objective__c = 'a0Q7T000000kJFYUA2';
            
            try {
                INSERT pio;    
            } catch(Exception ex) {
                System.debug('####exception:' + ex.getMessage());
            }    
        }
    }
}