force-app/main/default/objects/ampi__Disbursement__c/ampi__Disbursement__c.object-meta.xml
<CustomObject>
    <description>Financial payments made for a Project</description>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Disbursement__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-Detail field to specify the project this disbursement belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/classes/DisbursementTriggerHandlerTest.cls
@isTest
private class DisbursementTriggerHandlerTest {
    @isTest 
    static void afterInsertDeleteBudget_CheckFinancialsAndBudgetsForTransitionNationalservices() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'National services');
		
		Test.startTest();
		List<ampi__Disbursement__c> disbursements = [SELECT Id FROM ampi__Disbursement__c WHERE ampi__Project__c =: projectTransition.id];
        Boolean exceptionOccurred = false;

        try{
            delete disbursements;
		}catch (Exception e){
            //Set boolean to true to catch exception being thrown
            exceptionOccurred = e.getMessage().contains('Disbursements are not allowed to be removed or changed');
        }

        System.System.assert(exceptionOccurred);
        
        Test.stopTest();        
    }
}