force-app/main/default/objects/ampi__Disbursement__c/ampi__Disbursement__c.object-meta.xml
<CustomObject>
    <description>Financial payments made for a Project</description>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Disbursement__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-Detail field to specify the project this disbursement belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Disbursement__c/fields/Is_ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>Is_ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ReadOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Disbursement__c/fields/Order_Project__c.field-meta.xml
<CustomField>
    <fullName>Order_Project__c</fullName>
    <label>Order Project</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DisbursementTriggerHandler.cls
public class DisbursementTriggerHandler {
	public void afterInsertSetOrderPerProject(List<ampi__Disbursement__c> newDisbursements) {
    	if (newDisbursements.size() == 0) {
            return;
        }
        
        Decimal order = 0;
        Id projectId;
        Boolean hasRecordsToUpdate = false; 
        Set<Id> ids = (new Map<Id, ampi__Disbursement__c>(newDisbursements)).keySet();
        List<ampi__Disbursement__c> newDisbursementsToUpdate = [SELECT Id, Order_Project__c, ampi__Project__c FROM ampi__Disbursement__c WHERE Id =: ids AND ampi__Project__c != ''];

        for(ampi__Disbursement__c newDisbursement : newDisbursementsToUpdate) {     
                if (projectId != newDisbursement.ampi__Project__c) {
                    projectId = newDisbursement.ampi__Project__c;
                	order = 0;
                    List<ampi__Disbursement__c> checkOrders = [SELECT Id, Order_Project__c FROM ampi__Disbursement__c WHERE ampi__Project__c =: projectId AND Order_Project__c <> NULL ORDER BY Order_Project__c DESC LIMIT 1];
            		if (checkOrders.size() > 0) {
            			order = checkOrders[0].Order_Project__c + 1;
                    } else {
                        order = order + 1;
                    }
                } else {
                	order = order + 1;
                }

                if (newDisbursement.Order_Project__c != order) {
                    hasRecordsToUpdate = true;                
                    newDisbursement.Order_Project__c = order;
                }
        }
        
        if (hasRecordsToUpdate) {
            UPDATE newDisbursementsToUpdate;
        }
    }   
    public void beforeDeleteRestrictionDeletion(List<ampi__Disbursement__c> newDisbursements) {
        for(ampi__Disbursement__c acc : newDisbursements){
            if (acc.Is_ReadOnly__c == true) {
                acc.addError('Disbursements are not allowed to be removed or changed');
            } 
        } 
    }
    public void beforeUpdateRestrictionDeletion(List<ampi__Disbursement__c> newDisbursements, List<ampi__Disbursement__c> oldDisbursements) {
        for(ampi__Disbursement__c acc : newDisbursements){
            if (acc.Is_ReadOnly__c == true) {
                for(ampi__Disbursement__c accold : oldDisbursements) {
                    if (acc.Id == accold.Id && acc.Order_Project__c == accold.Order_Project__c) {
                        acc.addError('Disbursements are not allowed to be removed or changed');
                    }
                }
            } 
        } 
    }
}