force-app/main/default/objects/ampi__Objective__c/ampi__Objective__c.object-meta.xml
<CustomObject>
    <description>An objective that has been assigned to a specific project</description>
    <label>Framework Objective</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Project Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project objective</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Objective__c.field-meta.xml
<CustomField>
    <fullName>ampi__Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to specify the parent catalog objective</description>
    <label>Objective</label>
    <referenceTo>ampi__Catalog_Objective__c</referenceTo>
    <relationshipLabel>Project Objectives</relationshipLabel>
    <relationshipName>Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Parent_Project_Objective__c.field-meta.xml
<CustomField>
    <fullName>ampi__Parent_Project_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self-lookup to create a hierarchy between objectives within a project, as displayed on ManageLogframes</description>
    <label>Parent Framework Objective</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>$Source.ampi__Project__c</field>
            <operation>equals</operation>
            <valueField>ampi__Objective__c.ampi__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Objective__c</referenceTo>
    <relationshipLabel>Child Project Objectives</relationshipLabel>
    <relationshipName>Child_Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to specify the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Project_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Objective__c/fields/Description_Short__c.field-meta.xml
<CustomField>
    <fullName>Description_Short__c</fullName>
    <label>Description Short</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Description__c.field-meta.xml
<CustomField>
    <fullName>ampi__Description__c</fullName>
    <description>Long text field to describe the project</description>
    <inlineHelpText>Add description of your project (1024 char max), describe specific objectives. Include key words to ease the search (e.g. country, donor). The description can be changed and updated at any time and is shown on the Team Site.</inlineHelpText>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
            <value>
                <fullName>Closure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identification</fullName>
                <default>true</default>
                <label>Identification</label>
            </value>
            <value>
                <fullName>Formulation</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Closure</fullName>
            </value>
            <value>
                <fullName>In Setup</fullName>
            </value>
            <value>
                <fullName>In Tendering</fullName>
            </value>
            <value>
                <fullName>In Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/classes/ProjectResultStatementTriggerHandler.cls
public class ProjectResultStatementTriggerHandler {
    public void beforeInsertSetShortDescription(List<ampi__Objective__c> newProjectResultStatement) {
           Set<Id> newPus = new Set<Id>();           
           for (ampi__Objective__c obj : newProjectResultStatement) {
               if (obj.ampi__description__c <> null) {
                    String text = obj.ampi__description__c.length() >= 255 ? obj.ampi__description__c.substring(0, 255) : obj.ampi__description__c;
                    obj.description_short__c = text;
                }
            } 
    }   
    
    public void beforeUpdateSetShortDescription(List<ampi__Objective__c> oldProjectResultStatement, List<ampi__Objective__c> newProjectResultStatement) {
        system.debug('####enter beforeUpdateSetShortDescription shouldBeUpdated');
        // Boolean shouldBeUpdated = false;
        for (ampi__Objective__c prsToCheck : oldProjectResultStatement) { 
            ampi__Objective__c objectiveToUpdate;
            for (ampi__Objective__c prsUpdated : newProjectResultStatement) {
                if (prsToCheck.Id == prsUpdated.Id) {
                    objectiveToUpdate = prsUpdated;
                }
            }
            
            if (objectiveToUpdate.ampi__description__c <> null && objectiveToUpdate.ampi__description__c != prsToCheck.ampi__description__c) {
                    String text = objectiveToUpdate.ampi__description__c.length() >= 255 ? objectiveToUpdate.ampi__description__c.substring(0, 255) : objectiveToUpdate.ampi__description__c;
                    objectiveToUpdate.description_short__c = text;
                    // shouldBeUpdated = true;
                    system.debug('####beforeUpdateSetShortDescription shouldBeUpdated');
            }
        }

        // if (shouldBeUpdated == true) {
        //     UPDATE newProjectResultStatement;
        // }
    }

    public void beforeUpdateRestriction(List<ampi__Objective__c> oldProjectResultStatement, List<ampi__Objective__c> newProjectResultStatement) {
        Set<Id> projectIds = new Set<Id>();
        for (ampi__Objective__c prsToCheck : oldProjectResultStatement) { 
             if (prsToCheck.ampi__Project__c != NULL && !projectIds.contains(prsToCheck.ampi__Project__c)) {
                    projectIds.add(prsToCheck.ampi__Project__c);
             }
        }

        System.debug('#queries-beforeUpdateRestriction 1:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
    
        List<ampi__Project__c> projects = [SELECT Id, Phase__c, ampi__Project_Status__c FROM ampi__Project__c 
                                           WHERE Id IN : projectIds AND RecordType.Name = 'Standard' AND 
                                           (Phase__c = 'Implementation' OR Phase__c = 'Closure' OR ampi__Project_Status__c = 'Funding approved')];
 

        System.debug('#queries-beforeUpdateRestriction 2:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());

        for (ampi__Objective__c prsToCheck : oldProjectResultStatement) { 
             if (prsToCheck.ampi__Project__c != NULL) {
                //ampi__Project__c currentProject = [SELECT Id, Phase__c, ampi__Project_Status__c, RecordType.Name FROM ampi__Project__c WHERE ID =: prsToCheck.ampi__Project__c LIMIT 1];
                if (prsToCheck.ampi__Project__c != NULL) {                      
                       ampi__Project__c currentProject = null;
                       for (ampi__Project__c project : projects) {
                            if (project.Id == prsToCheck.ampi__Project__c) {
                                currentProject = project;
                            }
                        } 

                        if (currentProject != null) {
                            for (ampi__Objective__c prsUpdated : newProjectResultStatement) {
                                if (prsUpdated.Id == prsToCheck.Id  && prsUpdated.ampi__Parent_Project_Objective__c != prsToCheck.ampi__Parent_Project_Objective__c) {
                                        prsUpdated.addError('Cannot update Related Project Result Statement fields from the Project Result Statement if the project is in "' +currentProject.Phase__c + '" phase and "' + currentProject.ampi__Project_Status__c + '" status');
                                }
                            }
                        }
                }
             }
        }
    }

    public void beforeDeleteRestrictionPRSAccordingToProjectData(List<ampi__Objective__c> oldProjectResultStatement) {
        for (ampi__Objective__c prsToCheck : oldProjectResultStatement) { 
             if (prsToCheck.ampi__Project__c != NULL) {
                ampi__Project__c currentProject = [SELECT Id, Phase__c, ampi__Project_Status__c, RecordType.Name FROM ampi__Project__c WHERE ID =: prsToCheck.ampi__Project__c LIMIT 1];
                
                if (prsToCheck.ampi__Project__c != NULL && 
                        (currentProject.RecordType.Name == 'Standard' && 
                        (currentProject.Phase__c == 'Implementation' || 
                        currentProject.Phase__c == 'Closure' || 
                        currentProject.ampi__Project_Status__c == 'Funding approved'))) {                      
                            prsToCheck.addError('Cannot delete Project Result Statement if the project is in "' +currentProject.Phase__c + '" phase and "' + currentProject.ampi__Project_Status__c + '" status');                            
                }
             }
        }
    }
}