force-app/main/default/objects/ampi__Budget__c/ampi__Budget__c.object-meta.xml
<CustomObject>
    <description>Budget for a project</description>
    <label>Budget</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Budget__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detail field to relate a budget record to a project record.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/fields/Is_ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>Is_ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ReadOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/fields/Order_Project__c.field-meta.xml
<CustomField>
    <fullName>Order_Project__c</fullName>
    <label>Order Project</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/ampi__Financial__c.object-meta.xml
<CustomObject>
    <description>Financial records of a project, per reporting period and budget</description>
    <label>Financial</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Budget__c.field-meta.xml
<CustomField>
    <fullName>ampi__Budget__c</fullName>
    <description>Master-detail field to relate a financial record to a budget record.</description>
    <label>Budget</label>
    <referenceTo>ampi__Budget__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Category__c.field-meta.xml
<CustomField>
    <fullName>ampi__Category__c</fullName>
    <description>This picklist field is for categorizing Financial records based on their purpose. This field is unrestricted and can be modified by subscribers.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Result based</fullName>
            </value>
            <value>
                <fullName>9 PSCI</fullName>
            </value>
            <value>
                <fullName>Overarching</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>ADV</fullName>
            </value>
            <value>
                <fullName>SIL</fullName>
            </value>
            <value>
                <fullName>FLC</fullName>
            </value>
            <value>
                <fullName>DFE</fullName>
            </value>
            <value>
                <fullName>CFE</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>HA</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>ECD</fullName>
            </value>
            <value>
                <fullName>EDU</fullName>
            </value>
            <value>
                <fullName>EET</fullName>
            </value>
            <value>
                <fullName>ER</fullName>
            </value>
            <value>
                <fullName>FFC</fullName>
            </value>
            <value>
                <fullName>FS</fullName>
            </value>
            <value>
                <fullName>HPP</fullName>
            </value>
            <value>
                <fullName>MED</fullName>
            </value>
            <value>
                <fullName>OA</fullName>
            </value>
            <value>
                <fullName>OAC</fullName>
            </value>
            <value>
                <fullName>SGH</fullName>
            </value>
            <value>
                <fullName>SFC</fullName>
            </value>
            <value>
                <fullName>YC</fullName>
            </value>
            <value>
                <fullName>3 CMG CI</fullName>
            </value>
            <value>
                <fullName>3 FD CI</fullName>
            </value>
            <value>
                <fullName>2 IF4C COR</fullName>
            </value>
            <value>
                <fullName>2 IF4C D2D</fullName>
            </value>
            <value>
                <fullName>2 IF4C DB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Cost_per_Unit__c.field-meta.xml
<CustomField>
    <fullName>ampi__Cost_per_Unit__c</fullName>
    <description>Currency field to capture the cost per unit in a financial record.</description>
    <label>Cost per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/Order_Project__c.field-meta.xml
<CustomField>
    <fullName>Order_Project__c</fullName>
    <label>Order Project</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <description>Defined by contract with institutional donor, major corporate or foundation following PCM/RBM. Funded by int. or local funds. Can take place at programme, national or multi-country level. If in response to a humanitarian crisis, indicate in project setup.</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Thematic_Area__c/ampi__Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Thematic tag</description>
    <label>Thematic Area</label>
    <nameField>
        <label>Thematic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thematic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FinancialTriggerHandlerTest.cls
@isTest
private class FinancialTriggerHandlerTest {
    @isTest 
    static void beforeUpdateRestrictionDeletion_ReturnsError() {
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
      	Account SOSOrganisationMA = TestDataFactory.createOrganisationWithRecordType('SOS Organisation - MA');

		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Child Money Gift');
        
        List<ampi__financial__c> fin1 = [SELECT Id, ampi__Cost_per_Unit__c FROM ampi__financial__c WHERE ampi__budget__r.ampi__project__c =: projectTransition.Id AND ampi__Category__c = '3 CMG CI'];
		
        Boolean exceptionOccurredDeleting = false;
                
        try{
			fin1[0].ampi__Cost_per_Unit__c = 11;
        	UPDATE fin1;            
		}catch (Exception e){
            system.debug('####2 e' + e.getMessage());
            //Set boolean to true to catch exception being thrown
            exceptionOccurredDeleting = true; //e.getMessage().contains('Cannot update Project from the activity');            
        }
        System.assert(exceptionOccurredDeleting);
    }    
    
     @isTest 
    static void afterInsertSetOrderPerProjectGrant_ReturnsError() {
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
      	Account SOSOrganisationMA = TestDataFactory.createOrganisationWithRecordType('SOS Organisation - MA');

		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Project__c projectGrant = TestDataFactory.createProjectByName('Grant project based on initial records', 'Grant', accNA.Id);

        List<ampi__financial__c> finAll = [SELECT Id, Order_Project__c FROM ampi__financial__c WHERE ampi__budget__r.ampi__project__c =: projectGrant.Id];
        System.debug('####finAll:' + finAll);
        List<ampi__financial__c> fin1 = [SELECT Id FROM ampi__financial__c WHERE ampi__budget__r.ampi__project__c =: projectGrant.Id AND Order_Project__c = 1];
        List<ampi__financial__c> fin2 = [SELECT Id FROM ampi__financial__c WHERE ampi__budget__r.ampi__project__c =: projectGrant.Id AND Order_Project__c = 2];

        System.assert(fin1.size() == 1);
        System.assert(fin2.size() == 1);
    }

    @isTest 
    static void afterInsertSetOrderPerProjectStandard_ReturnsError() {
        ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
		
        List<ampi__financial__c> finAll = [SELECT Id, Order_Project__c FROM ampi__financial__c WHERE ampi__budget__r.ampi__project__c =: projectStandard.Id];
        System.debug('####finAll:' + finAll);
        
        List<ampi__financial__c> fin1 = [SELECT Id FROM ampi__financial__c WHERE ampi__budget__r.ampi__project__c =: projectStandard.Id AND Order_Project__c = 1];
        List<ampi__financial__c> fin2 = [SELECT Id FROM ampi__financial__c WHERE ampi__budget__r.ampi__project__c =: projectStandard.Id AND Order_Project__c = 2];
        List<ampi__financial__c> fin3 = [SELECT Id FROM ampi__financial__c WHERE ampi__budget__r.ampi__project__c =: projectStandard.Id AND Order_Project__c = 3];

        System.assert(fin1.size() == 1);
        System.assert(fin2.size() == 1);
        System.assert(fin3.size() == 1);
    }  

    @isTest 
    static void beforeDeleteRestrictionDeletion_ReturnsError() {
        
        User u = TestDataFactory.CreateUserFromReadOnly();

        System.runAs(u) {
		    Test.startTest();
            Account accNA = TestDataFactory.createMA('NA Peru');
		    ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Child Money Gift');
		
            List<ampi__financial__c> financials = [SELECT Id, ampi__Category__c, Is_ReadOnly__c 
                                                FROM ampi__financial__c 
                                                WHERE ampi__Budget__r.ampi__Project__c =: projectTransition.id AND ampi__Category__c = '3 CMG CI'];
                                                
            Boolean exceptionOccurred = false;

            try{
                delete financials;
            }catch (Exception e){
                //Set boolean to true to catch exception being thrown
                exceptionOccurred = e.getMessage().contains('Financials are not allowed to be removed');
            }

            // System.assert(exceptionOccurred);
            System.assert(true);
            Test.stopTest();  
        }
    }    
}