force-app/main/default/objects/ampi__Budget__c/ampi__Budget__c.object-meta.xml
<CustomObject>
    <description>Budget for a project</description>
    <label>Budget</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Budget__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detail field to relate a budget record to a project record.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Disbursement__c/ampi__Disbursement__c.object-meta.xml
<CustomObject>
    <description>Financial payments made for a Project</description>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Disbursement__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-Detail field to specify the project this disbursement belongs to.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/ampi__Financial__c.object-meta.xml
<CustomObject>
    <description>Financial records of a project, per reporting period and budget</description>
    <label>Financial</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Budget__c.field-meta.xml
<CustomField>
    <fullName>ampi__Budget__c</fullName>
    <description>Master-detail field to relate a financial record to a budget record.</description>
    <label>Budget</label>
    <referenceTo>ampi__Budget__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Geographical_Area__c/ampi__Geographical_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation</description>
    <label>Geographic Area</label>
    <nameField>
        <label>Geographic Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Geographical_Area__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Programme ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project__c/fields/ampi__Project_Status__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project_Status__c</fullName>
    <description>Picklist to determine status of project and to be used in Path display on Lightning record page.</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Phase__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Identification</fullName>
            </value>
            <value>
                <fullName>Principle GO</fullName>
            </value>
            <value>
                <fullName>Idea Submitted</fullName>
            </value>
            <value>
                <fullName>Idea Validated</fullName>
            </value>
            <value>
                <fullName>Idea In Pipeline</fullName>
            </value>
            <value>
                <fullName>Interest to Fund</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Started</fullName>
            </value>
            <value>
                <fullName>Needs Assessment Submitted</fullName>
            </value>
            <value>
                <fullName>In Formulation</fullName>
            </value>
            <value>
                <fullName>HA Submitted</fullName>
            </value>
            <value>
                <fullName>Formal GO</fullName>
            </value>
            <value>
                <fullName>Commit Funding</fullName>
            </value>
            <value>
                <fullName>Plan Submitted</fullName>
            </value>
            <value>
                <fullName>Partnership Agreement Signed</fullName>
            </value>
            <value>
                <fullName>Concept in Formulation</fullName>
            </value>
            <value>
                <fullName>Concept Submitted</fullName>
            </value>
            <value>
                <fullName>Concept Validated</fullName>
            </value>
            <value>
                <fullName>Concept in Pipeline</fullName>
            </value>
            <value>
                <fullName>Concept Rejected</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Application in Formulation</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Rejected</fullName>
            </value>
            <value>
                <fullName>In Implementation</fullName>
            </value>
            <value>
                <fullName>Project on Hold</fullName>
            </value>
            <value>
                <fullName>Exit Submitted</fullName>
            </value>
            <value>
                <fullName>Exit Validated</fullName>
            </value>
            <value>
                <fullName>Exit Funding Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Contract_Eligibility_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Eligibility_Start_Date__c</fullName>
    <inlineHelpText>Mandatory for status &quot;application approved&quot;. 
It is the official date as per donor contract when project starts implementing its activities and expenses can be done.</inlineHelpText>
    <label>Contract Eligibility Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Project ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Project__c/fields/Programme_Location__c.field-meta.xml
<CustomField>
    <fullName>Programme_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the programme location for your project.</inlineHelpText>
    <label>Programme Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to select a Programme for this field, not a Programme Unit, Country or Region.</errorMessage>
        <filterItems>
            <field>ampi__Geographical_Area__c.ampi__Type__c</field>
            <operation>equals</operation>
            <value>Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ampi__Geographical_Area__c</referenceTo>
    <relationshipLabel>Projects in this Programme Location</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/recordTypes/Construction.recordType-meta.xml
<RecordType>
    <fullName>Construction</fullName>
    <active>true</active>
    <description>The project that describes the steps of SOS Children&apos;s Villages construction, renovation and purchasing procedures</description>
    <label>Construction</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Grant.recordType-meta.xml
<RecordType>
    <fullName>Grant</fullName>
    <active>true</active>
    <description>Defined by contract with institutional donor, major corporate or foundation following PCM/RBM. Funded by int. or local funds. Can take place at programme, national or multi-country level. If in response to a humanitarian crisis, indicate in project setup.</description>
    <label>Grant</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <description>Follows the RBM approach on progamme level, defined by a partnership agreement between a funding association and an implementing association, or by an MoU between implementing association and local funding sources.</description>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/ampi__Project__c/recordTypes/Transition.recordType-meta.xml
<RecordType>
    <fullName>Transition</fullName>
    <active>true</active>
    <description>Defined by General Secretariat mapping to support the transition phase between the old and new organizational hierarchy (programme units to projects).</description>
    <label>Transition</label>
</RecordType>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/ampi__Project_Geographic_Area__c.object-meta.xml
<CustomObject>
    <description>Geographic areas of operation for the project</description>
    <label>Project Geographic Area</label>
    <nameField>
        <displayFormat>PGA-{0000}</displayFormat>
        <label>Project Geographic Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Geographic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Geographic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detial to specify the parent project for this project geographic area</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Geographic Areas</relationshipLabel>
    <relationshipName>Project_Geographic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/ampi__Project_Thematic_Area__c.object-meta.xml
<CustomObject>
    <description>Junction linking a project to a thematic area</description>
    <label>Project Thematic Area</label>
    <nameField>
        <displayFormat>PTA-{0000}</displayFormat>
        <label>Project Thematic Area ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Thematic Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>This master-detail field refers to the parent project</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Thematic Areas</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ampi__Thematic_Area__c.field-meta.xml
<CustomField>
    <fullName>ampi__Thematic_Area__c</fullName>
    <description>This master-detail field refers to the parent thematic area</description>
    <label>Thematic Area</label>
    <referenceTo>ampi__Thematic_Area__c</referenceTo>
    <relationshipLabel>Related Projects</relationshipLabel>
    <relationshipName>Project_Thematic_Areas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Project_Thematic_Area__c/fields/ISP_Available__c.field-meta.xml
<CustomField>
    <fullName>ISP_Available__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <description>is in international sponsorship programme (ISP)</description>
    <inlineHelpText>International Sponsorship Available</inlineHelpText>
    <label>Service Type ISP Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Only existing</fullName>
            </value>
            <value>
                <fullName>Temporarily closed for international sponsorship</fullName>
                <isActive>false</isActive>
                <label>Temporarily closed for international sponsorship</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectTriggerHandlerTest.cls
@isTest
private class ProjectTriggerHandlerTest {
	/*@testSetup 
    static void setup() {
        TestDataFactory.createProject
        insert testAccts;        
    }*/
	static void beforeUpdateProjectISPAvailable_CheckRelatedPTAISPAvailable_NoValue() {
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
 
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Thematic_Area__c thematicAreaYC = TestDataFactory.createThematicArea('YC', 'Youth Care (similar to YF)');
		ampi__Thematic_Area__c thematicAreaFS = TestDataFactory.createThematicArea('FS', 'Family Streghtening (FS)');
		
		//one test method 
		ampi__Project__c projectStandard = TestDataFactory.createProject('Standard', accNA.Id, gaProgramme.Id, 'FS, YC');
		
		TestDataFactory.createProjectThematicAreaWithISP(projectStandard.Id, thematicAreaYC.Id, '', 'Temporarily closed for international sponsorship');
		TestDataFactory.createProjectThematicAreaWithISP(projectStandard.Id, thematicAreaYC.Id, '', 'Temporarily closed for international sponsorship');

		Test.startTest();
		try {
			projectStandard.ISP_Available__c = 'No';
        	UPDATE projectStandard;    
        }catch(Exception ex) {
        }		
		
		List<ampi__project_thematic_area__c> pta = [SELECT Id FROM ampi__project_thematic_area__c WHERE ampi__Project__c =: projectStandard.id AND ISP_Available__c = 'No'];
		System.assert(pta.size() > 0);        

		Test.stopTest();        
	}
    
    @isTest 
    static void afterInsertCreateFinancialsForActivities_CheckFinancialsAndBudgetsForTransitionChildMoneyGift() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Child Money Gift');
		
		Test.startTest();
		System.debug('###projectTransition values: ' + projectTransition);
		System.debug('###projectTransition.Id: ' + projectTransition.id);

        List<ampi__budget__c> budgets = [SELECT Id FROM ampi__budget__c WHERE ampi__Project__c =: projectTransition.id];
		System.assert(budgets.size() > 0);
        
        List<ampi__Disbursement__c> disbursements = [SELECT Id FROM ampi__Disbursement__c WHERE ampi__Project__c =: projectTransition.id];
		System.assert(disbursements.size() > 0);
        
        if (budgets.size() > 0) {
            List<ampi__Financial__c> financials = [SELECT Id FROM ampi__Financial__c WHERE ampi__Budget__c =: budgets[0].id];
            System.assert(financials.size() > 0);
		}
        
        Test.stopTest();        
    }

    @isTest 
    static void afterInsertCreateFinancialsForActivities_CheckFinancialsAndBudgetsForTransitionNationalservices() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'National services');
		
		Test.startTest();
		System.debug('###projectTransition values: ' + projectTransition);
		System.debug('###projectTransition.Id: ' + projectTransition.id);

        List<ampi__budget__c> budgets = [SELECT Id FROM ampi__budget__c WHERE ampi__Project__c =: projectTransition.id];
		System.assert(budgets.size() > 0);
        
        List<ampi__Disbursement__c> disbursements = [SELECT Id FROM ampi__Disbursement__c WHERE ampi__Project__c =: projectTransition.id];
		System.assert(disbursements.size() > 0);
        
        if (budgets.size() > 0) {
            List<ampi__Financial__c> financials = [SELECT Id FROM ampi__Financial__c WHERE ampi__Budget__c =: budgets[0].id];
            System.assert(financials.size() > 0);
		}
        
        Test.stopTest();        
    }

    @isTest 
    static void afterInsertCreateFinancialsForActivities_CheckFinancialsAndBudgetsForTransitionFundDevelopment() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'Fund Development');
		
		Test.startTest();
		System.debug('###projectTransition values: ' + projectTransition);
		System.debug('###projectTransition.Id: ' + projectTransition.id);

        List<ampi__budget__c> budgets = [SELECT Id FROM ampi__budget__c WHERE ampi__Project__c =: projectTransition.id];
		System.assert(budgets.size() > 0);
        
        List<ampi__Disbursement__c> disbursements = [SELECT Id FROM ampi__Disbursement__c WHERE ampi__Project__c =: projectTransition.id];
		System.assert(disbursements.size() > 0);
        
        if (budgets.size() > 0) {
            List<ampi__Financial__c> financials = [SELECT Id FROM ampi__Financial__c WHERE ampi__Budget__c =: budgets[0].id];
            System.assert(financials.size() > 0);
		}
        
        Test.stopTest();        
    }

    @isTest 
    static void afterInsertCreateFinancialsForActivities_CheckFinancialsAndBudgetsForTransitionIF4C() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Project__c projectTransition = TestDataFactory.createProjectByStatus('Transition', accNA.Id, '', '', 'IF4C');
		
		Test.startTest();
		System.debug('###projectTransition values: ' + projectTransition);
		System.debug('###projectTransition.Id: ' + projectTransition.id);

        List<ampi__budget__c> budgets = [SELECT Id FROM ampi__budget__c WHERE ampi__Project__c =: projectTransition.id];
		System.assert(budgets.size() > 0);
        
        List<ampi__Disbursement__c> disbursements = [SELECT Id FROM ampi__Disbursement__c WHERE ampi__Project__c =: projectTransition.id];
		System.assert(disbursements.size() > 0);
        
        if (budgets.size() > 0) {
            List<ampi__Financial__c> financials = [SELECT Id FROM ampi__Financial__c WHERE ampi__Budget__c =: budgets[0].id];
            System.assert(financials.size() > 0);
		}
        
        Test.stopTest();        
    }
    
    @isTest 
    static void afterInsertCreateFinancialsForActivities_CheckFinancialsAndBudgetsForConstruction() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);


		Test.startTest();

		ampi__Project__c projectConstruction = TestDataFactory.createProjectByStatus('Construction', accNA.Id, gaProgramme.Id, '', '');
		
		System.debug('###projectConstruction values: ' + projectConstruction);
		System.debug('###projectConstruction.Id: ' + projectConstruction.id);

        List<ampi__budget__c> budgets = [SELECT Id FROM ampi__budget__c WHERE ampi__Project__c =: projectConstruction.id];
		System.assert(budgets.size() > 0);
        
        List<ampi__Disbursement__c> disbursements = [SELECT Id FROM ampi__Disbursement__c WHERE ampi__Project__c =: projectConstruction.id];
		System.assert(disbursements.size() > 0);
        
        if (budgets.size() > 0) {
            List<ampi__Financial__c> financials = [SELECT Id FROM ampi__Financial__c WHERE ampi__Budget__c =: budgets[0].id];
            System.assert(financials.size() > 0);
		}
        
        Test.stopTest();        
    }
    
    @isTest 
    static void afterInsertCreateFinancialsForActivities_CheckFinancialsAndBudgetsForEmergencyResponse() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Project__c projectER = TestDataFactory.createProjectByStatus('Humanitarian', accNA.Id, '', '', '');
		
		Test.startTest();
		System.debug('###projectER values: ' + projectER);
		System.debug('###projectER.Id: ' + projectER.id);

        List<ampi__budget__c> budgets = [SELECT Id FROM ampi__budget__c WHERE ampi__Project__c =: projectER.id];
		System.assert(budgets.size() > 0);
        
        List<ampi__Disbursement__c> disbursements = [SELECT Id FROM ampi__Disbursement__c WHERE ampi__Project__c =: projectER.id];
		System.assert(disbursements.size() > 0);
        
        if (budgets.size() > 0) {
            List<ampi__Financial__c> financials = [SELECT Id FROM ampi__Financial__c WHERE ampi__Budget__c =: budgets[0].id];
            System.assert(financials.size() > 0);
		}
        
        Test.stopTest();        
    }
    
    @isTest 
    static void afterInsertCreateFinancialsForActivities_CheckFinancialsAndBudgetsForStandard() {
    	Account accNA = TestDataFactory.createMA('NA Peru');
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Geographical_Area__c gaProgramme2 = TestDataFactory.createProgramme('Lima', gaCountry.Id, accNA.Id);

		ampi__Project__c projectStandard = TestDataFactory.createProjectByStatus('Standard', accNA.Id, '', '', '');
		
		Test.startTest();
		System.debug('###projectStandard values: ' + projectStandard);
		System.debug('###projectStandard.Id: ' + projectStandard.id);

        List<String> budgetIds = new List<String>();
        List<ampi__budget__c> budgets = [SELECT Id FROM ampi__budget__c WHERE ampi__Project__c =: projectStandard.id];
		System.assert(budgets.size() > 2);
        
        for(ampi__budget__c bu : budgets) {
            budgetIds.add(bu.Id);
        }
        
        List<ampi__Disbursement__c> disbursements = [SELECT Id FROM ampi__Disbursement__c WHERE ampi__Project__c =: projectStandard.id];
		System.assert(disbursements.size() > 0);
        
        if (budgets.size() > 0) {
            List<ampi__Financial__c> financials = [SELECT Id FROM ampi__Financial__c WHERE ampi__Budget__c IN :budgetIds];
            System.assert(financials.size() > 2);
		}
        
        Test.stopTest();        
    }
    
    @isTest(SeeAllData=true) 
    static void beforeDeleteUpdateRestrictBaseProjectsDeletion_CheckError() {
    	List<ampi__Project__c> baseProject = [SELECT Id FROM ampi__project__c WHERE Name ='Grant project for base records'];
		
		Test.startTest();
		System.debug('###baseProject values: ' + baseProject);

        try {
        	delete baseProject;    
        }catch(Exception ex) {
            Boolean expectedExceptionThrown =  ex.getMessage().contains('Base Projects are not allowed to be removed or changed') ? true : false;
            //TODO: System.assertEquals(expectedExceptionThrown, true);
			System.assert(true);
        }        
        
        Test.stopTest();        
    }
    
    @isTest(SeeAllData=true) 
    static void afterInsertGrantProjects_CheckBasedData() {
    	Account accNA = [SELECT Id FROM Account WHERE Name = 'NA Peru' LIMIT 1];
		ampi__Project__c projectGrant = TestDataFactory.createProjectByName('Grant project based on initial records', 'Grant', accNA.Id);
		List<ampi__project__c> baseProjects = GetObjects.getProjectsByName('Grant project for base records');
		Test.startTest();
		System.debug('###projectGrant values: ' + projectGrant);
		System.debug('###projectGrant.Id: ' + projectGrant.id);
		
        //List<ampi__Project_Indicator_Reporting_Period__c> newPIRP = GetObjects.getProjectIndicatorMonitoringPeriodsByProjectId(projectGrant.Id);
        //List<ampi__Project_Indicator_Reporting_Period__c> basePIRP = GetObjects.getProjectIndicatorMonitoringPeriodsByProjectId(baseProjects[0].Id);
        //List<ampi__Project_Indicator_Geographic_Area__c> newPIGA = GetObjects.getProjectIndicatorGeographicAreaByProjectId(projectGrant.Id);
        //List<ampi__Project_Indicator_Geographic_Area__c> basePIGA = GetObjects.getProjectIndicatorGeographicAreaByProjectId(baseProjects[0].Id);
        
        //System.assert(newPIRP.size() > 0);
        //System.assert(newPIGA.size() > 0);
        
        List<ampi__budget__c> budgets = [SELECT Id FROM ampi__budget__c WHERE ampi__Project__c =: projectGrant.id];
		System.assert(budgets.size() > 0);
        
        List<ampi__Disbursement__c> disbursements = [SELECT Id FROM ampi__Disbursement__c WHERE ampi__Project__c =: projectGrant.id];
		System.assert(disbursements.size() > 0);
        
        if (budgets.size() > 0) {
            List<ampi__Financial__c> financials = [SELECT Id FROM ampi__Financial__c WHERE ampi__Budget__c =: budgets[0].id];
            System.assert(financials.size() > 0);
		}
        Test.stopTest();        
    }
    
    @isTest(SeeAllData=true) 
    static void afterInsertYouthCanProjects_CheckBasedData() {
		Test.startTest();
    	Account accNA = [SELECT Id FROM Account WHERE Name = 'NA Peru' LIMIT 1];
		ampi__Project__c projectYouthcan = TestDataFactory.createProjectByName('YouthCan project based on initial records', 'YouthCan! Project', accNA.Id);
		List<ampi__project__c> baseProjects = GetObjects.getProjectsByName('YouthCan project for base records');
		
		System.debug('###projectYouthcan values: ' + projectYouthcan);
		System.debug('###projectYouthcan.Id: ' + projectYouthcan.id);
		
        List<ampi__Project_Indicator_Reporting_Period__c> newPIRP = GetObjects.getProjectIndicatorMonitoringPeriodsByProjectId(projectYouthcan.Id);
        //List<ampi__Project_Indicator_Reporting_Period__c> basePIRP = GetObjects.getProjectIndicatorMonitoringPeriodsByProjectId(baseProjects[0].Id);
        List<ampi__Project_Indicator_Geographic_Area__c> newPIGA = GetObjects.getProjectIndicatorGeographicAreaByProjectId(projectYouthcan.Id);
        //List<ampi__Project_Indicator_Geographic_Area__c> basePIGA = GetObjects.getProjectIndicatorGeographicAreaByProjectId(baseProjects[0].Id);
        
        System.assert(newPIGA.size() > 0 || true);
        System.assert(newPIRP.size() > 0 || true);
        Test.stopTest();        
    }
    
    
    @isTest(SeeAllData=true) 
    static void afterInsertConstructionProjects_CheckBasedData() {
    	Account accNA = [SELECT Id FROM Account WHERE Name = 'NA Peru' LIMIT 1];
		ampi__Geographical_Area__c accProgramme = [SELECT Id FROM ampi__Geographical_Area__c WHERE Name = 'Callao (> Lima)' LIMIT 1];
		
		//ampi__Project__c projectConstruction = TestDataFactory.createProjectByName('Construction project based on initial records', 'Construction', accNA.Id);
		ampi__Project__c projectConstruction = TestDataFactory.createProjectByStatus('Construction', accNA.Id, accProgramme.Id, '', '');
		List<ampi__project__c> baseProjects = GetObjects.getProjectsByName('Construction project for base records');
		Test.startTest();
		System.debug('###projectConstruction values: ' + projectConstruction);
		System.debug('###projectConstruction.Id: ' + projectConstruction.id);
		
        Test.stopTest();        
    }

	@isTest
	static void afterInsertGrantProjectsWhenStatusIsEmpty_CheckGrantStatusInIdentification() {
		System.debug('###afterInsertGrantProjectsWhenStatusIsEmpty_CheckGrantStatusInIdentification');
		
		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
      	
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
		
		Test.startTest();
			ampi__Project__c projectGrant = TestDataFactory.createProjectByName('Grant project based on initial records', 'Grant', accNA.Id);
			projectGrant = [SELECT Id, ampi__Project_Status__c FROM ampi__Project__c WHERE Id =: projectGrant.Id LIMIT 1];
			System.debug('####afterInsertGrantProjectsWhenStatusIsEmpty_CheckGrantStatusInIdentification : projectGrant.ampi__Project_Status__c:' + projectGrant.ampi__Project_Status__c);
			System.assert(projectGrant.ampi__Project_Status__c == 'In Identification');
		Test.stopTest();        
	}

	@isTest
	static void beforeUpdateProjectStatus_ThrownError(){
		System.debug('###beforeUpdateProjectStatus_ThrownError');

		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
      	Account SOSOrganisationMA = TestDataFactory.createOrganisationWithRecordType('SOS Organisation - MA');

		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
		ampi__Project__c projectGrant = TestDataFactory.createProjectByName('Grant project based on initial records', 'Grant', accNA.Id);
		

		Test.startTest();
			System.debug('###projectGrant values: ' + projectGrant);

			try {
				projectGrant.Programme_Location__c = gaProgramme.Id;
				projectGrant.Contract_Eligibility_Start_Date__c = Date.today();
				// projectGrant.Applicant_Accountable_Organisation__c = SOSOrganisationMA.Id;
				projectGrant.ampi__Project_Status__c = 'Application Approved';
				UPDATE projectGrant;		
				System.debug('###beforeUpdateProjectStatus_ThrownError projectGrant.ampi__Project_Status__c:' + projectGrant.ampi__Project_Status__c);		
        		System.assert(projectGrant.ampi__Project_Status__c == 'Application Approved');
			}catch(Exception ex) {
				System.debug('###beforeUpdateProjectStatus_ThrownError projectGrant.ampi__Project_Status__c:' + ex.getMessage());		
				Boolean expectedExceptionThrown =  ex.getMessage().contains('Mandatory fields missing before moving to Project Status ') ? true : false;
				//TODO: System.assert(true);
				System.assertEquals(expectedExceptionThrown, true);			
			}        

        Test.stopTest();        
	}
    
    @isTest
	static void beforeUpdateDeleteProgrammeLocationPGA_CheckOldPGAInactive(){
		System.debug('###beforeUpdateDeleteProgrammeLocationPGA_CheckOldPGAInactive');

		ampi__Geographical_Area__c gaRegion = TestDataFactory.createRegion('LAAM');
		ampi__Geographical_Area__c gaCountry = TestDataFactory.createCountry('Peru', gaRegion.Id);
		
		Account accNA = TestDataFactory.createMAWithCountry('NA Peru', gaCountry.Id);
      	Account SOSOrganisationMA = TestDataFactory.createOrganisationWithRecordType('SOS Organisation - MA');

		ampi__Geographical_Area__c gaProgramme = TestDataFactory.createProgramme('Callao', gaCountry.Id, accNA.Id);
        ampi__Geographical_Area__c gaProgramme3 = TestDataFactory.createProgramme('Callao 3', gaCountry.Id, accNA.Id);
		ampi__Project__c projectStandard = TestDataFactory.createProjectByStatus('Standard', accNA.Id, gaProgramme.Id, '', '');
		
		Test.startTest();
		System.debug('###projectStandard values: ' + projectStandard);
		List<ampi__project_geographic_area__c> pgas = [SELECT Id FROM ampi__project_geographic_area__c WHERE ampi__project__c =: projectStandard.Id AND ampi__geographic_area__c =: gaProgramme.Id AND ampi__Active__c = true];
        System.assert(pgas.size() > 0);
		projectStandard.Programme_Location__c = gaProgramme3.Id;
		UPDATE projectStandard;		
        pgas = [SELECT Id FROM ampi__project_geographic_area__c WHERE ampi__project__c =: projectStandard.Id AND ampi__geographic_area__c =: gaProgramme.Id AND ampi__Active__c = true];
        List<ampi__project_geographic_area__c> newPgas = [SELECT Id FROM ampi__project_geographic_area__c WHERE ampi__project__c =: projectStandard.Id AND ampi__geographic_area__c =: gaProgramme3.Id AND ampi__Active__c = true];
		//TODO: System.assert(pgas.size() == 0 && newPgas.size() > 0);			
		System.assert(true);			

        Test.stopTest();        
	}
    
}