force-app/main/default/objects/ampi__Budget__c/ampi__Budget__c.object-meta.xml
<CustomObject>
    <description>Budget for a project</description>
    <label>Budget</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Budget__c/fields/ampi__Project__c.field-meta.xml
<CustomField>
    <fullName>ampi__Project__c</fullName>
    <description>Master-detail field to relate a budget record to a project record.</description>
    <label>Project</label>
    <referenceTo>ampi__Project__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/fields/Is_ReadOnly__c.field-meta.xml
<CustomField>
    <fullName>Is_ReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ReadOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/fields/Order_Financial__c.field-meta.xml
<CustomField>
    <fullName>Order_Financial__c</fullName>
    <label>Order Financial</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ampi__Budget__c/fields/Order_Project__c.field-meta.xml
<CustomField>
    <fullName>Order_Project__c</fullName>
    <label>Order Project</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/ampi__Financial__c.object-meta.xml
<CustomObject>
    <description>Financial records of a project, per reporting period and budget</description>
    <label>Financial</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Budget__c.field-meta.xml
<CustomField>
    <fullName>ampi__Budget__c</fullName>
    <description>Master-detail field to relate a financial record to a budget record.</description>
    <label>Budget</label>
    <referenceTo>ampi__Budget__c</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/ampi__Category__c.field-meta.xml
<CustomField>
    <fullName>ampi__Category__c</fullName>
    <description>This picklist field is for categorizing Financial records based on their purpose. This field is unrestricted and can be modified by subscribers.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Result based</fullName>
            </value>
            <value>
                <fullName>9 PSCI</fullName>
            </value>
            <value>
                <fullName>Overarching</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>ADV</fullName>
            </value>
            <value>
                <fullName>SIL</fullName>
            </value>
            <value>
                <fullName>FLC</fullName>
            </value>
            <value>
                <fullName>DFE</fullName>
            </value>
            <value>
                <fullName>CFE</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>HA</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>ECD</fullName>
            </value>
            <value>
                <fullName>EDU</fullName>
            </value>
            <value>
                <fullName>EET</fullName>
            </value>
            <value>
                <fullName>ER</fullName>
            </value>
            <value>
                <fullName>FFC</fullName>
            </value>
            <value>
                <fullName>FS</fullName>
            </value>
            <value>
                <fullName>HPP</fullName>
            </value>
            <value>
                <fullName>MED</fullName>
            </value>
            <value>
                <fullName>OA</fullName>
            </value>
            <value>
                <fullName>OAC</fullName>
            </value>
            <value>
                <fullName>SGH</fullName>
            </value>
            <value>
                <fullName>SFC</fullName>
            </value>
            <value>
                <fullName>YC</fullName>
            </value>
            <value>
                <fullName>3 CMG CI</fullName>
            </value>
            <value>
                <fullName>3 FD CI</fullName>
            </value>
            <value>
                <fullName>2 IF4C COR</fullName>
            </value>
            <value>
                <fullName>2 IF4C D2D</fullName>
            </value>
            <value>
                <fullName>2 IF4C DB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ampi__Financial__c/fields/Order_Project__c.field-meta.xml
<CustomField>
    <fullName>Order_Project__c</fullName>
    <label>Order Project</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ampi__Project__c/ampi__Project__c.object-meta.xml
<CustomObject>
    <description>Project or grant where progress against goals needs to be measured</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BudgetTriggerHandler.cls
public class BudgetTriggerHandler {
	public void beforeInsertSetOrderPerProject(List<ampi__Budget__c> newBudgetsToUpdate) {
    	/*if (newBudgets.size() == 0) {
            return;
        }*/
        
        Decimal order = 0;
        Id projectId;
        Boolean hasRecordsToUpdate = false; 
        //Set<Id> ids = (new Map<Id, ampi__Budget__c>(newBudgets)).keySet();
        //List<ampi__Budget__c> newBudgetsToUpdate = newBudgets.deepClone();//[SELECT Id, Order_Project__c, ampi__Project__c FROM ampi__Budget__c WHERE Id =: ids AND ampi__Project__c != ''];
        
        if (newBudgetsToUpdate.size() > 0) {
            projectId = newBudgetsToUpdate[0].ampi__Project__c;
        } else {
            return;
        }
        
        List<ampi__Budget__c> checkOrders = [SELECT Id, Order_Project__c FROM ampi__Budget__c 
                                             WHERE ampi__Project__c =: projectId AND Order_Project__c <> NULL 
                                             ORDER BY Order_Project__c DESC];

        Integer initialBudgetOrderPerProject = 0;        
        Integer countBudgetOrderPerProject = 0;
        if (checkOrders.size() > 0) {
            initialBudgetOrderPerProject = Integer.ValueOf(checkOrders[0].Order_Project__c);
        }
        
        for(ampi__Budget__c newBudget : newBudgetsToUpdate) {            
                if (projectId != newBudget.ampi__Project__c) {
                	projectId = newBudget.ampi__Project__c;
                    order = 0;
                    //List<ampi__Budget__c> checkOrders = [SELECT Id, Order_Project__c FROM ampi__Budget__c WHERE ampi__Project__c =: projectId AND Order_Project__c <> NULL ORDER BY Order_Project__c DESC LIMIT 1];
                    if (initialBudgetOrderPerProject > 0) { 
                        countBudgetOrderPerProject += 1;
            			order = initialBudgetOrderPerProject + countBudgetOrderPerProject;
                    } else {
                        order = order + 1;
                    }
                } else {
                	order = order + 1;
                }           

                if (newBudget.Order_Project__c != order) {
                    hasRecordsToUpdate = true;                
                    newBudget.Order_Project__c = order;
                }   
        }
        
        //if (hasRecordsToUpdate) {
        //    UPDATE newBudgetsToUpdate;
        //}
    }   

    //public void beforeDeleteUpdateRestrictionDeletion(List<ampi__Budget__c> newBudgets) {
    public void beforeUpdateRestrictionDeletion(List<ampi__Budget__c> newBudgets, List<ampi__Budget__c> oldBudgets) {
        //List<ampi__Budget__c> newBudgets = newMapBudgets.keySet();
        System.debug('#queries-4:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        Set<Id> budgetIds = (new Map<Id, ampi__Budget__c>(newBudgets)).keySet();
        
        List<ampi__financial__c> currentFinancials = [SELECT Id, ampi__budget__c FROM ampi__financial__c WHERE ampi__budget__c =: budgetIds AND ampi__Category__c = '3 CMG CI'];
		System.debug('#queries-4:' + Limits.getQueries() + ' max queries: ' + Limits.getLimitQueries());
        for(ampi__Budget__c acc : newBudgets){
            ampi__Budget__c currentBudget;
            for(ampi__Budget__c accold : oldBudgets) {
                if (acc.Id == accold.Id) {
                    currentBudget = accold;
                }
            }    
                
            for(ampi__financial__c currentFinancial : currentFinancials) {
                if (currentFinancial.ampi__budget__c == acc.Id) {
                    if (acc.Order_Project__c == currentBudget.Order_Project__c && acc.Order_Financial__c == currentBudget.Order_Financial__c) {
                        acc.addError('Budgets from category "3 CMG CI" are not allowed to be removed or changed');
                    }
                }            

                if (acc.Is_ReadOnly__c == true) {
                    //if (acc.Id == accold.Id && acc.Order_Project__c == accold.Order_Project__c) {
                    if (acc.Order_Project__c == currentBudget.Order_Project__c && acc.Order_Financial__c == currentBudget.Order_Financial__c) {
                    	//acc.addError('Budgets are not allowed to be removed or changed U: old ' + accold.Order_Financial__c + ' new ' + acc.Order_Financial__c + ' U: old ' + accold.Order_Project__c + ' new ' + acc.Order_Project__c);
                        acc.addError('Budgets are not allowed to be removed or changed');
                    }
                } 
            }
        } 
    }

    public void beforeDeleteRestrictionDeletion(List<ampi__Budget__c> newBudgets) {
        //List<ampi__Budget__c> newBudgets = newMapBudgets.keySet();
        for(ampi__Budget__c acc : newBudgets){
            List<ampi__financial__c> currentFinancials = [SELECT Id, ampi__Category__c FROM ampi__financial__c WHERE ampi__budget__c =: acc.Id];

            for(ampi__financial__c currentFinancial : currentFinancials) {
                if (currentFinancial.ampi__Category__c == '3 CMG CI') {
                    acc.addError('Budgets from category "3 CMG CI" are not allowed to be removed or changed');
                }            

                if (acc.Is_ReadOnly__c == true) {
                    acc.addError('Budgets are not allowed to be removed or changed');
                } 
            }
        } 
    }
}